import { test, expect, type Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { freshSave } from '../../src/systems/progress';
import { FAMILY_IDS } from '../../src/families/types';
import { familyConfig } from '../../src/families/specs';
import { validateCareer } from '../../src/career/validation';
import { productionOrigin } from './productionOrigin';
test.describe.configure({mode:'parallel'});test.use({screenshot:'only-on-failure'});
async function prepare(page:Page,locale:'en'|'es'='en'){const save=freshSave();save.selectedDifficulty=true;save.settings.tutorials=false;save.settings.muted=true;save.settings.reducedMotion=true;save.settings.locale=locale;await page.addInitScript(v=>{if(!localStorage.getItem('brain-sweat-studio:v1'))localStorage.setItem('brain-sweat-studio:v1',JSON.stringify(v));},save);}
const saved=(page:Page)=>page.evaluate(()=>JSON.parse(localStorage.getItem('brain-sweat-studio:v1')!).academy.career);
async function create(page:Page){await page.getByRole('button',{name:'Create passport',exact:true}).click();await page.getByRole('button',{name:'Enable circuit families',exact:true}).click();}
async function episode(page:Page){await page.getByRole('button',{name:'Prepare handoff',exact:true}).click();await page.getByRole('button',{name:'Run episode',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Execution status'})).toContainText('COMPLETE');}
test('families: one passport completes six mechanics, retains proven outputs and carries research into a local show',async({page,browserName})=>{
    await prepare(page);await page.goto('/#/academy?tab=locker');await create(page);
    for(const family of FAMILY_IDS){await page.getByLabel('Destination world',{exact:true}).selectOption(family);if(family==='web-scout')await page.getByLabel('Controller selection',{exact:true}).selectOption('mock');if(family==='stream-studio')await page.getByLabel('Memory condition',{exact:true}).selectOption('PRIOR');await episode(page);const data=validateCareer(await saved(page)),last=data.runs.at(-1)!;expect(last.agentId).toBe('studio-agent');expect(last.receipt.schema).toBe('family-episode@1');expect(last.receipt.result.success).toBe(true);await page.getByRole('button',{name:'Retain verified family outputs',exact:true}).click();if(browserName==='chromium')await page.screenshot({path:`test-results/family-review/${family}.png`,fullPage:true});}
    const data=validateCareer(await saved(page));expect(data.runs).toHaveLength(6);expect(data.artifacts).toHaveLength(7);const show=data.runs.find(r=>r.worldId==='stream-studio')!;if(show.receipt.schema!=='family-episode@1')throw new Error('Missing local show proof.');expect(show.receipt.result.measures.sourceReferences).toBe(2);expect(data.agents[0].vehicleRef).not.toBeNull();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('brain-sweat-studio:v1')!).points)).toBe(0);await page.reload();await expect(page.getByRole('status').filter({hasText:'Execution status'})).toContainText('STOPPED');expect((await saved(page)).runs).toHaveLength(6);
});
test('families: human racing controls, strict configurations and fresh heldout generation preserve one authority',async({page})=>{
    await prepare(page);await page.goto('/#/academy?tab=locker');await create(page);await page.getByLabel('Destination world',{exact:true}).selectOption('auto-circuit');await page.getByLabel('Race format',{exact:true}).selectOption('head-to-head');await page.getByLabel('Controller selection',{exact:true}).selectOption('human');await page.getByRole('button',{name:'Prepare handoff',exact:true}).click();await page.getByRole('button',{name:'accelerate',exact:true}).click();const before=await saved(page);expect(before.runs.at(-1).receipt.result.ticks).toBe(1);expect(Object.keys(before.runs.at(-1).receipt.initialControllers)).toHaveLength(4);
    await page.getByText('Data-defined event configuration',{exact:true}).click();await page.getByLabel('Import event configuration',{exact:true}).setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...familyConfig('auto-circuit'),execute:'teleport'}))});await expect(page.getByRole('alert')).toContainText('Invalid');expect(await saved(page)).toEqual(before);
    await page.getByLabel('Controller selection',{exact:true}).selectOption('baseline');await page.getByLabel('Destination world',{exact:true}).selectOption('cache-quest');await page.getByLabel('Evaluation partition',{exact:true}).selectOption('HOLDOUT');await episode(page);const held=validateCareer(await saved(page)).runs.at(-1)!;expect(held.evaluation.notes).toEqual([]);expect(held.evaluation.artifacts).toEqual([]);if(held.receipt.schema!=='family-episode@1')throw new Error('Missing heldout proof.');expect(held.receipt.config.seed).toBe(2001);await expect(page.getByRole('button',{name:'Retain verified family outputs',exact:true})).toBeDisabled();
});
test('families: paused racing stays frozen and a stopped native receipt reloads after the origin disappears',async({page})=>{
    await prepare(page);const origin=await productionOrigin();try{await page.goto(`${origin.url}#/academy?tab=locker`);await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await page.reload();await create(page);await page.getByLabel('Destination world',{exact:true}).selectOption('auto-circuit');await page.getByLabel('Race format',{exact:true}).selectOption('endurance');await page.getByRole('button',{name:'Prepare handoff',exact:true}).click();await page.getByRole('button',{name:'Run episode',exact:true}).click();await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});await expect(page.getByRole('status').filter({hasText:'Execution status'})).toContainText('PAUSED');const before=await saved(page);await page.waitForTimeout(250);expect(await saved(page)).toEqual(before);await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'));});expect(await page.evaluate(()=>navigator.serviceWorker.controller!==null)).toBe(true);await origin.close();const response=await page.reload();expect(response?.status()).toBe(200);expect(response?.fromServiceWorker()).toBe(true);await expect(page.getByRole('status').filter({hasText:'Execution status'})).toContainText('STOPPED');validateCareer(await saved(page));}finally{await origin.close();}
});
test('families: Spanish family telemetry and controls fit 320/390 screens with keyboard access',async({page,browserName})=>{
    await prepare(page,'es');await page.goto('/#/academy?tab=locker');await page.getByRole('button',{name:'Crear pasaporte',exact:true}).click();await page.getByRole('button',{name:'Activar familias del circuito',exact:true}).focus();await page.keyboard.press('Enter');
    for(const family of FAMILY_IDS){await page.getByLabel('Mundo de destino',{exact:true}).selectOption(family);await page.getByRole('button',{name:'Preparar traspaso',exact:true}).click();await page.getByRole('button',{name:'Avanzar un paso',exact:true}).click();for(const width of [320,390]){await page.setViewportSize({width,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);}const scan=await new AxeBuilder({page}).include('.career').analyze();expect(scan.violations).toEqual([]);if(browserName==='chromium'&&family==='ensemble-lab')await page.screenshot({path:'test-results/family-review/spanish-phone.png',fullPage:true});}
});
