import { describe, expect, it } from 'vitest';
import { courses, lessonScore, validateClasses } from '../src/data/classes';
import { derivative, engineRun, evaluatePolynomial, integral, kitchenHeat, machineRun, machineStart, machinePrograms, machineTargets, machineTarget, workedMachineProgram, mixingPeak, projectile, robotGoal, robotStart, robotStep, stemTask, streamBudget, trailStart, trailTurn, waterStart, waterTurn } from '../src/games/advanced/models';
import { validateAdvanced } from '../src/games/advanced/validation';
import { validateSave, freshSave } from '../src/systems/progress';

describe('advanced scientific models',()=>{
 it('connects differentiation and integration, including negative signed area',()=>{const c=[3,2,4];for(const x of[0,1,2,4]){const h=0.0001;expect((evaluatePolynomial(c,x+h)-evaluatePolynomial(c,x-h))/(2*h)).toBeCloseTo(derivative(c,x),6);expect((integral(c,0,x+h)-integral(c,0,x-h))/(2*h)).toBeCloseTo(evaluatePolynomial(c,x),6);}expect(integral([0,1],-3,3)).toBe(0);expect(integral([0,0,1],3,0)).toBe(-9);});
 it('predicts symmetric projectile ranges and ballistic landing',()=>{const a=projectile(12,30),b=projectile(12,60);expect(a.range).toBeCloseTo(b.range,8);expect(a.vy*a.time-0.5*9.81*a.time**2).toBeCloseTo(0,8);expect(projectile(12,45).range).toBeGreaterThan(a.range);});
 it('trades speed for torque without creating power and models cooling separately',()=>{const c={type:'piston' as const,cylinders:4,throttle:70,gear:2,cooling:4,load:0};const a=engineRun(c),b=engineRun({...c,gear:4});expect(b.torque).toBeCloseTo(a.torque*2);expect(b.outputRPM).toBeCloseTo(a.outputRPM/2);expect(b.power).toBeCloseTo(a.power);expect(engineRun({...c,cooling:6}).heat).toBeLessThan(a.heat);expect(engineRun({...c,load:500}).stalled).toBe(true);});
 it('runs delivery programs for all maps, uses sensors, and respects the energy bound',()=>{const c={motor:2,battery:60,sensor:1,wheels:'grip' as const};for(let m=0;m<8;m++){const g=robotGoal(m),program=[...Array(6).fill('F'),'R',...Array(g.y).fill('F')];let s=robotStart(c.battery);for(let n=0;n<program.length;n++)s=robotStep(s,c,program,m);expect(s.delivered).toBe(true);expect(s.collisions).toBe(0);expect(s.energy).toBeGreaterThan(0);}const blocked={...robotStart(20),x:1,y:1};expect(robotStep(blocked,c,['S'],0).direction).toBe(1);expect(robotStep(blocked,{...c,sensor:0},['S'],0).collisions).toBe(1);expect(robotStep({...blocked,energy:0},c,['F'],0)).toEqual({...blocked,energy:0});});
 it('executes every VM brief with real memory/storage, finite loops, and target output',()=>{const c={ram:8,disk:8,clock:2};for(let m=0;m<8;m++){const s=machineRun(machineStart(c),machinePrograms[m],c);expect(s.error).toBe('');expect(s.halted).toBe(true);expect(s.output.at(-1)).toBe(machineTargets[m]);for(let d=1;d<=2;d++){const advanced=machineRun(machineStart(c),workedMachineProgram(m,d),c);expect(advanced.halted).toBe(true);expect(advanced.output.at(-1)).toBe(machineTarget(m,d));}}const s=machineRun(machineStart(c),'SET 9\nSTORE 2\nSET 3\nWRITE 2\nLOAD 2\nOUT\nREAD 2\nOUT\nHALT',c);expect(s.output).toEqual([9,3]);expect(s.ram[2]).toBe(9);expect(s.disk[2]).toBe(3);});
 it('rejects invalid VM instructions, addresses, overflow, and nonterminating loops',()=>{const c={ram:4,disk:4,clock:1};for(const p of['SET 1\nJNZ 1','SET 2\nSTORE 4','READ -1','SET 10000\nMUL 10000','alert(1)','SET 2.5','OUT 7','JNZ 90','SET 4']){const s=machineRun(machineStart(c),p,c);expect(s.error).not.toBe('');expect(s.cycles).toBeLessThanOrEqual(121);expect(Math.abs(s.accumulator)).toBeLessThanOrEqual(1000000);}});
 it('finds a resilient six-leg modern route in every difficulty and campaign',()=>{for(let d=0;d<3;d++)for(let m=0;m<8;m++){let s=trailStart(d);for(const choice of['transit','transit','community','transit','community','transit'] as const)s=trailTurn(s,choice,m);expect(s.step).toBe(6);expect(s.distance).toBeGreaterThanOrEqual(100+m%3*5+d*5);expect(Math.min(s.food,s.water,s.energy,s.cash,s.battery)).toBeGreaterThan(0);}});
 it('conserves modeled water and excludes untreated, exposed, or chemically contaminated supply',()=>{const c={filter:true,treatment:true,sealed:true,chemical:false,leak:10,inflow:20};const s=waterTurn(waterStart(),c,24);expect(s.stored+s.supplied+s.waste).toBeCloseTo(60);expect(s.safeDays).toBe(1);for(const unsafe of[{treatment:false},{sealed:false},{chemical:true}])expect(waterTurn(waterStart(),{...c,...unsafe},24).supplied).toBe(0);});
 it('approaches the heat setting, checks endpoints, and detects scorching',()=>{let s={temperature:20,minutes:0,stirred:0,burned:false};for(let i=0;i<16;i++)s=kitchenHeat(s,100,true);expect(s.temperature).toBeGreaterThan(74);expect(s.temperature).toBeLessThan(100);expect(s.burned).toBe(false);for(let i=0;i<20;i++)s=kitchenHeat(s,160,false);expect(s.burned).toBe(true);});
 it('accounts for video bits/bytes, frame timing, and additive audio peaks',()=>{expect(streamBudget(6,25,30).megabytes).toBe(18.75);expect(streamBudget(6,25,30).frameMs).toBeCloseTo(33.3333);expect(mixingPeak(-6,-6)).toBeCloseTo(0.0206,3);expect(mixingPeak(-10,-24)).toBeLessThan(-1);});
 it('authors 96 finite math, geometry, calculus, and physics briefs',()=>{for(const id of['math','geometry','calculus','physics'] as const)for(let m=0;m<8;m++)for(let d=0;d<3;d++){const t=stemTask(id,m,d);expect(Number.isFinite(t.answer)).toBe(true);expect(t.question.length).toBeGreaterThan(0);}expect(stemTask('calculus',6,2).answer).toBe(0);});
});
describe('classes and strict advanced saves',()=>{
 it('provides two bilingual classes per new world and explained answer checks',()=>{expect(courses).toHaveLength(22);for(const id of new Set(courses.map(c=>c.world)))expect(courses.filter(c=>c.world===id)).toHaveLength(2);for(const c of courses){expect(c.idea.en).not.toBe(c.idea.es);expect(c.questions).toHaveLength(3);expect(lessonScore(c,c.questions.map(q=>q.correct))).toBe(100);expect(lessonScore(c,[-1,-1,-1])).toBe(0);for(const q of c.questions)expect(q.why.es.length).toBeGreaterThan(0);}});
 it('migrates older v2 saves and preserves class progress without game XP',()=>{const save=freshSave();const old={...save,classes:undefined};expect(validateSave(old).classes).toEqual({});save.classes.equations={parameter:4,answers:[0,1,2],tested:true,best:100,attempts:1,date:new Date().toISOString()};expect(validateSave(JSON.parse(JSON.stringify(save)))).toEqual(save);expect(save.xp).toBe(0);});
 it('rejects invalid class answers, parameters, identifiers, and scores',()=>{const good={parameter:4,answers:[0,1,2],tested:true,best:100,attempts:1,date:''};for(const bad of[{...good,answers:[9,1,2]},{...good,parameter:11},{...good,best:99},{...good,answers:[]},{...good,extra:1}])expect(()=>validateClasses({equations:bad})).toThrow();expect(()=>validateClasses({unknown:good})).toThrow();});
 it('rejects VM memory mismatch, impossible robot delivery, unsafe keys, and oversized programs',()=>{const config={ram:4,disk:4,clock:1};const vm={config,parts:[],program:'HALT',machine:machineStart(config),boots:0};expect(validateAdvanced('vm',vm)).toBe(true);expect(validateAdvanced('vm',{...vm,machine:{...vm.machine,ram:[0]}})).toBe(false);expect(validateAdvanced('vm',{...vm,program:'x'.repeat(2001)})).toBe(false);expect(validateAdvanced('vm',{...vm,command:'execute'})).toBe(false);const robot={config:{motor:2,battery:50,sensor:1,wheels:'grip'},parts:[],program:[],robot:{...robotStart(50),delivered:true},tests:0};expect(validateAdvanced('robot',robot,0)).toBe(false);});
});
