import { describe, expect, it } from 'vitest';
import { badges, completedCount, dailyChallenges, freshSave, localDate, recordResult, validateSave } from '../src/systems/progress';
import { games } from '../src/data/games';
import { calculateBusinessDay } from '../src/games/SideHustle';
import { mealCoverage } from '../src/games/FoodFuel';
import { powerTurn } from '../src/games/PowerGrid';
import { robotStep } from '../src/games/CodeQuest';

describe('mission rewards and local saves', () => {
  it('has twelve playable manifests and thirty achievable badges', () => { expect(games).toHaveLength(12); expect(badges).toHaveLength(30); expect(new Set(games.map(g => g.id)).size).toBe(12); });
  it('only rewards a replay for an improved score', () => { const first = recordResult(freshSave(), 'money', 'explorer', 0, 75, '2026-10-02'); const same = recordResult(first.save, 'money', 'explorer', 0, 75, '2026-10-02'); const better = recordResult(same.save, 'money', 'explorer', 0, 90, '2026-10-02'); expect(same.xpGain).toBe(0); expect(better.xpGain).toBe(15); expect(better.save.xp).toBe(90); expect(completedCount(better.save)).toBe(1); expect(better.save.records['money/explorer/0'].attempts).toBe(3); expect(better.save.badges).toContain('money-mastery'); });
  it('awards each 3, 6 and 9 milestone once', () => { let save = freshSave(); let bonus = 0; for (let i = 0; i < 9; i++) { const reward = recordResult(save, games[i].id, 'explorer', 0, 100, '2026-10-02'); save = reward.save; bonus += reward.bonus; } expect(save.milestones).toEqual([3, 6, 9]); expect(bonus).toBe(360); expect(save.xp).toBe(1260); expect(recordResult(save, 'money', 'explorer', 0, 100, '2026-10-02').bonus).toBe(0); });
  it('exports/imports a save without losing awards or settings', () => { const first = recordResult(freshSave(), 'code', 'master', 3, 94, '2026-10-02').save; first.settings.highContrast = true; first.selectedDifficulty = true; expect(validateSave(JSON.parse(JSON.stringify(first)))).toEqual(first); });
  it('rejects invalid saves before replacement and derives rewards from records', () => { expect(() => validateSave({ version: 99 })).toThrow(); const first = recordResult(freshSave(), 'scam', 'explorer', 0, 80, '2026-10-02').save; expect(() => validateSave({ ...first, records: { bad: { score: 99999 } } })).toThrow(); expect(validateSave({ ...first, xp: 9999999, points: 9999999 }).xp).toBe(80); expect(() => validateSave({ ...first, settings: { ...first.settings, music: 'loud' } })).toThrow(); });
  it('keeps progress when a play streak ends', () => { const first = recordResult(freshSave(), 'money', 'builder', 0, 100, '2026-10-01').save; const next = recordResult(first, 'code', 'builder', 0, 100, '2026-10-02').save; expect(next.streak).toBe(2); const later = recordResult(next, 'scam', 'builder', 0, 100, '2026-10-06').save; expect(later.streak).toBe(1); expect(later.xp).toBeGreaterThan(next.xp); });
  it('rotates challenges deterministically by the supplied local date', () => { expect(dailyChallenges('2026-10-02')).toEqual(dailyChallenges('2026-10-02')); expect(dailyChallenges('2026-10-03')).not.toEqual(dailyChallenges('2026-10-02')); expect(new Set(dailyChallenges('2026-10-02').map(c => c.game)).size).toBe(3); const date = new Date(2026, 9, 2, 23, 30); expect(localDate(date)).toBe('2026-10-02'); });
});
describe('game consequences', () => {
  it('does not let business bookings exceed available work time', () => { const result = calculateBusinessDay(32, 6, 20, 32, 8, 2, 0, 100, 2); expect(result.jobs).toBe(3); expect(result.revenue).toBe(96); expect(result.profit).toBe(result.revenue - result.expenses - result.taxReserve); });
  it('counts grocery portions across every planned day', () => { const enough = mealCoverage({ grain: 1, beans: 1, veg: 1, fruit: 1 }, [0, 0, 0]); expect(enough.coverage).toBe(1); const short = mealCoverage({ grain: 1, beans: 0, veg: 1, fruit: 1 }, [0, 0, 0]); expect(short.coverage).toBeLessThan(1); });
  it('charges batteries only from excess and never below zero', () => { const sunny = powerTurn({ solar: 5, wind: 0, sun: 1, breeze: 0, demand: 6, stored: 0, capacity: 4, useBattery: true, gridEnabled: false, cash: 0, efficiency: false }); expect(sunny.stored).toBe(4); const night = powerTurn({ solar: 5, wind: 0, sun: 0, breeze: 0, demand: 6, stored: 4, capacity: 4, useBattery: true, gridEnabled: false, cash: 0, efficiency: false }); expect(night.delivered).toBe(4); expect(night.stored).toBe(0); });
  it('limits energy imports to cash and models efficiency', () => { const input = { solar: 0, wind: 0, sun: 0, breeze: 0, demand: 10, stored: 0, capacity: 0, useBattery: true, gridEnabled: true, cash: 5, efficiency: false }; expect(powerTurn(input).imported).toBe(2.5); expect(powerTurn({ ...input, efficiency: true }).demand).toBe(8); });
  it('keeps a robot inside the grid and stops at walls', () => { expect(robotStep(0, 0, 'up', 5, []).blocked).toBe(true); expect(robotStep(0, 0, 'right', 5, [1]).x).toBe(0); expect(robotStep(0, 0, 'right', 5, []).x).toBe(1); });
});
