import { memo, useEffect, useRef, useState } from 'react';
import { build3D, projectMesh, shadedColor, vertexData } from './world3d';
import { createRenderer } from './render3d';
import { useStudio } from '../systems/StudioContext';
export const Art3D=memo(function Art3D({kind,angle=0.65,zoom=10,data={}}:{kind:string;angle?:number;zoom?:number;data?:Record<string,number>}) {const meshes=build3D(kind,data).sort((a,b)=>{const depth=(m:typeof a)=>{let sum=0;for(let i=0;i<m.vertices.length;i+=6)sum+=m.vertices[i]*Math.sin(angle)+m.vertices[i+1]*0.62+m.vertices[i+2]*Math.cos(angle);return sum/(m.vertices.length/6);};return depth(a)-depth(b);});return <svg viewBox="0 0 720 400" aria-hidden="true"><defs><radialGradient id={`sky-${kind}`}><stop stopColor="#33475d"/><stop offset="1" stopColor="#111b2d"/></radialGradient></defs><rect width="720" height="400" fill={`url(#sky-${kind})`}/>{meshes.map((mesh,i)=><polygon key={i} points={projectMesh(mesh,angle,zoom)} fill={shadedColor(mesh)} stroke={shadedColor(mesh)} strokeWidth="0.3"/>)}</svg>;});
export default function Scene3D({kind,data={},paused=false,label}:{kind:string;data?:Record<string,number>;paused?:boolean;label:string}){
  const canvas=useRef<HTMLCanvasElement>(null); const dirty=useRef(true); const frameData=useRef(data); const [fallback,setFallback]=useState(false);const [angle,setAngle]=useState(0.65);const [zoom,setZoom]=useState(10);const {save}=useStudio();const reduced=save.settings.reducedMotion;
  useEffect(()=>{if(JSON.stringify(frameData.current)!==JSON.stringify(data)){frameData.current=data;dirty.current=true;}},[data]);
  useEffect(()=>{
    const element=canvas.current;if(!element)return;let gl:WebGL2RenderingContext|null=null;try{gl=element.getContext('webgl2',{alpha:false,antialias:true,powerPreference:'low-power'});}catch{ /* The vector model remains available. */ }if(!gl){queueMicrotask(()=>setFallback(true));return;}
    const renderer=createRenderer(gl);if(!renderer){queueMicrotask(()=>setFallback(true));return;}
    dirty.current=true;let request=0,last=0,time=0,disposed=false;const motion=window.matchMedia('(prefers-reduced-motion: reduce)');
    const draw=(now:number)=>{if(disposed)return;request=requestAnimationFrame(draw);if(now-last<33||document.hidden)return;const delta=Math.min(0.1,(now-last)/1000);last=now;const moving=!paused&&!reduced&&!motion.matches;if(moving)time+=delta;const ratio=Math.min(window.devicePixelRatio||1,1.5);const w=Math.max(1,Math.round(element.clientWidth*ratio)),h=Math.max(1,Math.round(element.clientHeight*ratio));if(!moving&&!dirty.current&&element.width===w&&element.height===h)return;dirty.current=false;if(element.width!==w||element.height!==h){element.width=w;element.height=h;}renderer.draw(vertexData(build3D(kind,frameData.current,time)),w,h,angle,zoom);};request=requestAnimationFrame(draw);
    const lost=(e:Event)=>{e.preventDefault();cancelAnimationFrame(request);setFallback(true);};element.addEventListener('webglcontextlost',lost);return()=>{disposed=true;cancelAnimationFrame(request);element.removeEventListener('webglcontextlost',lost);renderer.dispose();};
  },[kind,angle,zoom,paused,reduced]);
  return <div className="scene-3d"><div className="scene-3d-view" role="img" aria-label={label}>{fallback?<Art3D kind={kind} angle={angle} zoom={zoom} data={data}/>:<canvas ref={canvas} aria-hidden="true" data-renderer="webgl2"/>}<span className="scene-status">{fallback?'VECTOR VIEW':'REAL-TIME 3D'} · {paused?'PAUSED':'LAB SIMULATION'}</span></div><div className="camera-controls" aria-label="Scene camera"><button className="btn secondary" onClick={()=>setAngle(a=>a-0.25)}>Orbit left</button><button className="btn secondary" onClick={()=>setAngle(a=>a+0.25)}>Orbit right</button><button className="btn secondary" disabled={zoom<=8} onClick={()=>setZoom(z=>Math.max(8,z-1))}>Zoom in</button><button className="btn secondary" disabled={zoom>=17} onClick={()=>setZoom(z=>Math.min(17,z+1))}>Zoom out</button></div></div>;
}
