import { useEffect, useRef, useState } from 'react';
import { build3D, cameraMatrix, projectMesh, shadedColor, vertexData } from './world3d';
import { useStudio } from '../systems/StudioContext';
const vertex=`#version 300 es
in vec3 position; in vec3 normal; in vec3 color; uniform mat4 camera; out vec3 world; out vec3 n; out vec3 c; void main(){ world=position; n=normal; c=color; gl_Position=camera*vec4(position,1.0); }`;
const fragment=`#version 300 es
precision highp float; in vec3 world; in vec3 n; in vec3 c; uniform vec3 eye; out vec4 outColor; void main(){vec3 normal=normalize(n);vec3 light=normalize(vec3(-3.0,7.0,5.0));vec3 view=normalize(eye-world);float diffuse=max(dot(normal,light),0.0);float spec=pow(max(dot(normal,normalize(light+view)),0.0),36.0);float rim=pow(1.0-max(dot(view,normal),0.0),3.0);vec3 shaded=c*(0.35+diffuse*0.65)+vec3(0.14,0.2,0.3)*rim+vec3(0.18)*spec;float fog=clamp(length(eye-world)/40.0,0.0,0.3);outColor=vec4(mix(shaded,vec3(0.07,0.1,0.16),fog),1.0);}`;
export function Art3D({kind}:{kind:string}) {const meshes=build3D(kind).sort((a,b)=>{const depth=(m:typeof a)=>{let sum=0;for(let i=0;i<m.vertices.length;i+=6)sum+=m.vertices[i]*0.605+m.vertices[i+1]*0.62+m.vertices[i+2]*0.796;return sum/(m.vertices.length/6);};return depth(a)-depth(b);});return <svg viewBox="0 0 720 400" aria-hidden="true"><defs><radialGradient id={`sky-${kind}`}><stop stopColor="#33475d"/><stop offset="1" stopColor="#111b2d"/></radialGradient></defs><rect width="720" height="400" fill={`url(#sky-${kind})`}/>{meshes.map((mesh,i)=><polygon key={i} points={projectMesh(mesh)} fill={shadedColor(mesh)} stroke={shadedColor(mesh)} strokeWidth="0.3"/>)}</svg>;}
export default function Scene3D({kind,data={},paused=false,label}:{kind:string;data?:Record<string,number>;paused?:boolean;label:string}){
  const canvas=useRef<HTMLCanvasElement>(null); const dirty=useRef(true); const frameData=useRef(data); const [fallback,setFallback]=useState(false);const [angle,setAngle]=useState(0.65);const [zoom,setZoom]=useState(12);const {save}=useStudio();const reduced=save.settings.reducedMotion;
  useEffect(()=>{if(JSON.stringify(frameData.current)!==JSON.stringify(data)){frameData.current=data;dirty.current=true;}},[data]);
  useEffect(()=>{
    const element=canvas.current;if(!element)return;let gl:WebGL2RenderingContext|null=null;try{gl=element.getContext('webgl2',{alpha:false,antialias:true,powerPreference:'low-power'});}catch{ /* The vector model remains available. */ }if(!gl){queueMicrotask(()=>setFallback(true));return;}
    const compile=(type:number,source:string)=>{const shader=gl.createShader(type)!;gl.shaderSource(shader,source);gl.compileShader(shader);if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS)){gl.deleteShader(shader);return null;}return shader;};const vs=compile(gl.VERTEX_SHADER,vertex),fs=compile(gl.FRAGMENT_SHADER,fragment);if(!vs||!fs){if(vs)gl.deleteShader(vs);if(fs)gl.deleteShader(fs);queueMicrotask(()=>setFallback(true));return;}
    const program=gl.createProgram()!;gl.attachShader(program,vs);gl.attachShader(program,fs);gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS)){gl.deleteShader(vs);gl.deleteShader(fs);gl.deleteProgram(program);queueMicrotask(()=>setFallback(true));return;}const buffer=gl.createBuffer()!;gl.useProgram(program);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);for(const [name,size,offset]of[['position',3,0],['normal',3,12],['color',3,24]] as const){const attr=gl.getAttribLocation(program,name);gl.enableVertexAttribArray(attr);gl.vertexAttribPointer(attr,size,gl.FLOAT,false,36,offset);}const camera=gl.getUniformLocation(program,'camera'),eye=gl.getUniformLocation(program,'eye');gl.enable(gl.DEPTH_TEST);gl.clearColor(0.055,0.08,0.13,1);
    dirty.current=true;let request=0,last=0,time=0,disposed=false;const motion=window.matchMedia('(prefers-reduced-motion: reduce)');
    const draw=(now:number)=>{if(disposed)return;request=requestAnimationFrame(draw);if(now-last<33||document.hidden)return;const delta=Math.min(0.1,(now-last)/1000);last=now;const moving=!paused&&!reduced&&!motion.matches;if(moving)time+=delta;const ratio=Math.min(window.devicePixelRatio||1,1.5);const w=Math.max(1,Math.round(element.clientWidth*ratio)),h=Math.max(1,Math.round(element.clientHeight*ratio));if(!moving&&!dirty.current&&element.width===w&&element.height===h)return;dirty.current=false;if(element.width!==w||element.height!==h){element.width=w;element.height=h;}gl.viewport(0,0,w,h);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const vertices=vertexData(build3D(kind,frameData.current,time));gl.bufferData(gl.ARRAY_BUFFER,vertices,gl.DYNAMIC_DRAW);const view=cameraMatrix(angle,zoom,w/h);gl.uniformMatrix4fv(camera,false,view.matrix);gl.uniform3fv(eye,new Float32Array(view.eye));gl.drawArrays(gl.TRIANGLES,0,vertices.length/9);};request=requestAnimationFrame(draw);
    const lost=(e:Event)=>{e.preventDefault();cancelAnimationFrame(request);setFallback(true);};element.addEventListener('webglcontextlost',lost);return()=>{disposed=true;cancelAnimationFrame(request);element.removeEventListener('webglcontextlost',lost);gl.deleteBuffer(buffer);gl.deleteProgram(program);gl.deleteShader(vs);gl.deleteShader(fs);};
  },[kind,angle,zoom,paused,reduced]);
  return <div className="scene-3d"><div className="scene-3d-view" role="img" aria-label={label}>{fallback?<Art3D kind={kind}/>:<canvas ref={canvas} aria-hidden="true" data-renderer="webgl2"/>}<span className="scene-status">{fallback?'VECTOR VIEW':'REAL-TIME 3D'} · {paused?'PAUSED':'LAB SIMULATION'}</span></div><div className="camera-controls" aria-label="Scene camera"><button className="btn secondary" onClick={()=>setAngle(a=>a-0.25)}>Orbit left</button><button className="btn secondary" onClick={()=>setAngle(a=>a+0.25)}>Orbit right</button><button className="btn secondary" disabled={zoom<=8} onClick={()=>setZoom(z=>Math.max(8,z-1))}>Zoom in</button><button className="btn secondary" disabled={zoom>=17} onClick={()=>setZoom(z=>Math.min(17,z+1))}>Zoom out</button></div></div>;
}
