import { clone, hash } from '../runtime/data.ts';
import type { FamilyConfig, FamilyMachine, PerformanceEvent, ScoreSpec } from './types.ts';
export function beatTime(score:ScoreSpec,beat:number):number {let time=0;for(let i=0;i<score.tempo.length;i++){const t=score.tempo[i],end=Math.min(beat,score.tempo[i+1]?.beat??beat);if(end>t.beat)time+=(end-t.beat)*60000/t.bpm;}return Math.round(time);}
export function ensembleMachine(config:FamilyConfig):FamilyMachine {
    const score=config.score!,roles=['conductor',...score.parts.map(p=>p.id)],end=score.bars*score.meter;let tick=0,beat=0,started=false,complete=false,correct=0,missed=0,cueErrors=0;const events:PerformanceEvent[]=[],active=new Set<string>();
    return {roles,observe(role){const part=score.parts.find(p=>p.id===role),target=part?.notes.find(n=>n.beat===beat)??null;return {role,title:score.title,beat,end,timeMs:beatTime(score,beat),tempo:score.tempo.filter(t=>t.beat<=beat).at(-1)?.bpm,started,active:active.has(role),part:part?clone(part):null,target:target?clone(target):null,cues:score.cues.filter(c=>c.beat===beat),chord:score.chords.filter(c=>c.beat<=beat).at(-1)??null,dynamics:beat<16?76:64};},legal(role){return role==='conductor'?['wait','entry','conduct','dynamics','cutoff']:['rest','play-target','play-low','play-high'];},advance(intents){tick++;const output:string[]=[];
        if(!started){if(intents.conductor==='entry'){started=true;score.parts.forEach(p=>active.add(p.id));events.push({beat:0,timeMs:0,role:'conductor',kind:'entry',pitch:0,duration:0,velocity:76,syllable:''});output.push('Conductor entry; beat zero opens on the next turn.');}return output;}
        if(beat>=end){if(intents.conductor==='cutoff'){complete=true;active.clear();events.push({beat,timeMs:beatTime(score,beat),role:'conductor',kind:'cutoff',pitch:0,duration:0,velocity:0,syllable:''});output.push('Conductor cutoff.');}else cueErrors++;return output;}
        const dynamic=score.cues.some(c=>c.beat===beat&&c.type==='dynamics');if(dynamic){if(intents.conductor!=='dynamics')cueErrors++;events.push({beat,timeMs:beatTime(score,beat),role:'conductor',kind:'dynamics',pitch:0,duration:0,velocity:64,syllable:''});}
        for(const part of score.parts){const n=part.notes.find(n=>n.beat===beat),a=intents[part.id];if(n&&active.has(part.id)){const pitch=n.pitch+(a==='play-low'?-2:a==='play-high'?2:0);if(a==='play-target'){correct++;}else missed++;if(a!=='rest')events.push({beat,timeMs:beatTime(score,beat),role:part.id,kind:'note',pitch,duration:n.duration,velocity:n.velocity,syllable:n.syllable});}else if(a!=='rest'){missed++;events.push({beat,timeMs:beatTime(score,beat),role:part.id,kind:'note',pitch:60,duration:1,velocity:40,syllable:''});}else events.push({beat,timeMs:beatTime(score,beat),role:part.id,kind:'rest',pitch:0,duration:1,velocity:0,syllable:''});}
        beat++;return output;
    },result(){const total=score.parts.reduce((s,p)=>s+p.notes.length,0);return {terminal:complete,success:complete&&missed===0&&cueErrors===0,measures:{pitchAccuracy:total?correct/total:0,noteCompletion:correct,timingErrors:missed,cueErrors,synchrony:Number(complete&&cueErrors===0),parts:score.parts.length},public:{score:clone(score),events:clone(events),beat,review:'Mechanical score checks. Artistic quality requires a separate human review.'}};},stateHash(){return hash({tick,beat,started,complete,correct,missed,cueErrors,events,active:[...active].sort()});},outputs(actor){if(!complete)return [];return [{actor,type:'music-score',content:clone(score),contentHash:hash(score)}];}};
}
