import type { AgentManifest } from './contracts';

const freezeList = <T extends string>(values: readonly T[]): readonly T[] => Object.freeze([...values]);

const manifest = (value: Omit<AgentManifest, 'schema' | 'authority'>): AgentManifest => Object.freeze({
  schema: 'fork-thirty-agent@1',
  ...value,
  capabilities: freezeList(value.capabilities),
  preferredWorlds: freezeList(value.preferredWorlds),
  bridgeAffinities: freezeList(value.bridgeAffinities),
  authority: Object.freeze([]),
});

export const cast: readonly AgentManifest[] = Object.freeze([
  manifest({
    id: 'al',
    displayName: 'Al',
    role: 'operator-bridge',
    summary: 'Grounded helper that translates between operator intent, evidence and bounded system actions.',
    capabilities: ['grounding', 'operator-handoff', 'evidence-review'],
    defaultMemoryScope: 'career',
    preferredWorlds: ['town-zero', 'web-scout'],
    bridgeAffinities: ['phios', 'commonline'],
    riskProfile: 'guarded',
  }),
  manifest({
    id: 'sal',
    displayName: 'SAL',
    role: 'strategic-planner',
    summary: 'High-agency planner for bounded search, scenario branching and ambitious proposals.',
    capabilities: ['planning', 'bounded-search', 'scenario-branching'],
    defaultMemoryScope: 'world',
    preferredWorlds: ['town-zero', 'web-scout', 'scenario'],
    bridgeAffinities: ['infinite-porch', 'phios'],
    riskProfile: 'elevated',
  }),
  manifest({
    id: 'oilleak',
    displayName: 'OilLeak',
    role: 'deterministic-mechanic',
    summary: 'Legacy-minded mechanic that favors inspectable rules, diagnostics and practical reality checks.',
    capabilities: ['diagnostics', 'rule-policy', 'reality-check'],
    defaultMemoryScope: 'world',
    preferredWorlds: ['auto-circuit', 'engine', 'town-zero'],
    bridgeAffinities: ['phios'],
    riskProfile: 'low',
  }),
  manifest({
    id: 'coreglow',
    displayName: 'CoreGlow',
    role: 'compute-coordinator',
    summary: 'Compute specialist for workload estimation, routing proposals and bounded execution planning.',
    capabilities: ['compute-routing', 'workload-estimation', 'resource-planning'],
    defaultMemoryScope: 'episode',
    preferredWorlds: ['world-lab', 'town-zero'],
    bridgeAffinities: ['phios'],
    riskProfile: 'guarded',
  }),
  manifest({
    id: 'cache',
    displayName: 'Cache',
    role: 'memory-custodian',
    summary: 'Memory specialist for retrieval, provenance indexing and bounded continuity.',
    capabilities: ['memory-retrieval', 'provenance-indexing', 'context-curation'],
    defaultMemoryScope: 'career',
    preferredWorlds: ['cache-quest', 'town-zero'],
    bridgeAffinities: ['phios'],
    riskProfile: 'guarded',
  }),
  manifest({
    id: 'patch',
    displayName: 'Patch',
    role: 'recovery-engineer',
    summary: 'Debug and recovery specialist that inspects failures, replays evidence and proposes repairs.',
    capabilities: ['debugging', 'repair-planning', 'replay-inspection'],
    defaultMemoryScope: 'world',
    preferredWorlds: ['town-zero', 'auto-circuit'],
    bridgeAffinities: ['phios'],
    riskProfile: 'low',
  }),
  manifest({
    id: 'flux',
    displayName: 'Flux',
    role: 'adaptation-analyst',
    summary: 'Adaptive-policy specialist for transfer, policy tuning and changing world conditions.',
    capabilities: ['adaptation', 'transfer-analysis', 'policy-tuning'],
    defaultMemoryScope: 'world',
    preferredWorlds: ['town-zero', 'cache-quest', 'auto-circuit'],
    bridgeAffinities: ['phios'],
    riskProfile: 'guarded',
  }),
  manifest({
    id: 'ping',
    displayName: 'Ping',
    role: 'communications-relay',
    summary: 'Structured communications specialist for presence, routing and bounded message exchange.',
    capabilities: ['structured-comms', 'message-routing', 'presence'],
    defaultMemoryScope: 'episode',
    preferredWorlds: ['town-zero', 'stream-studio'],
    bridgeAffinities: ['commonline', 'infinite-porch'],
    riskProfile: 'guarded',
  }),
  manifest({
    id: 'spark',
    displayName: 'Spark',
    role: 'creative-synthesist',
    summary: 'Creative specialist for original concepts, composition proposals and visual ideation.',
    capabilities: ['ideation', 'composition', 'visual-concepts'],
    defaultMemoryScope: 'world',
    preferredWorlds: ['ensemble-lab', 'stream-studio', 'stunt-show'],
    bridgeAffinities: ['domistika', 'auralith'],
    riskProfile: 'guarded',
  }),
  manifest({
    id: 'brian-sweat',
    displayName: 'Brian Sweat',
    role: 'mission-coordinator',
    summary: 'Mission coordinator for task framing, team alignment and relentlessly practical encouragement.',
    capabilities: ['mission-planning', 'team-coordination', 'progress-framing'],
    defaultMemoryScope: 'career',
    preferredWorlds: ['town-zero', 'auto-circuit', 'stream-studio'],
    bridgeAffinities: ['commonline', 'phios'],
    riskProfile: 'low',
  }),
]);
