import { lazy, Suspense, useEffect, useMemo, useRef, useState } from 'react';
import Icon from '../components/Icon';
import RuntimeLab from './RuntimeLab';
import AgentGarage from './AgentGarage';
import Modal from '../components/Modal';
import Scene3D from '../engine/Scene3D';
import { Select, Slider } from '../games/advanced/ui';
import { AGENT_IDS, arenaObjective, arenaStart, arenaStep, isArena, runEpisode, workedPolicy, type ArenaKind } from '../games/rung4/models';
import { parsePolicy } from '../games/rung4/validation';
import { Notice, Stat, Stats } from '../games/shared';
import { useStudio } from '../systems/StudioContext';
import { saveAcademy } from '../systems/profiles';
import { playAgentCue } from '../systems/sound';
import { arenaTitles, assess, evaluateRover, failureAdvice, freshAcademy, greedyAction, roverFresh, roverStart, roverTarget, roverWalls, searchGeneration, splitSeeds, trainRover, validateAcademy, type AcademySave, type Assessment, type ControllerRecord, type RoverRecord, type RoverEpisode } from '../training/models';

const WorldLab = lazy(() => import('./WorldLab'));
const initialController = (): ControllerRecord => ({ draft: [{ when: 'always', action: 'approach' }], champion: [{ when: 'always', action: 'approach' }], stage: 1, seed: 3, history: [] });
const round = (n: number) => Number(n.toFixed(1));
function download(name: string, value: unknown) {
  const url = URL.createObjectURL(new Blob([JSON.stringify(value, null, 2)], { type: 'application/json' }));
  const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
}
function traceData(trace: { x: number; y: number }[], frame: number) {
  const rows = trace.slice(0, frame < 0 ? trace.length : frame + 1).slice(-12), data: Record<string, number> = { trailCount: rows.length };
  rows.forEach((row, i) => { data[`tx${i}`] = row.x; data[`ty${i}`] = row.y; }); return data;
}
function usePlayback(length: number, paused: boolean) {
  const [frame, setFrame] = useState(-1), [playing, setPlaying] = useState(false);
  const active = playing && frame < length - 1;
  useEffect(() => {
    if (!active || paused) return;
    const timer = setInterval(() => { if (!document.hidden) setFrame(n => Math.min(length - 1, n + 1)); }, 140);
    return () => clearInterval(timer);
  }, [active, length, paused]);
  return { frame, setFrame, active, toggle: () => { if (active) setPlaying(false); else { setFrame(0); setPlaying(true); } }, stop: () => { setFrame(-1); setPlaying(false); } };
}
function Curve({ points, label }: { points: number[]; label: string }) {
  const path = points.map((v, i) => `${45 + i / Math.max(1, points.length - 1) * 430},${130 - Math.max(0, Math.min(100, v)) * 1.05}`).join(' ');
  return <svg className="training-curve" viewBox="0 0 500 160" role="img" aria-label={label}><path d="M45 25H480M45 77H480M45 130H480" fill="none" stroke="#49617b" strokeWidth="1" /><path d="M45 20V130H480" fill="none" stroke="#92acc3" strokeWidth="1" />{points.length > 0 && <polyline points={path} fill="none" stroke="#caff66" strokeWidth="3" />}<text x="4" y="29" fill="#c3d4e7" fontSize="12">100%</text><text x="12" y="134" fill="#c3d4e7" fontSize="12">0%</text><text x="45" y="151" fill="#c3d4e7" fontSize="12">1</text><text x="465" y="151" fill="#c3d4e7" fontSize="12">{points.length}</text></svg>;
}

export default function Academy({ arena, rover = false, lab = false, garage = false, worlds = false }: { arena?: string; rover?: boolean; lab?: boolean; garage?: boolean; worlds?: boolean }) {
  const { save, profile } = useStudio(), [academy, setAcademy] = useState<AcademySave>(() => save.academy || freshAcademy());
  const [tab, setTab] = useState(worlds ? 'worlds' : garage ? 'garage' : lab ? 'runtime' : rover ? 'rover' : 'controllers'), [kind, setKind] = useState<ArenaKind>(arena && isArena(arena) ? arena : 'sports');
  const [paused, setPaused] = useState(false), [visible, setVisible] = useState(!document.hidden), [sound, setSound] = useState(false), [notice, setNotice] = useState(''), [revision, setRevision] = useState(0), alive = useRef(true);
  useEffect(() => { saveAcademy(academy, profile.id); }, [academy, profile.id]);
  useEffect(() => { alive.current = true; return () => { alive.current = false; }; }, []);
  useEffect(() => { const visibility = () => setVisible(!document.hidden); document.addEventListener('visibilitychange', visibility); return () => document.removeEventListener('visibilitychange', visibility); }, []);
  const importFile = async (file?: File) => {
    if (!file) return;
    try {
      if (file.size > 3000000) throw new Error('Choose an academy file smaller than 3 MB.');
      const raw = JSON.parse(await file.text());
      if (!raw || raw.version !== 1 || Object.keys(raw).sort().join(',') !== 'academy,version') throw new Error('Choose a version 1 academy export.');
      const next = validateAcademy(raw.academy); if (!alive.current) return;
      saveAcademy(next, profile.id); setAcademy(next); setRevision(n => n + 1); setNotice('Academy imported. Training and replays resume stopped.');
    } catch (error) { if (alive.current) setNotice(error instanceof Error ? error.message : 'The academy file could not be read.'); }
  };
  return <div className="academy"><header className="academy-heading"><div><span className="eyebrow">TRAIN · EVALUATE · UNDERSTAND</span><h1>Agent academy</h1><p>Find a controller that works, then test it on separate trials.</p></div><div className="button-row"><button className="btn secondary" onClick={() => setPaused(p => !p)}>{paused ? 'Resume academy' : 'Pause academy'}</button><label className="academy-sound"><input type="checkbox" checked={sound} onChange={e => { setSound(e.target.checked); if (e.target.checked) playAgentCue('complete', 0); }} />Simulation sound</label></div></header>
    <div className="academy-tabs" role="tablist" aria-label="Training tools">{[['controllers', 'Controller lab'], ['rover', 'Learning rover'], ['worlds', 'World authoring lab'], ['runtime', 'Experiment lab'], ['garage', 'Agent garage']].map(([id, name]) => <button className={`btn ${tab === id ? 'primary' : 'secondary'}`} id={`academy-tab-${id}`} role="tab" tabIndex={tab === id ? 0 : -1} aria-selected={tab === id} aria-controls={`academy-panel-${id}`} key={id} onClick={() => setTab(id)} onKeyDown={e => { if (!['ArrowLeft', 'ArrowRight', 'Home', 'End'].includes(e.key)) return; e.preventDefault(); const tools = ['controllers', 'rover', 'worlds', 'runtime', 'garage'], index = tools.indexOf(tab), next = tools[e.key === 'Home' ? 0 : e.key === 'End' ? 4 : (index + (e.key === 'ArrowRight' ? 1 : 4)) % 5]; setTab(next); document.getElementById(`academy-tab-${next}`)?.focus(); }}>{name}</button>)}</div>
    {['controllers', 'rover', 'worlds', 'runtime', 'garage'].map(id => <section role="tabpanel" id={`academy-panel-${id}`} aria-labelledby={`academy-tab-${id}`} hidden={tab !== id} key={id}>
      {tab === id ? id === 'worlds' ? <Suspense fallback={<p>Opening world authoring lab…</p>}><WorldLab key={revision} saved={academy.worlds} paused={paused || !visible} onChange={worlds => setAcademy(a => ({ ...a, worlds }))} /></Suspense> : id === 'garage' ? <AgentGarage key={revision} academy={academy} paused={paused || !visible} sound={sound} onChange={garage => setAcademy(a => ({ ...a, garage }))} /> : id === 'runtime' ? <RuntimeLab key={revision} academy={academy} paused={paused || !visible} onChange={lab => setAcademy(a => ({ ...a, lab }))} /> : id === 'controllers' ? <><div className="academy-picker"><Select label="Training arena" value={kind} options={AGENT_IDS.map(value => ({ value, label: arenaTitles[value] }))} onChange={v => setKind(v as ArenaKind)} /><a className="text-link" href={`#/classes?world=${kind}`}>Study the agent classes</a></div><ControllerLab key={`${kind}-${revision}`} kind={kind} record={academy.controllers[kind] || initialController()} paused={paused || !visible} sound={sound} onChange={record => setAcademy(a => ({ ...a, controllers: { ...a.controllers, [kind]: record } }))} /></> : <LearningRover key={revision} record={academy.rover} paused={paused || !visible} sound={sound} onChange={record => setAcademy(a => ({ ...a, rover: record }))} /> : null}
    </section>)}
    <footer className="academy-save"><div><strong>Saved with this local profile.</strong><p>Policies, learned values, and training history travel with your progress backup. Academy runs award no game XP.</p></div><div className="button-row"><button className="btn secondary" onClick={() => download('brain-sweat-academy.json', { version: 1, academy })}><Icon name="download" />Export academy</button><label className="btn secondary import-button">Import academy<input type="file" aria-label="Import academy" accept=".json,application/json" onChange={e => { void importFile(e.target.files?.[0]); e.target.value = ''; }} /></label></div></footer>{notice && <Notice>{notice}</Notice>}
  </div>;
}

function ControllerLab({ kind, record, paused, sound, onChange }: { kind: ArenaKind; record: ControllerRecord; paused: boolean; sound: boolean; onChange: (r: ControllerRecord) => void }) {
  const [text, setText] = useState(JSON.stringify({ version: 1, kind, rules: record.draft }, null, 2));
  const [remaining, setRemaining] = useState(0), [assessment, setAssessment] = useState<Assessment | null>(null), [selected, setSelected] = useState(0), [notice, setNotice] = useState('');
  const training = remaining > 0, baseline = useMemo(() => assess(kind, record.draft, record.stage, splitSeeds(record.seed)), [kind, record.draft, record.stage, record.seed]);
  const championTraining = useMemo(() => assess(kind, record.champion, record.stage, splitSeeds(record.seed)), [kind, record.champion, record.stage, record.seed]);
  const last = record.history[record.history.length - 1], current = assessment?.trials[selected];
  const episode = useMemo(() => current ? runEpisode(arenaStart(kind, current.seed, record.stage), record.champion) : arenaStart(kind, record.seed, record.stage), [kind, current, record.stage, record.champion, record.seed]);
  const playback = usePlayback(episode.trace.length, paused), row = episode.trace[playback.frame < 0 ? episode.trace.length - 1 : playback.frame];
  const view = useMemo(() => playback.frame < 0 ? episode : episode.trace.slice(0, playback.frame + 1).reduce((state, step) => arenaStep(state, step.action), arenaStart(kind, episode.seed, episode.difficulty)), [playback.frame, episode, kind]), target = arenaObjective(view);
  useEffect(() => {
    if (!training || paused) return;
    const timer = setTimeout(() => {
      const result = searchGeneration(kind, record.champion, record.stage, record.seed);
      onChange({ ...record, champion: result.champion, history: [...record.history, { generation: (last?.generation || 0) + 1, successes: result.report.successes, score: result.report.score, ticks: result.report.ticks }].slice(-80) });
      setRemaining(n => n - 1);
    }, 80);
    return () => clearTimeout(timer);
  }, [training, paused, kind, record, last, onChange]);
  useEffect(() => { if (sound && playback.active && !paused && row) playAgentCue(row.reason.includes('Blocked move') ? 'blocked' : row.action === 'interact' ? 'interact' : kind === 'space' ? 'thruster' : 'move', kind === 'space' ? row.x / 50 : row.x / 4 - 1); }, [sound, playback.active, paused, row, kind]);
  const change = (next: ControllerRecord) => { setRemaining(0); setAssessment(null); playback.stop(); onChange(next); };
  const applyDraft = () => { try { const rules = parsePolicy(JSON.parse(text), kind); change({ ...record, draft: rules, champion: rules, history: [] }); setNotice('Draft applied. Compare it before training.'); } catch (error) { setNotice(error instanceof Error ? error.message : 'Check the controller JSON.'); } };
  return <div className="academy-layout"><div className="academy-stage"><Scene3D kind={kind} paused={paused} label={`${arenaTitles[kind]} training scene; position ${view.x}, ${view.y}.`} data={{ x: view.x, y: view.y, seed: episode.seed, goalX: target[0], goalY: target[1], progress: view.progress, vx: view.vx, vy: view.vy, ...traceData(episode.trace, playback.frame) }} />
      <div className="telemetry-strip"><span>FLIGHT RECORDER</span><strong>{current ? current.status : 'ready'}</strong><span>({view.x}, {view.y})</span></div>
      {episode.trace.length > 0 && <div className="academy-panel"><h2>Replay the trial</h2><Slider label="Controller replay tick" value={playback.frame < 0 ? episode.trace.length - 1 : playback.frame} min={0} max={episode.trace.length - 1} onChange={n => { playback.stop(); playback.setFrame(n); }} /><button className="btn secondary" disabled={paused} onClick={playback.toggle}>{playback.active ? 'Stop replay' : 'Play replay'}</button><p>{row?.reason}</p><Stats><Stat label="Energy reserve" value={round(view.energy)} /><Stat label="Water reserve" value={round(view.water)} /></Stats></div>}
      <div className="academy-panel"><h2>Success across training trials</h2><Curve points={record.history.map(p => p.successes / 8 * 100)} label={`Training successes by generation: ${record.history.map(p => p.successes).join(', ')} out of 8.`} /><p>Eight training seeds per generation. Prefer completion first, then model score, then fewer ticks.</p></div>
    </div><div className="academy-work"><fieldset disabled={paused || training} className="academy-panel"><legend>Build a repeatable experiment</legend><Select label="Curriculum stage" value={String(record.stage)} options={[{ value: '0', label: 'Foundation · Explorer' }, { value: '1', label: 'Constraints · Builder' }, { value: '2', label: 'Endurance · Master' }]} onChange={value => change({ ...record, stage: Number(value), history: [] })} /><Slider label="Experiment seed" min={0} max={99} value={record.seed} onChange={seed => change({ ...record, seed, history: [] })} />
      <label className="code-editor">Draft controller<textarea aria-label="Academy controller JSON" rows={6} maxLength={12000} value={text} spellCheck={false} onChange={e => setText(e.target.value)} /></label><div className="button-row"><button className="btn secondary" onClick={applyDraft}>Apply draft</button><button className="btn secondary" onClick={() => { const rules = workedPolicy(kind); setText(JSON.stringify({ version: 1, kind, rules }, null, 2)); change({ ...record, draft: rules, champion: rules, history: [] }); }}>Load teaching example</button></div>
      <Stats><Stat label="Draft training success" value={`${baseline.successes}/8`} /><Stat label="Champion training success" value={`${championTraining.successes}/8`} /><Stat label="Mean training ticks" value={round(championTraining.ticks)} /><Stat label="Search generations" value={record.history.length} /></Stats>
      <div className="button-row"><button className="btn primary" onClick={() => { setAssessment(null); playback.stop(); onChange({ ...record, champion: record.draft.map(r => ({ ...r })), history: [] }); setRemaining(6); }}>Train controller</button><button className="btn secondary" onClick={() => { setAssessment(assess(kind, record.champion, record.stage, splitSeeds(record.seed, true))); setSelected(0); playback.stop(); if (sound) playAgentCue('complete', 0); }}>Evaluate champion</button></div></fieldset>
      {training && <div className="academy-panel" role="status"><p>{paused ? 'Training paused.' : 'Testing candidate rules on the training seeds.'}</p><progress max={6} value={6 - remaining} aria-label="Controller training progress" /><button className="btn secondary" onClick={() => setRemaining(0)}>Stop controller training</button></div>}
      <section className="academy-panel"><h2>The current champion</h2><ol className="champion-rules">{record.champion.map((rule, i) => <li key={i}><span>{rule.when}</span><strong>{rule.action}</strong></li>)}</ol><div className="button-row"><button className="btn secondary" onClick={() => download(`brain-sweat-${kind}-policy.json`, { version: 1, kind, rules: record.champion })}>Export champion</button><a className="btn secondary" href={`#/game/${kind}`}>Open arena</a></div><p>The arena can load this academy champion. The exported version 1 policy also works in agent competitions.</p></section>
      {assessment && <section className="academy-panel evaluation-report"><span className="eyebrow">FROZEN CONTROLLER · SEPARATE SEEDS</span><h2>Evaluation report</h2><Stats><Stat label="Evaluation success" value={`${assessment.successes}/8`} /><Stat label="Worst model score" value={`${assessment.worst}/100`} /><Stat label="Mean evaluation ticks" value={round(assessment.ticks)} /><Stat label="Mean model score" value={`${round(assessment.score)}/100`} /></Stats><Select label="Inspect evaluation trial" value={String(selected)} options={assessment.trials.map((t, i) => ({ value: String(i), label: `${t.seed} · ${t.status} · ${t.ticks} ticks` }))} onChange={v => { playback.stop(); setSelected(Number(v)); }} /><Notice tone={current?.status === 'complete' ? 'success' : 'warning'}>{failureAdvice(kind, current)}</Notice><p>Evaluation seeds are never used to select candidate rules. Changing your controller or settings clears this report.</p></section>}
      {notice && <Notice>{notice}</Notice>}<details className="academy-panel"><summary>What is training here?</summary><p>This lab searches a bounded set of condition/action rules using repeated training outcomes. It is local controller optimization, with no cloud model or arbitrary code. Approach includes a built-in path planner.</p><p>Use the learning rover to see a different method: action values updated from rewards. Success in these models does not establish real-world agent capability.</p></details>
    </div></div>;
}

function LearningRover({ record, paused, sound, onChange }: { record: RoverRecord; paused: boolean; sound: boolean; onChange: (r: RoverRecord) => void }) {
  const [remaining, setRemaining] = useState(0), [report, setReport] = useState<ReturnType<typeof evaluateRover> | null>(null), [baseline, setBaseline] = useState<number | null>(null), [selected, setSelected] = useState(0), [returnMap, setReturnMap] = useState(false), [cell, setCell] = useState(42), [reset, setReset] = useState<RoverRecord['mode'] | null>(null);
  const training = remaining > 0, episode: RoverEpisode = report?.trials[selected] || roverStart(20000, record.mode), playback = usePlayback(episode.trace.length, paused);
  const row = episode.trace[playback.frame < 0 ? episode.trace.length - 1 : playback.frame], view = row || episode, target = roverTarget({ ...episode, carrying: view.carrying });
  useEffect(() => {
    if (!training || paused) return;
    const timer = setTimeout(() => { const n = Math.min(25, remaining); onChange(trainRover(record, n)); setRemaining(v => v - n); }, 40);
    return () => clearTimeout(timer);
  }, [training, paused, remaining, record, onChange]);
  const previousCarry = episode.trace[Math.max(0, playback.frame - 1)]?.carrying || false;
  useEffect(() => { if (sound && playback.active && !paused && row) playAgentCue(row.collision ? 'blocked' : row.carrying !== previousCarry ? 'interact' : 'move', row.x / 3 - 1); }, [sound, playback.active, paused, row, previousCarry]);
  const observation = episode.layout * 98 + cell * 2 + Number(returnMap), values = record.q[observation], directions = ['↑', '→', '↓', '←'], moves = ['north', 'east', 'south', 'west'];
  return <div className="academy-layout"><div className="academy-stage"><Scene3D kind="learner" paused={paused} label={`Learning rover at ${view.x}, ${view.y}; target ${target[0]}, ${target[1]}; ${view.carrying ? 'returning with parcel' : 'collecting parcel'}.`} data={{ x: view.x, y: view.y, goalX: target[0], goalY: target[1], layout: episode.layout, storm: Number(record.mode === 'storm'), carrying: Number(view.carrying), ...traceData(episode.trace, playback.frame) }} /><div className="telemetry-strip"><span>LEARNING ROVER</span><strong>{report ? episode.status : 'ready'}</strong><span>{record.episodes} episodes</span></div>
      <section className="academy-panel"><h2>Learned action map</h2><div className="button-row"><button className={`btn ${returnMap ? 'secondary' : 'primary'}`} aria-pressed={!returnMap} onClick={() => setReturnMap(false)}>Collect parcel</button><button className={`btn ${returnMap ? 'primary' : 'secondary'}`} aria-pressed={returnMap} onClick={() => setReturnMap(true)}>Return to base</button></div><div className="learning-grid" role="img" aria-label="Seven by seven map. Arrows show the highest learned action value. Walls block movement; parcel is at 6, 0 and base at 0, 6.">{Array.from({ length: 49 }, (_, i) => { const x = i % 7, y = Math.floor(i / 7), wall = roverWalls(episode.layout).some(p => p[0] === x && p[1] === y), index = episode.layout * 98 + i * 2 + Number(returnMap), best = greedyAction(record.q, index), q = record.q[index][best]; return <span key={i} className={`${wall ? 'wall' : ''} ${x === view.x && y === view.y ? 'rover-here' : ''}`} style={{ backgroundColor: wall ? undefined : `rgba(141, 221, 165, ${0.05 + Math.max(0, Math.min(1, q / 25)) * 0.38})` }}>{wall ? '■' : x === view.x && y === view.y ? '●' : x === 6 && y === 0 ? 'P' : x === 0 && y === 6 ? 'B' : directions[best]}</span>; })}</div><Select label="Inspect rover cell" value={String(cell)} options={Array.from({ length: 49 }, (_, i) => ({ value: String(i), label: `(${i % 7}, ${Math.floor(i / 7)})` }))} onChange={v => setCell(Number(v))} /><dl className="q-values">{moves.map((move, i) => <div key={move}><dt>{move}</dt><dd>{values[i].toFixed(2)}</dd></div>)}</dl><p>Values estimate future reward. The largest value chooses the action; it is not a probability of success.</p></section>
      {episode.trace.length > 0 && <section className="academy-panel"><h2>Replay the rover</h2><Slider label="Rover replay tick" value={playback.frame < 0 ? episode.trace.length - 1 : playback.frame} min={0} max={episode.trace.length - 1} onChange={n => { playback.stop(); playback.setFrame(n); }} /><button className="btn secondary" disabled={paused} onClick={playback.toggle}>{playback.active ? 'Stop replay' : 'Play replay'}</button><Stats><Stat label="Replay action" value={moves[row?.action || 0]} /><Stat label="Reward this tick" value={round(row?.reward || 0)} /><Stat label="Position" value={`${view.x}, ${view.y}`} /><Stat label="Battery ticks left" value={80 - (row?.tick || 0)} /></Stats></section>}
    </div><div className="academy-work"><section className="academy-panel"><span className="eyebrow">REWARD → LEARNED VALUE → ACTION</span><h2>Teach a delivery rover</h2><p>Collect a parcel at (6, 0), then bring it to base at (0, 6). The rover starts with zero action values and learns from its own trials.</p><div className="button-row"><button className="btn secondary" disabled={training || paused} onClick={() => setReset('courier')}>Fresh courier</button><button className="btn secondary" disabled={training || paused} onClick={() => setReset('storm')}>Fresh storm courier</button></div><p>Current environment: <strong>{record.mode === 'storm' ? 'Storm · 12% clockwise drift' : 'Courier · steady movement'}</strong></p><Stats><Stat label="Learning episodes" value={record.episodes} /><Stat label="Action value rows" value={record.q.length} /><Stat label="Trial tick cap" value={80} /><Stat label="Evaluation baseline" value={baseline === null ? 'Not compared' : `${baseline}/20`} /></Stats><div className="button-row"><button className="btn primary" disabled={training || paused || record.episodes > 99000} onClick={() => { setBaseline(evaluateRover(record).successes); setReport(null); playback.stop(); setRemaining(1000); }}>Train 1,000 episodes</button><button className="btn secondary" disabled={training || paused} onClick={() => { setReport(evaluateRover(record)); setSelected(0); playback.stop(); if (sound) playAgentCue('complete', 0); }}>Evaluate learned rover</button></div>{training && <div role="status"><p>{paused ? 'Training paused.' : 'Learning from rewards. Evaluation seeds remain separate.'}</p><progress max={1000} value={1000 - remaining} aria-label="Rover training progress" /><button className="btn secondary" onClick={() => setRemaining(0)}>Stop rover training</button></div>}</section>
      <section className="academy-panel"><h2>Training delivery success</h2><Curve points={record.history.map(p => p.successes)} label={`Delivery success in training batches: ${record.history.map(p => round(p.successes)).join(', ')} percent.`} /><p>Each point summarizes a training batch. Exploratory actions can lower a training result even when the learned policy improves.</p><dl className="reward-rules"><div><dt>Every tick</dt><dd>−0.12</dd></div><div><dt>Closer / farther</dt><dd>+0.2 / −0.2</dd></div><div><dt>Blocked move</dt><dd>−1.5</dd></div><div><dt>Parcel / delivery</dt><dd>+6 / +25</dd></div></dl></section>
      {report && <section className="academy-panel evaluation-report"><span className="eyebrow">NO EXPLORATION · NO LEARNING UPDATES</span><h2>Rover evaluation</h2><Stats><Stat label="Successful deliveries" value={`${report.successes}/20`} /><Stat label="Mean evaluation ticks" value={round(report.ticks)} /><Stat label="Mean blocked moves" value={round(report.collisions)} /><Stat label="Learned environment" value={record.mode} /></Stats><Select label="Inspect rover evaluation" value={String(selected)} options={report.trials.map((e, i) => ({ value: String(i), label: `${e.seed} · ${e.status} · ${e.tick} ticks` }))} onChange={v => { playback.stop(); setSelected(Number(v)); }} /><Notice tone={episode.status === 'complete' ? 'success' : 'warning'}>{episode.status === 'complete' ? 'Parcel delivered. Compare route length and blocked moves across all trials.' : 'Delivery missed the tick cap. Inspect action values, try more learning, or compare steady and windy movement.'}</Notice><p>Twenty fixed evaluation seeds never enter learning. Layouts and task rules still belong to the same small simulation.</p></section>}
      <details className="academy-panel"><summary>How the rover learns</summary><p>Q-learning updates the selected action value using the observed reward and the best next-state value. Learning rate: 0.25. Future-reward discount: 0.97. Exploration falls from 55% toward 6% as training accumulates.</p><p>Observations include map layout, position, and whether the parcel is carried. Unlike the arena approach action, this learner has no path planner. Evaluation uses the largest learned value with exploration and learning disabled.</p><a className="text-link" href="https://gymnasium.farama.org/v1.0.0/introduction/train_agent/" target="_blank" rel="noreferrer">Explore Q-learning with Gymnasium</a></details>
    </div>{reset && <Modal title="Start fresh rover learning?" onClose={() => setReset(null)}><p>This clears this rover’s learned values and training history. Export the academy first if you want to keep them.</p><div className="modal-actions"><button className="btn secondary" onClick={() => setReset(null)}>Keep learned values</button><button className="btn primary" onClick={() => { onChange(roverFresh(reset)); setReport(null); playback.stop(); setBaseline(0); setReset(null); }}>Start fresh learning</button></div></Modal>}</div>;
}
