import { useEffect, useRef, useState } from 'react';
import { CURRICULUM, curriculum } from '../runtime/curriculum';
import { GARAGE_WORLDS, worldConfig, type WorldId } from '../runtime/garageWorlds';
import { packageRules, packageRover } from '../runtime/packages';
import type { ArenaKind } from '../runtime/arenaRules';
import { CONTEXTS, DEFAULT_BUDGETS, MOCK_MODES, bytes, controllerSpec, validateController, type Budgets, type ContextStrategy, type ControllerSpec, type ModelInfo, type ModelObservation, type ProviderAdapter } from '../agents/contracts';
import { mockAdapter } from '../agents/mock';
import { DEFAULT_BRIDGE, ollamaAdapter } from '../agents/ollama';
import { createAgentSession, type AgentReceipt, type AgentSession } from '../agents/session';
import { verifyAgentReceipt } from '../agents/receipts';
import { rememberGarage, type GarageSave } from '../agents/notebook';
import { createModelExperiment, modelExperimentSteps, validateModelExperiment, type ModelExperiment } from '../agents/experiments';
import type { AcademySave } from '../training/models';
import { Select, Slider } from '../games/advanced/ui';
import { Notice, Stat, Stats } from '../games/shared';
import { playAgentCue } from '../systems/sound';
import GarageScene from './GarageScene';

const names: Record<WorldId, string> = { sports: 'Sport Bot Arena', outpost: 'Survival Agent Outpost', scenario: 'Scenario Agent Dispatch', space: 'Space Agent Rendezvous', rover: 'Delivery rover', survey: 'Survey · hidden cache', community: 'Community Restore · two roles', 'signal-maze': 'Signal Maze · misleading signs' };
const modes: Record<typeof MOCK_MODES[number], string> = { policy: 'Known public-observation policy', legal: 'First legal action', illegal: 'Illegal proposal', malformed: 'Malformed JSON', refusal: 'Provider refusal', timeout: 'Provider timeout', oversized: 'Oversized response', alternating: 'Illegal then valid · retry recovery', blocked: 'Blocked-movement probe', 'task-failure': 'Task-precondition probe', 'resource-failure': 'Resource-depletion probe' };
const contexts: Record<ContextStrategy, string> = { STATE_ONLY: 'Current state only', RECENT_WINDOW: 'Recent six actions', EVENT_SUMMARY: 'Bounded event counts', BOUNDED_EPISODE_MEMORY: 'Public episode notebook' };
type Choice = 'model' | 'reference' | 'human' | 'champion' | 'learned';
function download(name: string, data: unknown) { const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }

export default function AgentGarage({ academy, paused, sound, onChange }: { academy: AcademySave; paused: boolean; sound: boolean; onChange: (save: GarageSave) => void }) {
  const [world, setWorld] = useState<WorldId>('survey'), [seed, setSeed] = useState(3), [stage, setStage] = useState('explorer'), [context, setContext] = useState<ContextStrategy>('STATE_ONLY'), [budgets, setBudgets] = useState<Budgets>({ ...DEFAULT_BUDGETS });
  const [provider, setProvider] = useState<'mock' | 'ollama'>('mock'), [model, setModel] = useState('mock-policy'), [address, setAddress] = useState(DEFAULT_BRIDGE), [models, setModels] = useState<ModelInfo[]>([]), [metadata, setMetadata] = useState<ModelInfo | null>(null), [connected, setConnected] = useState(false), [connecting, setConnecting] = useState(false), [mockMode, setMockMode] = useState<typeof MOCK_MODES[number]>('policy');
  const [choice, setChoice] = useState<Choice>('model'), [baseline, setBaseline] = useState<Choice>('reference'), [format, setFormat] = useState<'schema' | 'json'>('schema'), [second, setSecond] = useState<Choice>('reference'), [notice, setNotice] = useState(''), [revision, setRevision] = useState(0), [localPaused, setLocalPaused] = useState(false), [recording, setRecording] = useState<AgentReceipt | null>(academy.garage.receipt), [inspection, setInspection] = useState(0), [manifest, setManifest] = useState<ModelExperiment | null>(academy.garage.experiments[0] || null), [progress, setProgress] = useState<{ completed: number; total: number } | null>(null);
  const live = useRef<AgentSession | null>(null), adapter = useRef<ReturnType<typeof ollamaAdapter> | null>(null), connectionAbort = useRef<AbortController | null>(null), experimentAbort = useRef<AbortController | null>(null), alive = useRef(true), garage = useRef(academy.garage), notify = useRef(onChange), wasRunning = useRef(false), comparisonSession = useRef<AgentSession | null>(null), pauseRef = useRef(false), resumeWaiters = useRef<(() => void)[]>([]);
  const inactive = paused || localPaused, current = live.current, busy = !!current?.busy || !!progress, row = recording && inspection > 0 ? recording.records[inspection - 1] : null;
  useEffect(() => { garage.current = academy.garage; notify.current = onChange; }, [academy.garage, onChange]);
  useEffect(() => { alive.current = true; return () => { alive.current = false; live.current?.stop(); connectionAbort.current?.abort(); experimentAbort.current?.abort(); resumeWaiters.current.splice(0).forEach(resolve => resolve()); adapter.current?.disconnect(); }; }, []);
  useEffect(() => { pauseRef.current = inactive; if (inactive) comparisonSession.current?.pause(); else { comparisonSession.current?.resume(); resumeWaiters.current.splice(0).forEach(resolve => resolve()); } const s = live.current; if (!s) return; if (inactive) { wasRunning.current = s.continuous; s.pause(); } else if (s.status === 'PAUSED') { s.resume(); if (wasRunning.current) s.run(); } }, [inactive]);
  const persist = (receipt: AgentReceipt, spec?: ModelExperiment) => { const next = rememberGarage(garage.current, receipt, spec); garage.current = next; notify.current(next); setRecording(receipt); setInspection(receipt.records.length); };
  const step = async (action?: string) => {
    const s = live.current; if (!s) return;
    try { await s.step(action ? { type: action } : undefined); if (!alive.current) return; persist(s.receipt()); if (sound && s.result().terminal) playAgentCue(s.result().success ? 'complete' : 'blocked', 0); }
    catch (error) { if (alive.current) setNotice(error instanceof Error ? error.message : 'The controller could not step.'); }
  };
  useEffect(() => { if (!current?.continuous || current.busy || inactive || progress) return; const timer = setTimeout(() => { void step(); }, 35); return () => clearTimeout(timer); }, [revision, inactive, progress]);
  const availableProviders = (): ProviderAdapter[] => [mockAdapter(), ...(adapter.current && connected ? [adapter.current] : [])];
  const spec = (selected: Choice, id: string): ControllerSpec => {
    let next: ControllerSpec;
    if (selected === 'champion' && ['sports', 'outpost', 'scenario', 'space'].includes(world)) { const champion = academy.controllers[world as ArenaKind]?.champion; if (!champion) throw new Error('Train a champion in the controller lab first.'); next = { ...controllerSpec('rules'), package: packageRules(world as ArenaKind, champion) }; }
    else if (selected === 'learned' && world === 'rover') next = { ...controllerSpec('q-learning'), package: packageRover(academy.rover.q, academy.rover.mode, academy.rover.episodes) };
    else if (selected === 'model') { if (provider === 'ollama' && (!connected || !model)) throw new Error('Connect the bridge and choose an installed model first.'); next = controllerSpec('model', provider, model); next.settings.mockMode = mockMode; next.settings.seed = seed; next.settings.format = format; }
    else if (selected === 'human' || selected === 'reference') next = controllerSpec(selected);
    else throw new Error('This frozen controller is incompatible with the selected world.');
    return validateController({ ...next, id });
  };
  const start = () => {
    try { live.current?.stop(); const definition = curriculum(stage), first = spec(choice, 'controller-one'), other = world === 'community' ? spec(second, 'controller-two') : null;
      live.current = createAgentSession({ config: worldConfig(world, seed, definition.difficulty, definition.trainingVariant, world === 'rover' && choice === 'learned' ? academy.rover.mode : 'courier'), controllers: other ? { engineer: first, logistics: other } : { pilot: first }, providers: availableProviders(), budgets, context, onChange: () => { if (alive.current) setRevision(n => n + 1); } });
      setLocalPaused(false); persist(live.current.receipt()); setNotice('World ready. Choose one step or run the bounded episode.'); document.getElementById('garage-world')?.scrollIntoView({ block: 'start' });
    } catch (error) { setNotice(error instanceof Error ? error.message : 'The world could not start.'); }
  };
  const connect = async () => {
    connectionAbort.current?.abort(); const abort = new AbortController(); connectionAbort.current = abort; setConnecting(true); setNotice(''); const timeout = setTimeout(() => abort.abort(), 5000);
    try { const next = ollamaAdapter(address); await next.connect(abort.signal); const found = await next.models(abort.signal); if (!alive.current || abort.signal.aborted) return; adapter.current = next; live.current?.connectProvider(next); setModels(found); setConnected(true); setModel(''); setNotice(found.length ? 'Bridge connected. Choose an installed model explicitly.' : 'Bridge connected, but no supported local model is installed. Offline mock remains available.'); }
    catch (error) { if (alive.current) { setConnected(false); setNotice(error instanceof Error ? error.message : 'The bridge could not connect.'); } }
    finally { clearTimeout(timeout); if (alive.current) setConnecting(false); }
  };
  const chooseModel = async (id: string) => { setModel(id); setMetadata(null); if (!id || !adapter.current) return; const abort = new AbortController(), timer = setTimeout(() => abort.abort(), 5000); connectionAbort.current?.abort(); connectionAbort.current = abort; try { const info = await adapter.current.metadata(id, abort.signal); if (alive.current && !abort.signal.aborted) setMetadata(info); } catch { if (alive.current) setNotice('Model metadata is unavailable. The bridge will recheck compatibility before inference.'); } finally { clearTimeout(timer); } };
  const disconnect = () => { connectionAbort.current?.abort(); experimentAbort.current?.abort(); resumeWaiters.current.splice(0).forEach(resolve => resolve()); adapter.current?.disconnect(); adapter.current = null; live.current?.disconnect(); setConnected(false); setModels([]); setModel(''); setMetadata(null); setProgress(null); setNotice('Provider disconnected. Pending responses were cancelled.'); };
  const changeController = (selected: Choice) => { try { const s = live.current; if (!s) return; s.handoff(s.actor(), spec(selected, `handoff-${s.actor()}`), selected === 'human' ? 'Operator took manual control.' : 'Operator changed the controller.'); setLocalPaused(false); persist(s.receipt()); } catch (error) { setNotice(error instanceof Error ? error.message : 'Controller handoff failed.'); } };
  const compare = async (imported?: ModelExperiment) => {
    const abort = new AbortController(); experimentAbort.current?.abort(); experimentAbort.current = abort;
    try { live.current?.stop(); live.current = null; const candidate = spec(choice, 'controller-one'), reference = spec(baseline, 'comparison-baseline'), next = imported || createModelExperiment(world, candidate, reference, stage, seed, context, budgets, 2, world === 'community' ? spec(second, 'controller-two') : undefined);
      if (Object.values(next.controllers).some(c => c.provider === 'ollama') && !connected) throw new Error('Connect a local bridge before rerunning this model manifest.');
      setNotice(''); setProgress({ completed: 0, total: next.trialsPerSplit * 8 }); const iterator = modelExperimentSteps(next, availableProviders(), abort.signal, { session: s => { comparisonSession.current = s; }, beforeStep: async () => { if (pauseRef.current && !abort.signal.aborted) await new Promise<void>(resolve => resumeWaiters.current.push(resolve)); } });
      while (true) { const part = await iterator.next(); if (!alive.current || abort.signal.aborted) return; if (part.done) { persist(part.value.receipt, part.value.manifest); setManifest(part.value.manifest); setProgress(null); const matches = imported?.report && imported.report.trials.every((t, i) => t.worldHash === part.value.manifest.report!.trials[i].worldHash && t.modelHash === part.value.manifest.report!.trials[i].modelHash); setNotice(imported ? matches ? 'Mock regeneration and world traces match. World replay is verified separately.' : 'Rerun complete. Model generation differed; each recorded world replay verifies independently.' : 'Frozen comparison complete. No weights or prompt settings were updated.'); break; } else { setProgress({ completed: part.value.completed, total: part.value.total }); persist(part.value.receipt); await new Promise<void>(resolve => setTimeout(resolve, 0)); } }
    } catch (error) { if (alive.current && !abort.signal.aborted) setNotice(error instanceof Error ? error.message : 'Comparison failed.'); }
    finally { if (alive.current && experimentAbort.current === abort) setProgress(null); }
  };
  const importFile = async (type: 'receipt' | 'manifest' | 'controller', file?: File) => {
    if (!file) return; try { if (file.size > 500000) throw new Error('Choose an agent file smaller than 500 KB.'); const raw = JSON.parse(await file.text()); if (!alive.current) return;
      if (type === 'receipt') { const verified = verifyAgentReceipt(raw); live.current?.stop(); live.current = null; persist(verified); setInspection(0); setNotice('World replay verified from recorded actions. Model regeneration was not requested.'); }
      else if (type === 'controller') { const validated = validateController(raw); if (!live.current) throw new Error('Start a world before importing a controller handoff.'); live.current.handoff(live.current.actor(), validated, 'Operator imported a data-only controller.'); persist(live.current.receipt()); setNotice('Controller imported into the current world.'); }
      else { const validated = validateModelExperiment(raw); await compare(validated); }
    } catch (error) { if (alive.current) setNotice(error instanceof Error ? error.message : 'Import failed.'); }
  };
  const inspecting = recording && recording.records.length > 0 && inspection < recording.records.length;
  const recorded: ModelObservation | null = row?.transition ? { ...row.observation, tick: row.transition.view.tick, state: row.transition.view.state, target: row.transition.view.target, terminal: row.transition.result } : row?.observation || recording?.records[0]?.observation || null;
  const o: ModelObservation | null = inspecting ? recorded : current && !progress ? current.observation() : row?.transition ? { ...row.observation, tick: row.transition.view.tick, state: row.transition.view.state, target: row.transition.view.target, terminal: row.transition.result } : recording?.records[0]?.observation || null;
  const actor = current?.actor(), activeSpec = actor ? current!.controllers[actor] : null, report = manifest?.report;
  const controllerOptions = [{ value: 'model', label: 'Selected model or mock' }, { value: 'reference', label: 'Public reference policy' }, { value: 'human', label: 'Human control' }, ...(world === 'rover' ? [{ value: 'learned', label: 'Frozen learned Q-table' }] : ['sports', 'outpost', 'scenario', 'space'].includes(world) && academy.controllers[world as ArenaKind] ? [{ value: 'champion', label: 'Frozen academy champion' }] : [])];
  return <div className="agent-garage"><div className="runtime-intro"><span className="eyebrow">SAME WORLD · SAME RULES · DIFFERENT CONTROLLERS</span><h2>Agent garage</h2><p>Connect a controller, inspect its proposal, and see what the world actually executes.</p><p className="small">Offline mock works immediately. Ollama is optional. Simulation scores describe these tasks; they are not intelligence or professional qualifications.</p><div className="button-row"><button className="btn primary" disabled={busy || inactive || connecting} onClick={start}>Start garage world</button></div></div>
    <div className="garage-layout"><div className="academy-work"><fieldset className="academy-panel" disabled={busy || inactive || connecting}><legend>Controller connection</legend><Select label="Model provider" value={provider} options={[{ value: 'mock', label: 'Offline mock' }, { value: 'ollama', label: 'Local Ollama' }]} onChange={v => { disconnect(); setProvider(v as 'mock' | 'ollama'); setModel(v === 'mock' ? 'mock-policy' : ''); setNotice(''); }} />
      {provider === 'mock' ? <><p>No model server or internet is required.</p><Select label="Mock behavior" value={mockMode} options={MOCK_MODES.map(value => ({ value, label: modes[value] }))} onChange={v => setMockMode(v as typeof MOCK_MODES[number])} /></> : <><label className="garage-input">Loopback bridge address<input type="url" value={address} maxLength={100} onChange={e => setAddress(e.target.value)} /></label><div className="button-row"><button className="btn secondary" onClick={() => { void connect(); }}>Connect local bridge</button></div><Select label="Installed local model" value={model} options={[{ value: '', label: 'Choose an installed model' }, ...models.map(m => ({ value: m.id, label: m.id }))]} onChange={v => { void chooseModel(v); }} /><p>Start the optional bridge on the device running this browser. Allow only the studio origin. Browser local-network permission may also be required; running the studio locally is the fallback.</p><details><summary>Local setup commands</summary><pre className="runtime-json" tabIndex={0}>npm run agent:bridge{window.location.protocol === 'https:' ? ` -- --allow-origin ${window.location.origin}` : ''}</pre><p>Ollama must already have a local model installed. The studio does not download or delete models.</p><a href="https://github.com/larrinamsalva/brainsweatstudios/blob/main/docs/agent-bridge.md" target="_blank" rel="noreferrer" className="text-link">Read the local connection guide</a></details>{metadata && <dl className="runtime-facts"><div><dt>Model bytes</dt><dd>{metadata.sizeBytes ?? 'UNKNOWN'}</dd></div><div><dt>Context tokens</dt><dd>{metadata.contextLength ?? 'UNKNOWN'}</dd></div><div><dt>Capabilities</dt><dd>{metadata.capabilities.join(', ') || 'UNKNOWN'}</dd></div></dl>}</>}
    </fieldset>{provider === 'ollama' && <div className="button-row"><button className="btn secondary" disabled={!connected && !connecting} onClick={disconnect}>Disconnect provider</button></div>}<fieldset className="academy-panel" disabled={busy || inactive}><legend>World and controllers</legend><Select label="Garage environment" value={world} options={GARAGE_WORLDS.map(value => ({ value, label: names[value] }))} onChange={v => { setWorld(v as WorldId); setChoice('model'); setBaseline('reference'); }} /><Select label="Garage curriculum" value={stage} options={CURRICULUM.map(s => ({ value: s.id, label: s.title }))} onChange={setStage} /><Slider label="Garage seed" min={0} max={99} value={seed} onChange={setSeed} /><Select label={world === 'community' ? 'Engineer controller' : 'Primary controller'} value={choice} options={controllerOptions} onChange={v => setChoice(v as Choice)} />{world === 'community' && <Select label="Logistics controller" value={second} options={controllerOptions.filter(o => !['champion','learned'].includes(o.value))} onChange={v => setSecond(v as Choice)} />}<Select label="Comparison baseline" value={baseline} options={controllerOptions.filter(o => !['model', 'human'].includes(o.value))} onChange={v => setBaseline(v as Choice)} /><Select label="Structured output mode" value={format} options={[{ value: 'schema', label: 'JSON schema' }, { value: 'json', label: 'JSON fallback · same validation' }]} onChange={v => setFormat(v as 'schema' | 'json')} /><Select label="Model context" value={context} options={CONTEXTS.map(value => ({ value, label: contexts[value] }))} onChange={v => setContext(v as ContextStrategy)} /><div className="button-row"><button className="btn secondary" disabled={choice === 'human' || world === 'community' && second === 'human'} onClick={() => { void compare(); }}>Compare frozen controllers</button></div>
      <details><summary>Operator budgets</summary><p>Limits apply before a request or world action. There is no hidden cloud fallback.</p>{([['maxTicks', 'Maximum world ticks', 1, 120], ['maxRequests', 'Maximum controller requests', 1, 240], ['timeoutMs', 'Request timeout in milliseconds', 10, 60000], ['retries', 'Retries per proposal', 0, 2], ['observationBytes', 'Observation byte limit', 2048, 24000], ['responseBytes', 'Response byte limit', 128, 8192], ['notebookBytes', 'Notebook byte limit', 256, 4096]] as const).map(([key, label, min, max]) => <label className="garage-input" key={key}>{label}<input type="number" min={min} max={max} value={budgets[key]} onChange={e => setBudgets(b => ({ ...b, [key]: Number(e.target.value) }))} /></label>)}</details>
    </fieldset></div><div className="academy-stage"><section className="academy-panel garage-live" id="garage-world"><div className="garage-status"><span className="eyebrow">WORLD AUTHORITY</span><strong role="status" aria-live="polite">{current?.status || 'IDLE'}</strong></div>{o ? <><GarageScene observation={o} paused={inactive} variant={(inspecting || !current || progress ? recording?.config : current.config)?.variant || 'standard'} /><p>{o.objective}</p><Stats><Stat label="World tick" value={o.tick} /><Stat label="World score" value={o.terminal.score} /><Stat label="Remaining resource" value={o.terminal.resources} /><Stat label="Current actor" value={o.turn} /></Stats></> : <p>Start a world to inspect its observation and legal actions.</p>}
      {current && <><div className="button-row"><button className="btn primary" disabled={busy || inactive || current.result().terminal || current.ending === 'stopped' || activeSpec?.family === 'human'} onClick={() => { void step(); }}>Step controller</button><button className="btn secondary" disabled={busy || inactive || current.result().terminal || current.ending === 'stopped' || activeSpec?.family === 'human'} onClick={() => current.run()}>Run garage episode</button><button className="btn secondary" disabled={paused || current.result().terminal || current.ending === 'stopped'} onClick={() => { if (current.status === 'PAUSED' && !localPaused) current.resume(); else setLocalPaused(p => !p); }}>{localPaused || current.status === 'PAUSED' ? 'Resume garage' : 'Pause garage'}</button><button className="btn secondary" onClick={() => { current.stop(); persist(current.receipt()); setNotice('Episode stopped. Its recorded actions remain replayable.'); }}>Stop garage episode</button></div><div className="button-row"><button className="btn secondary" disabled={!!progress || paused || current.result().terminal} onClick={() => changeController('human')}>Take manual control</button><button className="btn secondary" disabled={busy || inactive || current.result().terminal} onClick={() => changeController('reference')}>Hand off to reference</button><button className="btn secondary" disabled={busy || inactive || current.result().terminal} onClick={() => changeController('model')}>Hand off to model</button></div>{activeSpec?.family === 'human' && <fieldset className="garage-actions" disabled={busy || inactive}><legend>Manual legal actions</legend>{current.observation().legalActions.map(a => <button className="btn secondary" key={a.type} onClick={() => { void step(a.type); }}>{a.type}</button>)}</fieldset>}
      <p className="small">Controller handoffs preserve the live world and record the actor, tick and reason.</p>{current.lastError && <p className="garage-error">Controller error: {current.lastError}</p>}<details><summary>Current observation and legal actions</summary><pre className="runtime-json" tabIndex={0}>{JSON.stringify(current.observation(), null, 2)}</pre></details></>}
    </section>{progress && <section className="academy-panel" role="status"><h3>{inactive ? 'Frozen comparison paused' : 'Frozen comparison running'}</h3><progress max={progress.total} value={progress.completed} aria-label="Model comparison progress" /><p>{progress.completed}/{progress.total}</p><button className="btn secondary" onClick={() => { experimentAbort.current?.abort(); resumeWaiters.current.splice(0).forEach(resolve => resolve()); setProgress(null); setNotice('Comparison stopped. Completed episode evidence remains saved.'); }}>Stop model comparison</button></section>}
    {recording && <section className="academy-panel"><h3>Model receipt inspector</h3><p>Replay uses recorded actions. Asking the model again may produce a different run.</p><Slider label="Model decision inspection" value={inspection} min={0} max={recording.records.length} onChange={setInspection} /><dl className="runtime-facts"><div><dt>Proposed action</dt><dd>{row?.attempts.at(-1)?.proposed?.type || 'No proposal'}</dd></div><div><dt>Validated action</dt><dd>{row?.validated?.action.type || 'No validated action'}</dd></div><div><dt>Executed action</dt><dd>{row?.transition?.executedAction.type || 'World did not advance'}</dd></div><div><dt>World reward</dt><dd>{row?.transition?.reward.toFixed(2) || '0'}</dd></div><div><dt>Recorded controller</dt><dd>{row?.controller.id || 'Initial controllers'}</dd></div><div><dt>Model-provided note</dt><dd>{row?.validated?.note || 'No public note supplied'}</dd></div></dl><div className="button-row"><button className="btn secondary" onClick={() => { try { verifyAgentReceipt(recording); setNotice('World replay verified from recorded actions. Model regeneration was not requested.'); } catch (error) { setNotice(error instanceof Error ? error.message : 'Replay differs.'); } }}>Verify model world replay</button><button className="btn secondary" onClick={() => download('brain-sweat-model-receipt.json', recording)}>Export model receipt</button></div><details><summary>Recorded proposal, validation and world result</summary><pre className="runtime-json" tabIndex={0}>{JSON.stringify(row || { initialHash: recording.initialHash, controllers: recording.initialControllers }, null, 2)}</pre></details><details><summary>Handoff history and trace hashes</summary><pre className="runtime-json" tabIndex={0}>{JSON.stringify({ handoffs: recording.handoffs, worldTraceHash: recording.worldTraceHash, modelTraceHash: recording.modelTraceHash, finalHash: recording.finalHash }, null, 2)}</pre></details><details><summary>Agent notebook · public task notes</summary><p>Facts, plans, warnings, completed and unresolved items are bounded public annotations. They are not private cognition or learned weights.</p><pre className="runtime-json" tabIndex={0}>{JSON.stringify(row?.notebook || current?.notebook() || recording.records.at(-1)?.notebook || {}, null, 2)}</pre></details><p className="small">Receipt bytes: {bytes(recording)}. Provider latency and world step time are recorded separately.</p></section>}
    </div></div>
    {report && manifest && <section className="academy-panel"><h3>Frozen model comparison</h3><p>TRAIN is practice only; VALIDATION is a frozen check; HOLDOUT is the final report. No model weights or prompt settings change. Repeated tuning against HOLDOUT contaminates the comparison.</p><div className="runtime-table" tabIndex={0} role="region" aria-label="Frozen model trial results"><table><thead><tr><th scope="col">Split</th><th scope="col">Controller</th><th scope="col">Seed</th><th scope="col">Complete</th><th scope="col">Score</th><th scope="col">Ticks</th><th scope="col">Resources</th><th scope="col">Invalid</th><th scope="col">Timeouts</th><th scope="col">Retries</th></tr></thead><tbody>{report.trials.map((t, i) => <tr key={i}><th scope="row">{t.transfer ? 'TRANSFER HOLDOUT' : t.split}</th><td>{t.candidate ? 'Candidate' : 'Reference'}</td><td>{t.seed}</td><td>{t.success ? 'Yes' : 'No'}</td><td>{t.score}</td><td>{t.ticks}</td><td>{t.resources}</td><td>{t.invalid}</td><td>{t.timeouts}</td><td>{t.retries}</td></tr>)}</tbody></table></div><Stats><Stat label="Transfer delta in percentage points" value={report.transferDelta} /><Stat label="Holdout delta against reference" value={report.baselineDelta} /><Stat label="Invalid-then-valid recoveries" value={report.recovery.rejectedThenValid} /><Stat label="Failed controller turns" value={report.recovery.failedTurns} /></Stats><p className="small">Monetary cost: UNKNOWN. Token counts appear only when the provider reports them.</p><details><summary>Failure modes, request efficiency and usage</summary><pre className="runtime-json" tabIndex={0}>{JSON.stringify({ totalRequests: report.totalRequests, successfulEpisodesPerRequest: report.trials.filter(t => t.success).length / Math.max(1, report.totalRequests), recovery: report.recovery, failures: report.trials.filter(t => t.failures.length).map(t => ({ seed: t.seed, split: t.split, transfer: t.transfer, candidate: t.candidate, failures: t.failures })), usage: report.usage, seeds: manifest.seeds }, null, 2)}</pre></details><div className="button-row"><button className="btn secondary" disabled={busy || inactive} onClick={() => { void compare(manifest); }}>Rerun model manifest</button><button className="btn secondary" onClick={() => download('brain-sweat-model-experiment.json', manifest)}>Export model manifest</button></div></section>}
    <fieldset className="academy-panel" disabled={busy || inactive}><legend>Local data exchange</legend><div className="button-row">{(['receipt', 'manifest', 'controller'] as const).map(type => <label className="btn secondary import-button" key={type}>Import model {type}<input type="file" accept=".json,application/json" aria-label={`Import model ${type}`} onChange={e => { void importFile(type, e.target.files?.[0]); e.target.value = ''; }} /></label>)}{activeSpec && <button className="btn secondary" onClick={() => download('brain-sweat-agent-controller.json', activeSpec)}>Export garage controller</button>}</div>{academy.garage.experiments.length > 0 && <div className="button-row">{academy.garage.experiments.map(m => <button className="text-link" key={m.id} onClick={() => { setManifest(m); }}>{names[m.config.world]} · {m.id.slice(0,8)}</button>)}</div>}<p>Observations, notes, receipts and experiments stay with this local profile. Starting an Ollama run sends only public simulation observations to the selected local bridge. No analytics, cloud fallback or automatic online submission.</p><p className="small">Model competitions are a future feature. Existing online competitions still execute validated data-only policies on the server.</p></fieldset>
    {notice && <Notice>{notice}</Notice>}
  </div>;
}
