import { useState } from 'react';
import { games } from '../data/games';
import { useStudio } from '../systems/StudioContext';
import { checkpoint, clearCheckpoint, markBotPractice } from '../systems/profiles';
import type { GameId } from '../data/types';
export default function BotLab() {
  const { save, updateSettings } = useStudio(); const [world, setWorld] = useState<GameId>('money'); const [mission, setMission] = useState(0); const [notice, setNotice] = useState('');
  return <section><div className="page-heading"><div><span className="eyebrow">Observe and adapt</span><h1>Bot lab</h1><p>Watch an optional local agent operate the actual mission controls. Pause it, inspect the plan, or take over.</p></div></div><div className="settings-panel"><h2>A practice run you can see</h2><p>These are deterministic authored player strategies, not a remote AI model. Practice never adds XP, badges, or streaks. Automated checks find broken flows; they cannot measure how a real child understands a game.</p><label className="setting-range"><span>World</span><select aria-label="Bot world" value={world} onChange={e => setWorld(e.target.value as GameId)}>{games.map(g => <option key={g.id} value={g.id}>{g.title}</option>)}</select></label><label className="setting-range"><span>Mission</span><select aria-label="Bot mission" value={mission} onChange={e => setMission(Number(e.target.value))}>{Array.from({ length: 8 }, (_, i) => <option key={i} value={i}>Mission {i + 1}</option>)}</select></label><p>Difficulty: {save.difficulty}. Change it in the studio toolbar.</p><button className="btn primary" onClick={() => { const key = `${world}/${save.difficulty}/${mission}`; const saved = checkpoint(key); if (saved && !saved.botPractice) { setNotice('An earned-play checkpoint is saved here. Resume it first or choose a different mission for bot practice.'); return; } if (saved?.botPractice) clearCheckpoint(key); updateSettings({ botControl: true }); markBotPractice(key); window.location.hash = `${games.find(g => g.id === world)!.route}?mission=${mission + 1}&bot=1`; }}>Start bot practice</button>{notice && <p role="status">{notice}</p>}</div><div className="prose-panel"><h2>Agent playtest coverage</h2><p>The automated test suite checks completion, rewards, checkpoints, profile isolation, keyboard controls, narrow screens, Spanish, fallback graphics, and invalid imports. A bot can still miss confusing wording or an untried strategy. The repository publishes the actual coverage and limits.</p><a className="text-link" href="https://github.com/larrinamsalva/brainsweatstudios/blob/main/docs/verification.md" target="_blank" rel="noreferrer">View the verification record</a></div></section>;
}
