import { useState } from 'react';
import { courseById, courses, lessonScore, type LessonRecord, type LocalText } from '../data/classes';
import { gameById } from '../data/games';
import { useStudio } from '../systems/StudioContext';
import { experiment } from '../games/advanced/experiments';
import { Formula, Slider } from '../games/advanced/ui';
import { Stat, Stats, Notice } from '../games/shared';
import Icon from '../components/Icon';
export default function Classes({id,world}:{id?:string;world?:string}){
 const{save,saveLesson}=useStudio();const [filter,choose]=useState(world||'all');const [search,find]=useState('');const c=id?courseById(id):undefined;const text=(v:LocalText)=>v[save.settings.locale];
 const [s,set]=useState<LessonRecord>(()=>c?(save.classes[c.id]||{parameter:c.initial,answers:[-1,-1,-1],tested:false,best:0,attempts:0,date:''}):{parameter:0,answers:[],tested:false,best:0,attempts:0,date:''});
 if(id&&!c)return <div className="empty-state"><h1>Class not found.</h1><a href="#/classes" className="btn primary">Explore classes</a></div>;
 if(c){const output=experiment(c.experiment,s.parameter);const update=(next:LessonRecord,submit=false)=>{const record=saveLesson(c.id,next.parameter,next.answers,submit);set(record);};const score=lessonScore(c,s.answers);const game=gameById(c.world)!;
 return <><a className="back-link" href={`#/classes?world=${c.world}`}><Icon name="left"/>All classes</a><div className="page-heading"><div><span className="eyebrow">HANDS-ON CLASS · {game.title}</span><h1>{text(c.title)}</h1><p>{text(c.description)}</p></div><a className="btn secondary" href={`#${game.route}`}>Open the game<Icon name="play"/></a></div><div className="class-detail"><section className="prose-panel"><h2>Understand the idea</h2><p>{text(c.idea)}</p><p><strong>Suggested preparation:</strong> {text(c.prerequisite)}</p><h2>Worked example</h2><p className="worked-example">{text(c.example)}</p>{c.source&&<a className="text-link" href={c.source.url} target="_blank" rel="noreferrer">{c.source.title} ↗</a>}</section><section className="prose-panel experiment-panel"><h2>Try the experiment</h2><Slider label={text(c.parameter)} value={s.parameter} min={c.min} max={c.max} onChange={parameter=>update({...s,parameter})}/><Formula>{output.formula}</Formula><Stats>{output.rows.map(([label,value,unit])=><Stat key={label} label={label} value={`${value} ${unit}`}/>)}</Stats><p>Change one input and compare the measured outputs. Predict the result before moving the control.</p></section><section className="prose-panel class-checks"><h2>Check your understanding</h2>{c.questions.map((q,i)=><fieldset className="knowledge-check" key={i}><legend>{i+1}. {text(q.prompt)}</legend>{q.choices.map((choice,j)=><label key={j}><input type="radio" name={`check-${i}`} checked={s.answers[i]===j} onChange={()=>update({...s,answers:s.answers.map((a,n)=>n===i?j:a),tested:false})}/><span>{text(choice)}</span></label>)}{s.tested&&<Notice tone={s.answers[i]===q.correct?'success':'info'}>{text(q.why)}</Notice>}</fieldset>)}<button className="btn primary" disabled={s.answers.some(a=>a<0)} onClick={()=>update(s,true)}>Check my understanding</button>{s.tested&&<Notice tone={score===100?'success':'info'}>{score===100?'All three ideas are clear. Try them in the game.':'Review the explanations, revise your choices, and check again.'} {score}/100 · Best: {s.best}/100</Notice>}<div className="button-row"><a className="btn primary" href={`#${game.route}`}>Apply this in {game.title}<Icon name="right"/></a><a className="btn secondary" href={`#/lab/${c.world}`}>Run in the retro lab</a>{c.id.startsWith('agent-')&&<a className="btn secondary" href={`#/academy?arena=${c.world}`}>Try this in the academy</a>}</div></section></div></>;}
 const filtered=courses.filter(c=>(filter==='all'||c.world===filter)&&`${text(c.title)} ${text(c.description)} ${gameById(c.world)?.title}`.toLowerCase().includes(search.toLowerCase()));const mastered=Object.values(save.classes).filter(r=>r.best===100).length;
 return <><div className="page-heading"><div><span className="eyebrow">LEARN IT · TRY IT · BUILD IT</span><h1>The classroom is a laboratory.</h1><p>{courses.length} hands-on classes. Worked examples, live experiments, and checks that explain every answer.</p></div><span className="quiet-pill">{mastered}/{courses.length} classes mastered</span></div><div className="class-intro"><Icon name="layers" size={35}/><p>Start anywhere. Preparation suggestions help you choose a route; every class and game is open. Class results stay separate from game XP.</p></div><div className="class-filters"><label>Learning world<select aria-label="Learning world" value={filter} onChange={e=>choose(e.target.value)}><option value="all">All learning worlds</option>{[...new Set(courses.map(c=>c.world))].map(id=><option key={id} value={id}>{gameById(id)?.title}</option>)}</select></label><label className="search-box"><Icon name="search"/><span className="sr-only">Search classes</span><input aria-label="Search classes" placeholder="Search classes" value={search} onChange={e=>find(e.target.value)}/></label></div><div className="class-grid">{filtered.map((c,i)=>{const game=gameById(c.world)!,record=save.classes[c.id];return <article className="class-card" key={c.id}><div className="class-card-top"><span>{String(i+1).padStart(2,'0')}</span><Icon name={game.icon} size={30}/></div><span className="eyebrow">{game.title}</span><h2>{text(c.title)}</h2><p>{text(c.description)}</p><p className="small">Suggested preparation: {text(c.prerequisite)}</p><span className="class-status">{record?.best===100?'Mastered':record?.attempts?`Best: ${record.best}/100`:record?'Experiment in progress':'Ready to explore'}</span><a className="btn secondary" href={`#/class/${c.id}`}>Enter class<Icon name="right"/></a></article>;})}</div>{!filtered.length&&<Notice>No classes match that search. Try another topic.</Notice>}</>;
}
