import type { FamilyObservation, FamilyResult, ScoreSpec } from '../families/types';
import { FAMILY_TITLES } from '../families/types';
import { translate as t } from '../i18n/translate';
export default function FamilyTelemetry({view,result,vehicleNames}:{view:FamilyObservation;result:FamilyResult;vehicleNames?:Record<string,string>}) {
    const s=view.state;
    return <section className="family-telemetry" aria-label={t('Family telemetry')}><h3>{t(FAMILY_TITLES[view.family])}</h3>
        {view.family==='auto-circuit'&&(()=>{const cars=result.public.cars as {id:string;position:number;energy:number;speed:number;damage:number;lane:number}[],track=result.public.track as {segments:{length:number}[]},length=track.segments.reduce((n,x)=>n+x.length,0);return <><svg role="img" aria-label={t('Virtual race positions')} viewBox="0 0 400 220"><title>{t('Virtual race positions')}</title><ellipse cx="200" cy="110" rx="158" ry="78" fill="none" stroke="currentColor" strokeWidth="24" opacity=".18"/>{cars.map((c,i)=>{const angle=c.position/length*Math.PI*2-Math.PI/2;return <g key={c.id}><circle cx={200+(158+c.lane*6)*Math.cos(angle)} cy={110+(78+c.lane*4)*Math.sin(angle)} r={9+(i&&cars.some((n,j)=>j<i&&n.position===c.position&&n.lane===c.lane)?3:0)} fill={i&&cars.some((n,j)=>j<i&&n.position===c.position&&n.lane===c.lane)?'none':['#665bd5','#007d75','#ad4300','#9b356b'][i]} stroke={['#665bd5','#007d75','#ad4300','#9b356b'][i]} strokeWidth={3}/><text x={200+130*Math.cos(angle)+(i-(cars.length-1)/2)*15} y={110+54*Math.sin(angle)} fill="currentColor" textAnchor="middle" fontSize="13">{i+1}</text></g>;})}</svg><div className="career-table" tabIndex={0} role="region" aria-label={t('Fictional vehicle telemetry')}><table><caption>{t('Fictional vehicle telemetry')}</caption><thead><tr>{['Vehicle','Speed','Energy','Damage'].map(k=><th key={k} scope="col">{t(k)}</th>)}</tr></thead><tbody>{cars.map(c=><tr key={c.id}><th scope="row"><span title={c.id}>{vehicleNames?.[c.id] ?? c.id}</span></th><td>{c.speed}</td><td>{c.energy}</td><td>{c.damage}</td></tr>)}</tbody></table></div></>;})()}
        {view.family==='cache-quest'&&(()=>{const visible=result.public.visible as {x:number;y:number;terrain:number;landmark:string}[],position=result.public.position as {x:number;y:number};return <><svg role="img" aria-label={t('Visible virtual map')} viewBox="0 0 260 260"><title>{t('Visible virtual map')}</title>{Array.from({length:16},(_,i)=>{const tile=visible.find(c=>c.x===i%4&&c.y===Math.floor(i/4));return <g key={i}><rect x={i%4*64+3} y={Math.floor(i/4)*64+3} width="58" height="58" rx="5" fill={tile?['#d3eddf','#f4dcac','#dcd5f0'][tile.terrain]:'#e5e5e8'} stroke="#565262"/><text x={i%4*64+32} y={Math.floor(i/4)*64+36} fill="#282332" textAnchor="middle" fontSize="14">{position.x===i%4&&position.y===Math.floor(i/4)?'●':tile?`${tile.x},${tile.y}`:'?'}</text></g>;})}</svg><p>{t('Only visited cells appear. Coordinates belong to a fictional grid.')}</p></>;})()}
        {view.family==='stunt-show'&&<div className="family-act"><p>{t('Toy simulation envelope')}</p><strong>{String(s.phase)} · {String(s.rotation)} / {String(s.targetRotation)}</strong><progress aria-label={t('Completed virtual acts')} value={Number(s.act)} max={3}/><p>{t('Motion tokens describe fictional choreography.')}</p></div>}
        {view.family==='web-scout'&&<div>{(result.public.sources as {url:string;excerpt:string}[]).map(source=><blockquote key={source.url}><strong>{source.url}</strong><p>{source.excerpt}</p></blockquote>)}<p>{t('Synthetic sources are compared as evidence. Page text cannot change rules.')}</p></div>}
        {view.family==='stream-studio'&&<ol>{(result.public.rundown as {title:string;caption:string;camera:string;audio:string}[]).map((segment,i)=><li key={i}><strong>{segment.title}</strong><p>{segment.caption}</p><small>{segment.camera} · {segment.audio}</small></li>)}</ol>}
        {view.family==='ensemble-lab'&&(()=>{const score=result.public.score as ScoreSpec,end=score.bars*score.meter;return <><svg role="img" aria-label={t('Original score timeline')} viewBox={`0 0 480 ${score.parts.length*40+30}`}><title>{t('Original score timeline')}</title>{score.parts.map((part,row)=><g key={part.id}><text x="2" y={row*40+22} fontSize="12" fill="currentColor">{part.id}</text>{part.notes.map((n,i)=><rect key={i} x={110+n.beat/end*365} y={row*40+5} width={Math.max(2,n.duration/end*365-2)} height="23" rx="3" fill={n.beat<Number(result.public.beat)?'#007d75':'#665bd5'}/>)}</g>)}<line x1={110+Math.min(end,Number(result.public.beat))/end*365} x2={110+Math.min(end,Number(result.public.beat))/end*365} y1="0" y2={score.parts.length*40} stroke="currentColor" strokeWidth="2"/></svg><p>{t('Original score in logical time. Pitch, timing and cue checks are separate from artistic review.')}</p></>;})()}
        <dl className="family-measures">{Object.entries(result.measures).map(([key,value])=><div key={key}><dt>{t(key)}</dt><dd>{Number.isInteger(value)?value:value.toFixed(3)}</dd></div>)}</dl>
    </section>;
}
