import { useId } from 'react';
import Scene3D from '../engine/Scene3D';
import type { ModelObservation } from '../agents/contracts';
import type { WorldId } from '../runtime/garageWorlds';

export default function GarageScene({ observation: o, paused, variant = 'standard' }: { observation: ModelObservation; paused: boolean; variant?: 'standard' | 'constraints' | 'transfer' }) {
  const id = useId().replaceAll(':', ''), s = o.state, world = o.world as WorldId;
  if (['sports', 'outpost', 'scenario', 'space', 'rover'].includes(world)) return <Scene3D kind={world === 'rover' ? 'learner' : world as 'sports' | 'outpost' | 'scenario' | 'space'} paused={paused} label={`Agent world at tick ${o.tick}; position ${s.x}, ${s.y}.`} data={{ x: Number(s.x), y: Number(s.y), goalX: o.target?.[0] || 0, goalY: o.target?.[1] || 0, seed: Number(s.seed || 0), layout: Number(s.layout || 0), carrying: Number(s.carrying || 0), variant: variant === 'transfer' ? 2 : variant === 'constraints' ? 1 : 0, storm: Number(s.mode === 'storm'), progress: Number(s.progress || 0), vx: Number(s.vx || 0), vy: Number(s.vy || 0) }} />;
  const district = (s.district || {}) as Record<string, boolean>, labels = ['power', 'water', 'roads', 'supplies', 'comms'];
  const route = (s.missionRoute || []) as string[], scanned = (s.scanned || []) as number[];
  const description = world === 'survey' ? `Survey sites: ${scanned.map((v, i) => `${i}: ${v < 0 ? 'unknown' : v ? 'cache' : 'empty'}`).join('; ')}. Current site ${s.position}.` : world === 'community' ? `District: ${labels.map(k => `${k}: ${k === 'supplies' ? s.supplies : district[k] ? 'restored' : 'pending'}`).join('; ')}. Current role ${o.turn}.` : `Mission route ${route.join(', ')}. Completed ${s.progress} of ${route.length} directions.`;
  return <div className="garage-scene"><svg viewBox="0 0 600 330" role="img" aria-label={description}>
    <defs><linearGradient id={`${id}-sky`} x2="0" y2="1"><stop stopColor="#101e38" /><stop offset="1" stopColor="#203b4f" /></linearGradient><linearGradient id={`${id}-deck`} x2="0" y2="1"><stop stopColor="#253c50" /><stop offset="1" stopColor="#102236" /></linearGradient></defs>
    <rect width="600" height="330" rx="12" fill={`url(#${id}-sky)`} />
    {Array.from({ length: 24 }, (_, i) => <circle key={i} cx={18 + (i * 89) % 570} cy={12 + (i * 31) % 145} r={i % 3 ? 1 : 1.8} fill="#8ccbdd" opacity=".5" />)}
    <path d="M65 295 160 153 450 153 550 295Z" fill={`url(#${id}-deck)`} stroke="#6c93ad" />
    {[0,1,2,3,4].map(i => <path key={i} d={`M${82 + i * 106} 295 ${173 + i * 65} 153`} stroke="#4a6b83" opacity=".55" />)}
    {world === 'survey' ? scanned.map((v, i) => { const x = 76 + i * 88, active = i === Number(s.position); return <g key={i}><ellipse cx={x + 15} cy={244} rx="33" ry="11" fill="#050d1b" opacity=".8" /><path d={`M${x-15} 200 ${x+15} 182 ${x+40} 198 ${x+10} 216Z`} fill={v < 0 ? '#30455e' : v === 1 ? '#caab44' : '#426574'} stroke={active ? '#caff66' : '#91bacf'} /><path d={`M${x-15} 200v29l25 15v-28M${x+10} 216l30-18v30l-30 16`} fill={v < 0 ? '#1b2b43' : '#234650'} stroke="#7698b0" /><text x={x+10} y="208" textAnchor="middle" fill="#fff" fontSize="18">{v < 0 ? '?' : v === 1 ? '◆' : '·'}</text><text x={x+10} y="273" textAnchor="middle" fill="#e1edf3" fontSize="16">{i}</text>{active && <><path d={`M${x+10} 159v-23`} stroke="#caff66" strokeWidth="3" /><circle cx={x+10} cy="165" r="10" fill="#caff66" /><circle cx={x+10} cy="165" r="3" fill="#172331" /></>}</g>; }) : world === 'community' ? labels.map((key, i) => { const x = 130 + i * 81, done = key === 'supplies' ? Number(s.supplies) > 0 : district[key]; return <g key={key}><ellipse cx={x} cy="248" rx="32" ry="9" fill="#050d1b" /><path d={`M${x-23} 238v-57l23-14 23 14v57l-23 14Z`} fill={done ? '#294e50' : '#25384d'} stroke={done ? '#bfff83' : '#9fc1d4'} strokeWidth="2" /><path d={`M${x} 167v85M${x-23} 181l23 14 23-14`} fill="none" stroke="#85a8b9" /><circle cx={x} cy="212" r="11" fill={done ? '#caff66' : '#9bb1c1'} /><text x={x} y="218" textAnchor="middle" fill="#152238" fontSize="16">{done ? '✓' : i + 1}</text><text x={x} y="279" textAnchor="middle" fill="#dceaf2" fontSize="12">{key}</text></g>; }) : route.map((direction, i) => { const x = 114 + i * 72, done = i < Number(s.progress); return <g key={i}><ellipse cx={x} cy="249" rx="29" ry="9" fill="#040e1d" /><path d={`M${x-24} 222l24-14 24 14-24 14Z`} fill={done ? '#67954e' : '#344d65'} stroke={done ? '#caff66' : '#b8d9eb'} /><text x={x} y="200" textAnchor="middle" fill="#e3f0f6" fontSize="29">{direction === 'north' ? '↑' : direction === 'south' ? '↓' : '→'}</text><text x={x} y="276" textAnchor="middle" fill="#cbdde8" fontSize="14">{i+1}</text></g>; })}
    <text x="27" y="39" fill="#bcffdd" fontSize="12" letterSpacing="2">{world === 'survey' ? 'SURVEY / INFORMATION COST' : world === 'community' ? 'COMMUNITY / SHARED DEPENDENCIES' : 'SIGNAL MAZE / MISSION ROUTE'}</text><text x="27" y="64" fill="#e7f4fa" fontSize="18">{o.agent.id} · {o.tick}</text>
  </svg><p className="small garage-scene-description">{description}</p></div>;
}
