import { useEffect, useRef, useState } from 'react';
import Icon from '../components/Icon';
import Modal from '../components/Modal';
import { useStudio } from '../systems/StudioContext';
import { AGENT_IDS, isArena, workedPolicy, type ArenaKind } from '../games/rung4/models';
import { parsePolicy } from '../games/rung4/validation';
import { Select } from '../games/advanced/ui';
import { Notice } from '../games/shared';
import { clearDeviceToken, competitionStandings, deviceToken, loadOnlineConfig, onlineRequest, type OnlineConfig } from '../online/client';
import type { EntityType, OnlineSession, OnlineView } from '../online/types';
const names:Record<ArenaKind,string>={sports:'Sport Bot Arena',outpost:'Survival Agent Outpost',scenario:'Scenario Agent Dispatch',space:'Space Agent Rendezvous'};
const clanNames=['Copper Crew','Orbit Builders','Signal Squad','River Rangers','Circuit Circle','Blueprint Guild','Trail Team','Launch League'];
const arenaOptions=AGENT_IDS.map(value=>({value,label:names[value]}));
export default function Online({arena:requested}:{arena?:string}) {
  const {profile}=useStudio(),[session,setSession]=useState<OnlineSession|null>(null),[config,setConfig]=useState<OnlineConfig|null>(null),[token,setToken]=useState('');
  const [tab,setTab]=useState<EntityType>('room'),[mode,setMode]=useState('dispatch'),[arena,setArena]=useState<ArenaKind>(requested&&isArena(requested)?requested:'sports'),[clanName,setClanName]=useState(clanNames[0]),[clan,setClan]=useState(''),[code,setCode]=useState('');
  const [busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[confirmDelete,setConfirmDelete]=useState(false),alive=useRef(true),epoch=useRef(0),connected=session!==null;
  useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
  useEffect(()=>{if(!config||!token||!connected)return;const abort=new AbortController();let pending=false;
    const poll=async()=>{if(document.hidden||pending)return;pending=true;const revision=epoch.current;try{const result=await onlineRequest(config,token,{op:'list'},abort.signal);if(!abort.signal.aborted&&revision===epoch.current&&'actor'in result)setSession(result);}catch(error){if(!abort.signal.aborted)setNotice(error instanceof Error?error.message:'The connection was interrupted.');}finally{pending=false;}};
    const timer=setInterval(()=>{void poll();},2500);return()=>{clearInterval(timer);abort.abort();};
  // Keep the live poll running across snapshots rather than restarting its timer.
  },[config,token,connected]);
  const connect=async()=>{setBusy(true);setNotice('');try{const c=await loadOnlineConfig(),credential=deviceToken(profile.id);const result=await onlineRequest(c,credential,{op:'connect'});if(alive.current&&'actor'in result){setConfig(c);setToken(credential);setSession(result);}}catch(error){if(alive.current)setNotice(error instanceof Error?error.message:'Online connection failed.');}finally{if(alive.current)setBusy(false);}};
  const act=async(body:Record<string,unknown>)=>{if(!config||!token||busy)return;epoch.current++;setBusy(true);setNotice('');try{
    const result=await onlineRequest(config,token,body);if(!alive.current)return;
    if('deleted'in result){clearDeviceToken(profile.id);setToken('');setSession(null);setConfig(null);setConfirmDelete(false);setNotice('Online identity deleted. Your local games, classes, and progress are unchanged.');}
    else setSession('session'in result?result.session:result);
  }catch(error){if(alive.current){setNotice(error instanceof Error?error.message:'The online action failed.');try{const current=await onlineRequest(config,token,{op:'list'});if(alive.current&&'actor'in current)setSession(current);}catch{/* The next poll can reconnect. */}}}finally{if(alive.current)setBusy(false);}};
  const groups=session?.entities.filter(e=>e.type===tab)||[],clans=session?.entities.filter(e=>e.type==='clan')||[];
  return <><div className="page-heading"><div><span className="eyebrow">PLAY TOGETHER · TRAIN TOGETHER</span><h1>The online commons.</h1><p>Private invitations. Shared objectives. Server-evaluated agent competitions.</p></div><span className="quiet-pill"><Icon name="shield"/>{session?session.actor.name:'Optional online play'}</span></div>
    {!session?<section className="online-intro"><div><span className="eyebrow">YOUR NEXT TEAM STARTS HERE</span><h2>A room for the crew.</h2><p>Cooperate on Community Dispatch, compare controllers in Agent Duel, build an invite-only clan, or host a three-round Agent League.</p><p>Connecting creates a generated player name and a device credential for this local profile. Private group rosters, team signals, controller submissions, and competition results are stored by the online service. Offline progress stays on your device.</p><button className="btn primary" disabled={busy} onClick={()=>{void connect();}}><Icon name="gamepad"/>{busy?'Connecting…':'Connect online'}</button><a className="text-link" href="#/privacy">Read the online privacy details →</a></div><div className="online-feature-list"><article><Icon name="compass"/><h3>Cooperative dispatch</h3><p>2–4 players rotate turns through observation, a protected zone, and qualified response.</p></article><article><Icon name="code"/><h3>Agent duels</h3><p>Controllers face the same three seeded sports, survival, scenario, or space trials.</p></article><article><Icon name="trophy"/><h3>Clans and tournaments</h3><p>Invite-only clans of up to 20. Events for 2–16 players, with locked submissions and round standings.</p></article></div></section>:<>
      <div className="online-toolbar"><div className="button-row">{(['room','clan','tournament'] as EntityType[]).map(type=><button className={`btn ${tab===type?'primary':'secondary'}`} aria-pressed={tab===type} key={type} onClick={()=>setTab(type)}>{type==='room'?'Rooms':type==='clan'?'Clans':'Tournaments'}</button>)}</div><button className="btn secondary" onClick={()=>{setSession(null);setToken('');setNotice('Online session paused. Reconnect to return to your private groups.');}}>Disconnect</button></div>
      <section className="online-create"><div><h2>{tab==='room'?'Create a private room':tab==='clan'?'Create a clan':'Host an Agent League'}</h2>{tab==='room'&&<Select label="Room game" value={mode} options={[{value:'dispatch',label:'Community Dispatch · cooperative'},{value:'duel',label:'Agent Duel · competition'}]} onChange={setMode}/>}{(tab==='tournament'||tab==='room'&&mode==='duel')&&<Select label="Competition arena" value={arena} options={arenaOptions} onChange={v=>setArena(v as ArenaKind)}/>} {tab==='clan'&&<Select label="Clan name" value={clanName} options={clanNames.map(value=>({value,label:value}))} onChange={setClanName}/>}{tab==='tournament'&&clans.length>0&&<Select label="Clan association" value={clan} options={[{value:'',label:'Independent event'},...clans.map(c=>({value:c.id,label:c.name}))]} onChange={setClan}/>}
        <button className="btn primary" disabled={busy} onClick={()=>{void act({op:'create',type:tab,mode:tab==='tournament'?'duel':mode,arena,...(tab==='clan'?{name:clanName}:{}),...(tab==='tournament'&&clan?{clan}:{})});}}>{tab==='room'?'Create room':tab==='clan'?'Create clan':'Create tournament'}</button></div><div><h2>Join by invitation</h2><label className="invite-entry">12-character invitation code<input aria-label="Invitation code" autoComplete="off" maxLength={12} value={code} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,''))}/></label><button className="btn secondary" disabled={busy||code.length!==12} onClick={()=>{void act({op:'join',type:tab,code});}}>Join {tab}</button><p className="small muted">Only share a code with the people you want in the group. There is no public directory or person-to-person chat.</p></div></section>
      <div className="online-groups">{groups.map(entity=><PrivateGroup key={entity.id} entity={entity} actor={session.actor.id} busy={busy} onAction={act} onNotice={setNotice}/>)}</div>{!groups.length&&<div className="empty-state"><Icon name="compass"/><h2>Your first invitation is a click away.</h2><p>Create a group or enter a code from your team.</p></div>}
      <div className="online-account"><p>Rooms and events expire after one day; clans after 30 days. Device identities expire after 90 days. Leaving an active event closes it so its roster cannot change mid-competition.</p><button className="btn danger" onClick={()=>setConfirmDelete(true)}>Delete my online identity</button></div>
    </>}{notice&&<Notice>{notice}</Notice>}
    {confirmDelete&&<Modal title="Delete this online identity?" onClose={()=>setConfirmDelete(false)}><p>This leaves your private groups, removes your submissions and team signals, and deletes this profile’s online credential. Local game and class progress remains on this device.</p><div className="modal-actions"><button className="btn secondary" onClick={()=>setConfirmDelete(false)}>Keep online identity</button><button className="btn danger" disabled={busy} onClick={()=>{void act({op:'delete-device'});}}>Delete online identity</button></div></Modal>}
  </>;
}
function PrivateGroup({entity:e,actor,busy,onAction,onNotice}:{entity:OnlineView;actor:string;busy:boolean;onAction:(body:Record<string,unknown>)=>Promise<void>;onNotice:(notice:string)=>void}) {
  const {save}=useStudio(),[policy,setPolicy]=useState(()=>JSON.stringify({version:1,kind:e.arena,rules:workedPolicy(e.arena)},null,2)),[transfer,setTransfer]=useState('');
  const owner=e.owner===actor,me=e.members.find(m=>m.id===actor)!,active=e.status==='active',dispatch=e.type==='room'&&e.mode==='dispatch',competition=e.type==='tournament'||e.type==='room'&&e.mode==='duel';
  const action=(op:string,extra:Record<string,unknown>={})=>{void onAction({op,id:e.id,version:e.version,...extra});};
  const submit=()=>{try{const rules=parsePolicy(JSON.parse(policy),e.arena);action('submit',{rules});}catch(error){onNotice(error instanceof Error?error.message:'Use valid controller JSON.');}};
  const importFile=async(file?:File)=>{if(!file)return;try{if(file.size>12000)throw new Error('Choose a policy file smaller than 12 KB.');const rules=parsePolicy(JSON.parse(await file.text()),e.arena);setPolicy(JSON.stringify({version:1,kind:e.arena,rules},null,2));onNotice('Controller loaded. Inspect it before locking your submission.');}catch(error){onNotice(error instanceof Error?error.message:'Controller import failed.');}};
  const useSaved=()=>{const checkpoint=Object.entries(save.checkpoints).filter(([key])=>key.startsWith(e.arena+'/')).sort((a,b)=>b[1].updatedAt.localeCompare(a[1].updatedAt))[0];const model=checkpoint?.[1].state.model as {rules?:unknown}|undefined;try{const rules=parsePolicy({version:1,kind:e.arena,rules:model?.rules},e.arena);setPolicy(JSON.stringify({version:1,kind:e.arena,rules},null,2));onNotice('Your latest local controller is loaded.');}catch{onNotice('No saved controller for this arena yet. Build one in its training world or import a policy file.');}};
  return <article className="private-group" data-online-id={e.id} data-online-version={e.version}><header><div><span className="eyebrow">{e.type==='clan'?'PRIVATE CLAN':e.type==='tournament'?'THREE-ROUND LEAGUE':dispatch?'COOPERATIVE ROOM':'AGENT DUEL'}</span><h2>{e.name}</h2><p>{competition?names[e.arena]:dispatch?'Three neighborhood tasks, shared turn by turn.':'A private home for your team.'}</p></div><span className="quiet-pill">{e.status}</span></header>
    <div className="invite-code"><label>Invitation code<input aria-label={`${e.name} invitation code`} readOnly value={e.code} onFocus={event=>event.target.select()}/></label><button className="btn secondary" onClick={()=>{void navigator.clipboard?.writeText(e.code).then(()=>onNotice('Invitation copied. Share it with your team.'),()=>onNotice('Select the code to copy it manually.'));}}>Copy invitation</button></div>
    <ul className="online-roster" aria-label="Group members">{e.members.map(m=><li key={m.id}><span>{m.name}{m.id===actor?' · you':''}</span><strong>{m.id===e.owner?'Host':e.type==='clan'?'Member':m.ready?'Ready':'Preparing'}</strong></li>)}</ul>
    {e.type!=='clan'&&e.status==='lobby'&&<div className="button-row"><button className="btn secondary" disabled={busy} onClick={()=>action('ready')}>{me.ready?'Return to preparing':'Ready to play'}</button>{owner&&<button className="btn primary" disabled={busy||e.members.length<2||!e.members.every(m=>m.ready)} onClick={()=>action('start')}>Start event</button>}<p className="small muted">At least two players must be ready. The roster locks when the host starts.</p></div>}
    {dispatch&&active&&<section className="dispatch-board"><h3>Task {e.task+1}/3 · {['Observe the site','Confirm the protected zone','Dispatch qualified response'][e.phase]}</h3><p>Current turn: <strong>{e.members[e.turn].name}</strong></p><div className="button-row">{[['observe','Log observation'],['protect','Confirm protected zone'],['dispatch','Dispatch qualified response']].map(([value,label])=><button key={value} className="btn secondary" disabled={busy||e.members[e.turn].id!==actor} onClick={()=>action('dispatch',{action:value})}>{label}</button>)}</div><p className="small">This is an abstract coordination game; its actions do not contact emergency services or perform real hazardous work.</p></section>}
    {dispatch&&e.log.length>0&&<ol className="dispatch-log" aria-label="Team action log">{e.log.map((item,i)=><li key={i}>{item.name} · task {item.task+1} · {item.action} · {item.accepted?'Recorded':'Revise the sequence'}</li>)}</ol>}
    {dispatch&&e.status==='complete'&&<Notice tone="success">Team objective complete. Three sites received the full response sequence. Online play does not change local XP.</Notice>}
    {competition&&active&&!e.submitted.includes(actor)&&<section className="online-controller"><h3>Lock your controller</h3><p>Three shared seeds. Builder difficulty. One submission per player; results from other players are revealed after everyone submits.</p><label className="code-editor">Controller JSON<textarea aria-label="Competition controller" rows={10} value={policy} maxLength={12000} spellCheck={false} onChange={event=>setPolicy(event.target.value)}/></label><div className="button-row"><button className="btn secondary" onClick={useSaved}>Use saved local controller</button><label className="btn secondary import-button">Import controller<input aria-label="Import competition controller" type="file" accept=".json,application/json" onChange={event=>{void importFile(event.target.files?.[0]);event.target.value='';}}/></label><a className="btn secondary" href={`#/game/${e.arena}`}>Open training world</a><button className="btn primary" disabled={busy} onClick={submit}>Lock and evaluate controller</button></div></section>}
    {competition&&(active||e.status==='complete')&&<section><h3>{e.status==='complete'?'Final standings':'Submission board'}</h3><p>{e.submitted.length}/{e.members.length} controllers locked · server-selected seeds: {e.seeds.join(', ')}</p>{e.status==='complete'?<div className="standings-scroll" role="region" tabIndex={0} aria-label="Competition standings"><table><thead><tr><th>Player</th><th>Round 1</th><th>Round 2</th><th>Round 3</th><th>League points</th><th>Total ticks</th></tr></thead><tbody>{competitionStandings(e).map(row=><tr key={row.id}><th>{row.name}</th>{row.rounds.map((round,i)=><td key={i}>{round.score}/100 · {round.ticks} ticks</td>)}<td>{row.points}</td><td>{row.ticks}</td></tr>)}</tbody></table></div>:<ul className="online-roster">{e.members.map(m=><li key={m.id}>{m.name}<strong>{e.submitted.includes(m.id)?'Locked':'Waiting'}</strong></li>)}</ul>}<p className="small muted">Per round: highest model score wins, then fewer ticks. A sole round winner earns 3 league points; tied winners earn 1 each. No local XP is awarded.</p></section>}
    {e.status==='closed'&&<Notice>An active participant left. This event is closed; create a fresh event with the current team.</Notice>}
    <div className="team-signals"><span>Team signals</span>{[['ready','Ready'],['help','Need a hand'],['good-round','Good round']].map(([value,label])=><button className="btn secondary" key={value} disabled={busy} onClick={()=>action('signal',{signal:value})}>{label}</button>)}</div>{e.signals.length>0&&<p className="small muted">{e.signals.map(s=>`${e.members.find(m=>m.id===s.actor)?.name}: ${s.signal}`).join(' · ')}</p>}
    {owner&&e.members.length>1&&<div className="online-transfer"><Select label="Next group host" value={transfer} options={[{value:'',label:'Choose a member'},...e.members.filter(m=>m.id!==actor).map(m=>({value:m.id,label:m.name}))]} onChange={setTransfer}/><button className="btn secondary" disabled={busy||!transfer} onClick={()=>action('transfer',{member:transfer})}>Transfer host role</button></div>}
    <footer><span className="small muted">Expires {new Date(e.expiresAt).toLocaleDateString(save.settings.locale)}</span><button className="btn secondary" disabled={busy} onClick={()=>action('leave')}>Leave group</button></footer>
  </article>;
}
