import { games, gameById } from '../data/games';
import { useStudio } from '../systems/StudioContext';
import { WorldArt } from '../engine/Scene';
import GameHost from './GameHost';
import Icon from '../components/Icon';
export default function RetroLab({id,mission,practice}:{id?:string;mission?:number;practice?:boolean}){
 const{save,updateSettings}=useStudio();const game=id?gameById(id):undefined;
 return <section className={`retro-lab palette-${save.settings.labPalette}`}><header className="retro-header"><div><span className="eyebrow">BRAIN SWEAT LAB SYSTEM / 05</span><h1>Retro lab interface</h1><p>Choose a cartridge. Run a real world. Your same checkpoints and progress travel with you.</p></div><div className="retro-switches"><button className="btn secondary" aria-pressed={save.settings.labPalette==='green'} onClick={()=>updateSettings({labPalette:'green'})}>Green phosphor</button><button className="btn secondary" aria-pressed={save.settings.labPalette==='amber'} onClick={()=>updateSettings({labPalette:'amber'})}>Amber phosphor</button></div></header><div className="retro-deck"><span className="retro-led"/> <strong>{game?`CARTRIDGE: ${game.title}`:'SYSTEM READY · SELECT CARTRIDGE'}</strong>{game&&<><label className="sr-only" htmlFor="cartridge">Change cartridge</label><select id="cartridge" aria-label="Change cartridge" value={game.id} onChange={e=>{window.location.hash=`/lab/${e.target.value}`;}}>{games.map(g=><option value={g.id} key={g.id}>{g.title}</option>)}</select><a className="btn secondary" href={`#${game.route}${mission===undefined?'':`?mission=${mission+1}`}`}>Open in the studio</a><a className="text-link" href="#/lab">Eject cartridge</a></>}</div>{game?<div className="crt-frame"><div className="crt-screen"><GameHost key={`${game.id}-${save.difficulty}-${mission}`} embedded id={game.id} initialMission={mission} initialPractice={practice}/></div><div className="crt-controls"><span>POWER ●</span><span>LOCAL SAVE / ONLINE + OFFLINE</span><span>CRT-05</span></div></div>:<div className="cartridge-grid">{games.map((g,i)=><a className="cartridge" key={g.id} href={`#/lab/${g.id}`}><WorldArt kind={g.id}/><span className="cartridge-number">{String(i+1).padStart(2,'0')}</span><Icon name={g.icon} size={24}/><h2>{g.title}</h2><p>{g.category}</p><span>INSERT & RUN →</span></a>)}</div>}<p className="retro-footnote">Static CRT styling. Keyboard and touch controls. Reduced-motion and contrast settings remain available.</p></section>;
}
