import { useMissionState } from '../systems/MissionSession';
import { clamp, difficultyIndex, type GameProps } from '../data/types';
import { Action, Counter, GameLayout, Meter, Notice, Stat, Stats } from './shared';
export interface GardenPlant { type: number; moisture: number; health: number; growth: number; light: number }
export const plantTypes = [{ name: 'Leafy herb', light: 6, cost: 6 }, { name: 'Shade fern', light: 3, cost: 5 }, { name: 'Pollinator flower', light: 7, cost: 7 }];
export function gardenTurn(plant: GardenPlant, water: number, heat: number, drainage: boolean, mulch: boolean): GardenPlant {
  const moisture = clamp(plant.moisture + water * 18 - heat * (mulch ? 0.65 : 1) - plant.light * 1.5);
  const waterQuality = Math.max(0, 1 - Math.abs(moisture - 55) / 45); const lightQuality = Math.max(0, 1 - Math.abs(plant.light - plantTypes[plant.type].light) / 6);
  const stress = (moisture > 85 && !drainage ? 20 : 0) + (moisture < 20 ? 12 : 0);
  return { ...plant, moisture, health: clamp(plant.health + waterQuality * lightQuality * 8 - 4 - stress), growth: clamp(plant.growth + waterQuality * lightQuality * 12) };
}
const missions = ['The windowsill garden', 'Sun and shade', 'The water budget', 'Pollinator corner', 'The warm week', 'Drainage detective', 'The shared garden', 'The resilient garden'];
export default function BotanyGarden({ difficulty, mission, paused, onFinish }: GameProps) {
  const d = difficultyIndex(difficulty); const [plants, setPlants] = useMissionState<GardenPlant[]>('plants', []); const [cash, setCash] = useMissionState('cash', [28, 24, 22][d]);
  const [day, setDay] = useMissionState('day', 0); const [started, setStarted] = useMissionState('started', false); const [water, setWater] = useMissionState('water', [1, 1, 1]); const [reservoir, setReservoir] = useMissionState('reservoir', [28, 24, 20][d] - (mission === 2 ? 2 : 0)); const [drainage, setDrainage] = useMissionState('drainage', true); const [mulch, setMulch] = useMissionState('mulch', false); const [observed, setObserved] = useMissionState('observed', false); const [observations, setObservations] = useMissionState('observations', 0); const [notice, setNotice] = useMissionState('notice', 'Plant up to three pots. Match light to each plant and leave room in the budget for water-saving mulch.');
  const heat = [5, 9, 7, 12, 8, 6][(day + mission) % 6] + (mission === 4 ? 4 : 0); const usedWater = water.slice(0, plants.length).reduce((sum, v) => sum + v, 0);
  function advance() {
    const next = plants.map((p, i) => gardenTurn(p, water[i], heat, drainage, mulch)); setReservoir(reservoir - usedWater); setPlants(next); setObserved(false);
    if (day === 5) { const health = next.reduce((sum, p) => sum + p.health, 0) / next.length; const growth = next.reduce((sum, p) => sum + p.growth, 0) / next.length; const variety = new Set(next.map(p => p.type)).size; const score = Math.round(clamp(health * 0.55 + growth * 0.2 + Math.min(1, observations / 4) * 15 + variety / 3 * 10)); onFinish({ score, summary: `Your garden completed six days with ${Math.round(health)}% average health and ${reservoir - usedWater} water units remaining.`, lesson: 'Plants need suitable light, water, air around roots, and a growing medium. Observe moisture before watering; more water is not always better. Different plants have different needs. This uses fictional water units and simplified growth, not a real watering schedule or plant-identification tool.', metrics: { 'Average health': `${Math.round(health)}%`, 'Observations': observations, 'Plant variety': variety } }); }
    else { setDay(day + 1); setNotice('Day advanced. Check soil again before deciding how much water the next day needs.'); }
  }
  return <GameLayout kind="botany" title={missions[mission]} description="Plan a small container garden, inspect its soil, and respond to six days of changing conditions. Resource choices affect the next day’s health and growth." paused={paused} data={{ growth: plants.length ? plants.reduce((sum, p) => sum + p.growth, 0) / plants.length : 20, pots: plants.length }}>
    <Stats><Stat label="Garden budget" value={`$${cash}`} accent /><Stat label="Water units left" value={reservoir} /><Stat label="Observations" value={observations} /></Stats>
    {!started && <><div className="choice-grid">{plantTypes.map((plant, i) => <button key={plant.name} className="choice-btn" disabled={plants.length >= 3 || cash < plant.cost} onClick={() => { setPlants([...plants, { type: i, moisture: 55, health: 80, growth: 0, light: plant.light }]); setCash(cash - plant.cost); }}><strong>Plant {plant.name}</strong>${plant.cost} · simulated preferred light {plant.light} hours</button>)}</div><Action secondary disabled={cash < 3 || mulch} onClick={() => { setCash(cash - 3); setMulch(true); }}>Add mulch · $3</Action></>}
    {plants.map((plant, i) => <div className="plant-card" key={i}><h3>Pot {i + 1}: {plantTypes[plant.type].name}</h3><Meter label="Plant health" value={plant.health} /><Meter label="Growth" value={plant.growth} /><p>Soil moisture: {observed || !started ? `${Math.round(plant.moisture)}%` : 'Inspect soil to observe'}</p><label className="range-label"><span>Light hours<strong>{plant.light}</strong></span><input type="range" min="1" max="9" step="1" aria-label={`Light hours pot ${i + 1}`} value={plant.light} onChange={e => setPlants(plants.map((p, n) => n === i ? { ...p, light: Number(e.target.value) } : p))} /></label>{started && <Counter label={`Water pot ${i + 1}`} min={0} max={2} value={water[i]} onChange={value => setWater(water.map((v, n) => n === i ? value : v))} />}</div>)}
    <label className="setting-row"><div><strong>Container drainage</strong><span>Allow excess water to leave the pot.</span></div><input type="checkbox" checked={drainage} onChange={e => setDrainage(e.target.checked)} /></label>
    {started && <><Notice>Day {day + 1}/6 · drying weather index {heat}. The garden needs observation, not an automatic watering schedule.</Notice><div className="game-actions"><Action secondary disabled={observed} onClick={() => { setObserved(true); setObservations(observations + 1); setNotice('Soil observed. Aim for moderate moisture. A wet pot can need no added water today.'); }}>Inspect soil</Action><Action disabled={usedWater > reservoir} onClick={advance}>{day === 5 ? 'Review my garden' : 'Grow one day'}</Action></div>{usedWater > reservoir && <Notice tone="warning">Reduce watering to fit the remaining water budget. Advancing without water is always available.</Notice>}</>}
    {!started && <Action disabled={plants.length < 2} onClick={() => { setStarted(true); setNotice('Your garden is planted. Observe the soil, then choose water for each pot.'); }}>Start the growing week</Action>}<Notice>{notice}</Notice>
  </GameLayout>;
}
