import { useMissionState } from '../systems/MissionSession';
import { clamp, difficultyIndex, money, type GameProps } from '../data/types';
import { Action, GameLayout, Notice, Stat, Stats, StepDots } from './shared';

const roles = [
  { title: 'Community shop assistant', skills: ['Helped organize a club supply shelf.', 'Arrived on time for a volunteer event.', 'Explained a game calmly to a new player.'], description: 'Help customers find items, keep shelves organized, and communicate with the team.' },
  { title: 'Library event helper', skills: ['Helped organize a club supply shelf.', 'Explained a game calmly to a new player.', 'Worked with a group to set up chairs.'], description: 'Set up events, organize materials, and help visitors find their way.' },
  { title: 'Garden center assistant', skills: ['Kept a small plant-watering checklist.', 'Worked with a group to set up chairs.', 'Arrived on time for a volunteer event.'], description: 'Follow a plant-care checklist, keep paths clear, and ask questions when unsure.' },
  { title: 'Community design helper', skills: ['Made a simple poster for a club event.', 'Explained a game calmly to a new player.', 'Arrived on time for a volunteer event.'], description: 'Create clear signs, check details, and discuss revisions with the project lead.' },
  { title: 'Equipment desk helper', skills: ['Helped organize a club supply shelf.', 'Kept a small plant-watering checklist.', 'Explained a game calmly to a new player.'], description: 'Use checklists, organize safe supplies, and explain checkout rules.' },
];
const resume = ['Helped organize a club supply shelf.', 'Arrived on time for a volunteer event.', 'Explained a game calmly to a new player.', 'Worked with a group to set up chairs.', 'Kept a small plant-watering checklist.', 'Made a simple poster for a club event.', 'Claimed a certificate never earned.', 'Added someone else’s private phone number.'];
const shifts = [{ label: 'Monday · 4–8 pm', hours: 4, available: true }, { label: 'Tuesday · 9 am–1 pm', hours: 4, available: false }, { label: 'Wednesday · 4–8 pm', hours: 4, available: true }, { label: 'Thursday · 10 am–2 pm', hours: 4, available: false }, { label: 'Saturday · 10 am–2 pm', hours: 4, available: true }, { label: 'Sunday · 4–8 pm', hours: 4, available: false }];
const interview = [
  [{ text: 'Can you tell me about experience that could help here?', options: [{ reply: 'I’m new to paid work, but I’ve practiced organizing and helping people. I can learn your process.', score: 100, response: 'That is clear and honest. Let’s talk about what the role needs.' }, { reply: 'I can share a specific volunteer example and ask what training is available.', score: 100, response: 'A concrete example and a training question give us a useful starting point.' }, { reply: 'I have every skill already, even the ones I haven’t tried.', score: 20, response: 'Let’s keep it accurate. It is okay to be new and willing to learn.' }] }, { text: 'What would you do if you made a mistake on a task?', options: [{ reply: 'Tell the lead, explain what happened, and ask how to correct it.', score: 100, response: 'Early communication gives the team a chance to fix it safely.' }, { reply: 'Pause the task if it might affect safety and ask for help.', score: 100, response: 'A thoughtful pause can protect people and the work.' }, { reply: 'Hide it and hope nobody notices.', score: 20, response: 'Hiding it makes the problem harder to resolve. Ask for help early.' }] }],
];
export default function CareerForge({ difficulty, mission, paused, onFinish }: GameProps) {
  const d = difficultyIndex(difficulty); const role = roles[mission]; const wage = [15, 17, 20][d] + mission; const [stage, setStage] = useMissionState('stage', 0); const [selected, setSelected] = useMissionState<string[]>('selected', []); const [booked, setBooked] = useMissionState<number[]>('booked', []); const [conversation, setConversation] = useMissionState('conversation', 0); const [interviewScore, setInterviewScore] = useMissionState('interviewScore', 0); const [feedback, setFeedback] = useMissionState('feedback', ''); const [waiting, setWaiting] = useMissionState('waiting', false);
  const hours = booked.reduce((sum, i) => sum + shifts[i].hours, 0); const validHours = booked.filter(i => shifts[i].available).reduce((sum, i) => sum + shifts[i].hours, 0); const question = interview[0][conversation];
  function finish() { const relevance = selected.filter(s => role.skills.includes(s)).length / 3; const honesty = selected.some(s => resume.indexOf(s) >= 6) ? 0 : 1; const schedule = Math.min(1, validHours / [6, 8, 10][d]) * (hours ? validHours / hours : 0); const score = Math.round(clamp(relevance * 25 + honesty * 10 + schedule * 35 + interviewScore / 2 * 0.3)); onFinish({ score, summary: `Your fictional application includes ${selected.filter(s => role.skills.includes(s)).length} matching examples and ${validHours} available work hours.`, lesson: 'A first-job resume can use honest volunteer and everyday examples. Clear availability protects your commitments. Ask about training and speak up when you need help. This game uses fictional wages and an adult applicant; real employment rules depend on age and location.', metrics: { 'Available hours': validHours, 'Illustrative gross pay': money(validHours * wage), 'Scheduling conflicts': booked.filter(i => !shifts[i].available).length } }); }
  return <GameLayout kind="career" title={role.title} description={`Help Alex, a fictional adult applicant, prepare for this role: ${role.description} Illustrative wage: ${money(wage)} per hour.`} paused={paused}>
    <Stats><Stat label="Application step" value={['Resume', 'Schedule', 'Interview'][stage]} icon="briefcase" accent /><Stat label="Scheduled hours" value={hours} /><Stat label="Illustrative pay" value={money(hours * wage)} /></Stats><StepDots total={3} current={stage} />
    {stage === 0 ? <><h3>Build a useful resume</h3><p>Choose up to three fictional experience cards that match this listing.</p><div className="resume-cards">{resume.map(card => <label className="resume-card" key={card}><input type="checkbox" checked={selected.includes(card)} disabled={selected.length >= 3 && !selected.includes(card)} onChange={() => setSelected(selected.includes(card) ? selected.filter(c => c !== card) : [...selected, card])} /><span>{card}</span></label>)}</div><div className="game-actions"><Action disabled={!selected.length} onClick={() => setStage(1)}>Plan availability</Action></div></> : stage === 1 ? <><h3>Build Alex’s weekly schedule</h3><Notice>Alex is available Monday and Wednesday after 4 pm, plus Saturday from 10 am to 2 pm. Other times have existing commitments.</Notice><div className="shift-grid">{shifts.map((shift, i) => <label key={i}><input type="checkbox" checked={booked.includes(i)} onChange={() => setBooked(booked.includes(i) ? booked.filter(j => j !== i) : [...booked, i])} /><span>{shift.label}<small style={{ display: 'block', color: '#bac8df' }}>{shift.hours} hours</small></span></label>)}</div><Notice tone={hours > validHours ? 'warning' : 'info'}>{hours > validHours ? 'Some selected shifts overlap existing commitments. Check the availability note and adjust.' : `Plan at least ${[6, 8, 10][d]} available hours. Gross pay is hours × hourly wage, before deductions.`}</Notice>{d === 2 && <p className="small muted">Practice example: an adult fictional schedule with 42 hours and a pretend overtime rule of 1.5× after 40 would pay {money(40 * wage + 2 * wage * 1.5)}. Actual overtime and youth-work rules vary; this mission does not apply them to minors.</p>}<div className="game-actions"><Action disabled={!booked.length} onClick={() => setStage(2)}>Meet the manager</Action><Action secondary onClick={() => setStage(0)}>Review resume</Action></div></> : <><div className="conversation"><span className="speaker">THE HIRING MANAGER</span><p>{question.text}</p>{feedback && <p className="reply">{feedback}</p>}</div>{waiting ? <div className="game-actions"><Action onClick={() => { if (conversation === 1) finish(); else { setConversation(1); setFeedback(''); setWaiting(false); } }}>{conversation === 1 ? 'Finish application' : 'Continue interview'}</Action></div> : <div className="dialogue-choices">{question.options.map(option => <button key={option.reply} onClick={() => { setInterviewScore(interviewScore + option.score); setFeedback(option.response); setWaiting(true); }}>{option.reply}</button>)}</div>}</>}
  </GameLayout>;
}
