import { useState } from 'react';
import { clamp, difficultyIndex, type GameProps } from '../data/types';
import { Action, GameLayout, Notice, Stat, Stats } from './shared';

interface Source { name: string; kind: string; text: string; relevance: boolean; quality: number }
interface Case { title: string; claim: string; verdict: 'supported' | 'misleading' | 'unproven'; reason: string; sources: Source[] }
const cases: Case[] = [
  { title: 'The giant garden mystery', claim: 'A viral post says a local student grew a three-meter tomato in one week using a secret fertilizer.', verdict: 'misleading', reason: 'The original photographer identifies a tiny tomato model held close to the camera. The caption changed when the image was reposted. The dramatic photo does not support the new claim.', sources: [
    { name: 'Original photographer', kind: 'FIRSTHAND SOURCE', text: 'The original image caption: “My miniature tomato sculpture, photographed close to the lens.” It is dated two years before the viral post.', relevance: true, quality: 3 }, { name: 'Repost account', kind: 'VIRAL POST', text: 'The account sells the “secret” fertilizer but does not link to the student or an original photograph.', relevance: true, quality: 2 }, { name: 'Garden measurements', kind: 'DIRECT RECORD', text: 'The school garden record lists ordinary tomato plants. There is no three-meter tomato harvest in its dated photos.', relevance: true, quality: 3 }, { name: 'Comment thread', kind: 'POPULARITY', text: 'Thousands of people liked the post. Several comments say it feels possible.', relevance: false, quality: 0 }, { name: 'Weather report', kind: 'UNRELATED RECORD', text: 'The fictional town had a sunny week and a little rain.', relevance: false, quality: 0 }, { name: 'Seller testimonial', kind: 'ADVERTISEMENT', text: 'An anonymous buyer says the fertilizer is “amazing.” No measurements or photo dates are included.', relevance: false, quality: 0 },
  ] },
  { title: 'The closed bridge story', claim: 'A clip says the town’s only footbridge collapsed yesterday and all routes to the library are closed.', verdict: 'misleading', reason: 'The original clip is from a different town three years earlier. Today’s dated maintenance notice says only one entrance is closed, with an alternate path open.', sources: [
    { name: 'Original video', kind: 'ORIGINAL SOURCE', text: 'The uploader names a different town and dates the footage three years ago.', relevance: true, quality: 3 }, { name: 'Town maintenance notice', kind: 'PRIMARY DOCUMENT', text: 'Today’s notice: “West entrance closed for painting. East path remains open.” Includes a marked map.', relevance: true, quality: 3 }, { name: 'Library route map', kind: 'DIRECT RECORD', text: 'A current library notice shows the open east footpath and its temporary signs.', relevance: true, quality: 3 }, { name: 'Dramatic soundtrack', kind: 'PRESENTATION', text: 'The clip uses tense music and flashing captions.', relevance: false, quality: 0 }, { name: 'Share counter', kind: 'POPULARITY', text: 'The clip has been shared 12,000 times.', relevance: false, quality: 0 }, { name: 'Old tourist guide', kind: 'OUTDATED', text: 'A guide from five years ago shows the west entrance.', relevance: false, quality: 0 },
  ] },
  { title: 'The sleep gadget claim', claim: 'A fictional ad claims everyone who used its glowing wristband learned twice as fast because the band changed their brain.', verdict: 'unproven', reason: 'The small observation has no comparison group and changed sleep routines at the same time. It cannot isolate the wristband’s effect or justify a universal claim.', sources: [
    { name: 'Full observation report', kind: 'METHOD DETAILS', text: 'Twelve volunteers used the band and also moved bedtime earlier. There was no group without the band.', relevance: true, quality: 3 }, { name: 'Original author', kind: 'DIRECT CLARIFICATION', text: 'The author says the observation cannot tell whether the wristband caused the change.', relevance: true, quality: 3 }, { name: 'Advertisement fine print', kind: 'CLAIM SCOPE', text: 'The ad’s “everyone” comes from selected positive comments, not all participants.', relevance: true, quality: 2 }, { name: 'Influencer clip', kind: 'SPONSORED OPINION', text: 'A paid creator says the band looks cool and feels motivating.', relevance: false, quality: 0 }, { name: 'Package color', kind: 'UNRELATED DETAIL', text: 'The box is bright blue with silver lettering.', relevance: false, quality: 0 }, { name: 'Sales total', kind: 'POPULARITY', text: 'The seller says the product sold out.', relevance: false, quality: 0 },
  ] },
  { title: 'The refill station rumor', claim: 'A post says the community center added three free water refill stations this week.', verdict: 'supported', reason: 'The dated installation records and current center map agree on three stations. A photograph helps confirm the locations; multiple independent records support this modest claim.', sources: [
    { name: 'Installation record', kind: 'PRIMARY DOCUMENT', text: 'This week’s signed fictional maintenance log lists three completed refill stations.', relevance: true, quality: 3 }, { name: 'Current center map', kind: 'DIRECT RECORD', text: 'The current map marks the lobby, sports hall, and garden entrances as free refill points.', relevance: true, quality: 3 }, { name: 'Dated center photographs', kind: 'DIRECT OBSERVATION', text: 'Three dated photos show the installed stations and recognizable center signs.', relevance: true, quality: 3 }, { name: 'Old complaint', kind: 'OUTDATED CONTEXT', text: 'A comment from last year says there were no refill stations.', relevance: false, quality: 0 }, { name: 'Nearby shop ad', kind: 'UNRELATED', text: 'A shop advertises bottled drinks at a discount.', relevance: false, quality: 0 }, { name: 'Post reactions', kind: 'POPULARITY', text: 'Many visitors reacted with a thumbs-up.', relevance: false, quality: 0 },
  ] },
  { title: 'The too-perfect wildlife photo', claim: 'A post says a purple fox with glass wings was photographed in the town park yesterday.', verdict: 'misleading', reason: 'The original creator labels the image as AI-assisted fantasy artwork. A cropped repost removed that disclosure. Visual realism alone does not prove an event happened.', sources: [
    { name: 'Creator’s original gallery', kind: 'ORIGINAL SOURCE', text: 'The original image is labeled “AI-assisted fantasy fox concept.” The full image includes that credit.', relevance: true, quality: 3 }, { name: 'Full uncropped image', kind: 'MISSING CONTEXT', text: 'The cropped repost removed the fantasy-art label and original date.', relevance: true, quality: 3 }, { name: 'Park observation log', kind: 'DIRECT RECORD', text: 'The fictional park’s dated observations record ordinary wildlife and no matching sighting.', relevance: true, quality: 2 }, { name: 'Sharp-looking fur', kind: 'APPEARANCE', text: 'The fur looks detailed. An image can look detailed whether it is a photo or generated art.', relevance: false, quality: 0 }, { name: 'Excited comments', kind: 'OPINION', text: 'Viewers say they want the animal to be real.', relevance: false, quality: 0 }, { name: 'Repost count', kind: 'POPULARITY', text: 'The cropped image has many shares.', relevance: false, quality: 0 },
  ] },
];
export default function MediaDetective({ difficulty, mission, paused, onFinish }: GameProps) {
  const d = difficultyIndex(difficulty); const mystery = cases[mission]; const [tokens, setTokens] = useState([6, 5, 4][d]); const [opened, setOpened] = useState<number[]>([]); const [pinned, setPinned] = useState<number[]>([]); const [active, setActive] = useState<number | null>(null); const [notice, setNotice] = useState('');
  function open(index: number) { if (!opened.includes(index)) { if (tokens <= 0) { setNotice('Research tokens are used. Revisit what you found and build the strongest case you can.'); return; } setTokens(tokens - 1); setOpened([...opened, index]); } setActive(index); setNotice(''); }
  function verdict(value: Case['verdict']) { const relevant = pinned.filter(i => mystery.sources[i].relevance); const irrelevant = pinned.length - relevant.length; const evidence = clamp((relevant.length - irrelevant) / 3, 0, 1); const sourceQuality = relevant.reduce((sum, i) => sum + mystery.sources[i].quality, 0) / 9; const score = Math.round(clamp((value === mystery.verdict ? 45 : 0) + evidence * 40 + Math.min(1, sourceQuality) * 15)); onFinish({ score, summary: `You filed a ${value} verdict with ${relevant.length} useful evidence cards. ${value === mystery.verdict ? 'Your conclusion fits the evidence.' : 'The original sources suggest a different conclusion.'}`, lesson: `${mystery.reason} Popularity, a polished image, or a strong feeling are not a substitute for evidence. “Unproven” leaves room to learn more.`, metrics: { 'Relevant evidence': relevant.length, 'Sources checked': opened.length, 'Tokens left': tokens } }); }
  return <GameLayout kind="media" title={mystery.title} description="Investigate this fictional claim. Spend research tokens on sources, pin evidence that actually bears on the claim, and choose a verdict supported by your board." paused={paused}>
    <Stats><Stat label="Research tokens" value={tokens} icon="search" accent /><Stat label="Sources checked" value={`${opened.length}/6`} /><Stat label="Evidence pinned" value={pinned.length} /></Stats><div className="event-card"><span className="eyebrow">THE VIRAL CLAIM</span><h3>{mystery.claim}</h3></div><h3>Choose where to investigate</h3><div className="source-grid">{mystery.sources.map((source, i) => <button key={source.name} className="source-card" onClick={() => open(i)} disabled={tokens <= 0 && !opened.includes(i)}><span>{d === 0 ? source.kind : `SOURCE ${i + 1}`}</span><strong>{source.name}</strong><small>{opened.includes(i) ? 'Opened · revisit free' : 'Investigate · 1 token'}</small></button>)}</div>{active !== null && <div className="event-card"><span className="eyebrow">{mystery.sources[active].kind}</span><p>{mystery.sources[active].text}</p><div className="game-actions"><Action secondary onClick={() => setPinned(pinned.includes(active) ? pinned.filter(i => i !== active) : [...pinned, active])}>{pinned.includes(active) ? 'Remove from evidence board' : 'Pin to evidence board'}</Action></div></div>}{notice && <Notice tone="warning">{notice}</Notice>}<div className="evidence-board"><h3>Your evidence board</h3>{pinned.length ? pinned.map(i => <div className="evidence-entry" key={i}><span>{mystery.sources[i].text}</span><button aria-label={`Remove ${mystery.sources[i].name} from evidence board`} onClick={() => setPinned(pinned.filter(j => j !== i))}>Remove</button></div>) : <p>Pin useful discoveries here. You can remove a card if it does not help answer the claim.</p>}</div><div className="game-actions"><Action disabled={opened.length < 2} onClick={() => verdict('supported')}>Supported</Action><Action secondary disabled={opened.length < 2} onClick={() => verdict('misleading')}>Misleading</Action><Action secondary disabled={opened.length < 2} onClick={() => verdict('unproven')}>Unproven</Action></div><p className="small muted" style={{ marginTop: 14 }}>Open at least two sources before filing a verdict.</p>
  </GameLayout>;
}
