import { useMissionState } from '../systems/MissionSession';
import { difficultyIndex, money, clamp, type GameProps } from '../data/types';
import { Action, GameLayout, Notice, Stats, Stat, StepDots } from './shared';

const missions = [
  { title: 'Your first apartment', events: [['Bike repair', 'Your bicycle needs a replacement tire for the commute.', 45], ['Phone surprise', 'Your phone case broke. Repairing it costs less than replacing the phone.', 30], ['Birthday invite', 'A friend invites you out. You can celebrate without buying an expensive gift.', 25], ['Utility adjustment', 'A warmer week nudged up your electricity bill.', 40]] },
  { title: 'Roommate month', events: [['Bus pass missing', 'Your bus pass needs replacing.', 40], ['Shared supplies', 'The apartment is out of basic cleaning supplies.', 20], ['Movie night', 'Your roommate proposes a movie-and-snacks night.', 30], ['Unexpected fee', 'A bill has an extra fee. Check it before paying.', 35]] },
  { title: 'The rainy commute', events: [['Rain gear', 'Keeping dry on the commute needs a practical solution.', 35], ['Broken bag', 'A repair shop can fix your backpack.', 30], ['Ride change', 'One bus route is closed for maintenance.', 25], ['Small emergency', 'A needed household item has stopped working.', 60]] },
  { title: 'Subscription shuffle', events: [['Renewal notice', 'A yearly subscription renewal appears on the calendar.', 50], ['Work shoes', 'The old shoes need replacing for a fictional job.', 60], ['Group activity', 'Your friends plan a paid outing.', 35], ['Bank statement', 'A charge you do not recognize needs checking.', 40]] },
  { title: 'Save for something big', events: [['Repair first', 'A loose bicycle part needs a safe workshop repair.', 40], ['Community trip', 'A local event adds a travel cost.', 25], ['Gift decision', 'You want to thank someone who helped you.', 20], ['Month-end adjustment', 'The final utility bill is a little higher than planned.', 45]] },
] as const;
export default function MoneyMission({ difficulty, mission, onFinish, paused }: GameProps) {
  const d = difficultyIndex(difficulty); const gross = [1500, 2100, 2850][d] + mission * 100; const tax = [0, 0.1, 0.15][d]; const income = Math.round(gross * (1 - tax));
  const needs = { rent: [460, 660, 900][d], food: [180, 250, 330][d], phone: [30, 45, 65][d], transport: [70, 120, 170][d], utilities: [65, 100, 150][d] };
  const [budget, setBudget] = useMissionState<Record<string, number>>('budget', { ...needs, savings: [160, 190, 200][d], fun: [70, 100, 120][d] });
  const [phase, setPhase] = useMissionState<'budget' | 'month'>('phase', 'budget'); const [week, setWeek] = useMissionState('week', 0); const [cash, setCash] = useMissionState('cash', 0); const [bank, setBank] = useMissionState('bank', 0); const [debt, setDebt] = useMissionState('debt', 0); const [funLeft, setFunLeft] = useMissionState('funLeft', 0); const [log, setLog] = useMissionState<string[]>('log', []);
  const allocated = Object.values(budget).reduce((sum, v) => sum + v, 0); const event = missions[mission].events[week]; const cost = Math.round(event[2] * [1, 1.3, 1.6][d]);
  function respond(strategy: 'fund' | 'credit' | 'trim' | 'compare') {
    let nextCash = cash; let nextBank = bank; let nextDebt = debt; let nextFun = funLeft; let paid = cost; let text = '';
    if (strategy === 'credit') { nextDebt += Math.ceil(cost * 1.2); paid = 0; text = `Borrowed ${money(cost)}. In this simplified model, repayment is ${money(Math.ceil(cost * 1.2))}.`; }
    if (strategy === 'trim') { const reclaim = Math.min(cost, funLeft); nextFun -= reclaim; nextCash += reclaim; text = `Redirected ${money(reclaim)} from entertainment to the surprise.`; }
    if (strategy === 'compare') { paid = Math.round(cost * 0.6); text = `Compared options and asked for help. A practical alternative costs ${money(paid)}.`; }
    if (strategy === 'fund') text = `Used the cushion for ${money(cost)}. That is what emergency savings are for.`;
    if (strategy !== 'credit') { const cashUsed = Math.min(nextCash, paid); nextCash -= cashUsed; const rest = paid - cashUsed; const bankUsed = Math.min(nextBank, rest); nextBank -= bankUsed; if (rest > bankUsed) { nextDebt += Math.ceil((rest - bankUsed) * 1.2); text += ` The uncovered ${money(rest - bankUsed)} became simulated debt.`; } }
    const nextLog = [...log, `Week ${week + 1}: ${text}`]; setCash(nextCash); setBank(nextBank); setDebt(nextDebt); setFunLeft(nextFun); setLog(nextLog);
    if (week === 3) {
      const coverage = Object.entries(needs).reduce((sum, [key, target]) => sum + Math.min(1, budget[key] / target), 0) / 5;
      const cushion = Math.min(1, (nextCash + nextBank) / (income * 0.12)); const debtHealth = 1 - Math.min(1, nextDebt / (income * 0.2)); const score = Math.round(clamp(coverage * 55 + cushion * 25 + debtHealth * 20));
      onFinish({ score, summary: coverage < 1 ? 'Your month revealed a gap in the essential bills. Adjust those first, then try a new cushion.' : `Your essential bills are covered, with ${money(nextCash + nextBank)} left as a cushion.`, lesson: `A budget is a plan you can adjust. Income after the game’s ${Math.round(tax * 100)}% pretend withholding is ${money(income)}. Borrowing solved a short-term gap but added ${money(nextDebt)} to repay. Spending less than a needed bill does not make the bill disappear.`, metrics: { 'Saved cushion': money(nextCash + nextBank), 'Simulated debt': money(nextDebt), 'Needs covered': `${Math.round(coverage * 100)}%` } });
    } else setWeek(week + 1);
  }
  return <GameLayout kind="money" title={missions[mission].title} description={phase === 'budget' ? 'Give each dollar a job. Your essentials are paid from this plan before the month begins; the leftover money and savings handle surprises.' : 'Your essential spending is set. Choose how to handle each weekly surprise, then see what your plan leaves at the end of the month.'} data={{ balance: income ? (cash + bank) / income * 100 : 0 }} paused={paused}>
    <Stats><Stat label="Take-home pay" value={money(income)} icon="wallet" accent /><Stat label={phase === 'budget' ? 'Unallocated' : 'Available cushion'} value={money(phase === 'budget' ? income - allocated : cash + bank)} icon="shield" /><Stat label="Debt to repay" value={money(debt)} /></Stats>
    {phase === 'budget' ? <>{d > 0 && <Notice>Gross pay {money(gross)} minus {money(gross - income)} of fictional withholding. This is a game example, not a real tax rate.</Notice>}{Object.entries(budget).map(([key, value]) => <label className="range-label" key={key}><span><span>{({ rent: 'Rent', food: 'Food', phone: 'Phone', transport: 'Transportation', utilities: 'Utilities', savings: 'Emergency savings', fun: 'Entertainment' } as Record<string, string>)[key]}{key in needs && <small>Needed: {money(needs[key as keyof typeof needs])}</small>}</span><strong>{money(value)}</strong></span><input type="range" min="0" max={key in needs ? Math.ceil(needs[key as keyof typeof needs] * 1.5 / 5) * 5 : Math.floor(income / 2 / 5) * 5} step="5" value={value} aria-label={`Budget for ${key}`} onChange={e => setBudget({ ...budget, [key]: Number(e.target.value) })} /></label>)}{allocated > income && <Notice tone="warning">The plan is {money(allocated - income)} over your income. Move money between categories before starting.</Notice>}<div className="game-actions"><Action disabled={allocated > income} onClick={() => { setCash(income - allocated); setBank(budget.savings); setFunLeft(budget.fun); setPhase('month'); }}>Start the month</Action></div></> : <><StepDots total={4} current={week} /><div className="event-card"><span className="eyebrow">WEEK {week + 1} SURPRISE · {money(cost)}</span><h3>{event[0]}</h3><p>{event[1]}</p></div><div className="choice-grid"><button className="choice-btn" onClick={() => respond('fund')}><strong>Use my cushion</strong>Pay {money(cost)} from unallocated cash and savings.</button><button className="choice-btn" onClick={() => respond('compare')}><strong>Find another way</strong>Compare prices, repair, or ask for help. Spend {money(Math.round(cost * 0.6))}.</button><button className="choice-btn" onClick={() => respond('trim')}><strong>Trim entertainment</strong>Move up to {money(Math.min(funLeft, cost))} back into your cushion.</button><button className="choice-btn" onClick={() => respond('credit')}><strong>Borrow for now</strong>Repay {money(Math.ceil(cost * 1.2))} later in this simplified model.</button></div><Notice>Cash {money(cash)} + savings {money(bank)}. Entertainment left to redirect: {money(funLeft)}.</Notice><ul className="game-log">{log.map((item, i) => <li key={i}>{item}</li>)}</ul></>}
  </GameLayout>;
}
