import { useState } from 'react';
import { clamp, difficultyIndex, money, type GameProps } from '../data/types';
import { Action, GameLayout, Meter, Notice, Stat, Stats } from './shared';
import Icon from '../components/Icon';

interface PowerInput { solar: number; wind: number; sun: number; breeze: number; demand: number; stored: number; capacity: number; useBattery: boolean; gridEnabled: boolean; cash: number; efficiency: boolean }
export function powerTurn(input: PowerInput) {
  const demand = input.demand * (input.efficiency ? 0.8 : 1); const generated = input.solar * 2 * input.sun + input.wind * 3 * input.breeze;
  const batteryUsed = input.useBattery ? Math.min(input.stored, Math.max(0, demand - generated)) : 0;
  const deficit = Math.max(0, demand - generated - batteryUsed); const imported = input.gridEnabled ? Math.min(deficit, Math.max(0, input.cash) / 2) : 0;
  const delivered = Math.min(demand, generated + batteryUsed + imported); const charge = Math.min(Math.max(0, input.capacity - input.stored + batteryUsed), Math.max(0, generated - demand));
  return { demand, generated, batteryUsed, imported, delivered, stored: input.stored - batteryUsed + charge, cost: imported * 2, coverage: demand ? delivered / demand : 1, clean: delivered ? Math.min(1, (generated + batteryUsed) / delivered) : 0, charge };
}
const forecasts = [
  [{ sun: 1, wind: 0.7 }, { sun: 1.3, wind: 0.4 }, { sun: 0.2, wind: 1 }, { sun: 0, wind: 0.8 }, { sun: 0.6, wind: 0.3 }, { sun: 1.2, wind: 0.7 }],
  [{ sun: 0.6, wind: 1 }, { sun: 1.2, wind: 0.5 }, { sun: 1.4, wind: 0.2 }, { sun: 0, wind: 0.9 }, { sun: 0.4, wind: 1.1 }, { sun: 1, wind: 0.4 }],
  [{ sun: 1.2, wind: 0.3 }, { sun: 1.3, wind: 0.2 }, { sun: 0.3, wind: 0.8 }, { sun: 0, wind: 0.4 }, { sun: 0.2, wind: 1.1 }, { sun: 0.8, wind: 0.6 }],
  [{ sun: 0.3, wind: 1 }, { sun: 0.4, wind: 1.2 }, { sun: 1.2, wind: 0.5 }, { sun: 0, wind: 0.6 }, { sun: 1.4, wind: 0.2 }, { sun: 0.7, wind: 1 }],
  [{ sun: 1.1, wind: 0.6 }, { sun: 0.7, wind: 0.8 }, { sun: 0.2, wind: 0.3 }, { sun: 0, wind: 1.2 }, { sun: 1.3, wind: 0.7 }, { sun: 0.5, wind: 0.4 }],
];
export default function PowerGrid({ difficulty, mission, paused, onFinish }: GameProps) {
  const d = difficultyIndex(difficulty); const [turn, setTurn] = useState(0); const [cash, setCash] = useState([120, 108, 96][d]); const [solar, setSolar] = useState(0); const [wind, setWind] = useState(0); const [batteries, setBatteries] = useState(0); const [stored, setStored] = useState(0); const [efficiency, setEfficiency] = useState(false); const [gridEnabled, setGrid] = useState(true); const [useBattery, setUseBattery] = useState(true); const [coverage, setCoverage] = useState(0); const [history, setHistory] = useState<ReturnType<typeof powerTurn>[]>([]); const [log, setLog] = useState<string[]>([]);
  const forecast = forecasts[mission][turn]; const demand = [7, 8, 9][d] + (turn % 3) + (mission === 4 ? 1 : 0); const preview = powerTurn({ solar, wind, sun: forecast.sun, breeze: forecast.wind, demand, stored, capacity: batteries * 4, useBattery, gridEnabled, cash, efficiency });
  const buy = (kind: 'solar' | 'wind' | 'battery' | 'efficiency') => { const cost = { solar: 18, wind: 24, battery: 16, efficiency: 20 }[kind]; if (cash < cost) return; setCash(cash - cost); if (kind === 'solar') setSolar(solar + 1); else if (kind === 'wind') setWind(wind + 1); else if (kind === 'battery') setBatteries(batteries + 1); else setEfficiency(true); };
  function advance() {
    const nextCash = cash - preview.cost + preview.coverage * 16; const nextHistory = [...history, preview]; setCash(nextCash); setStored(preview.stored); setCoverage(preview.coverage); setHistory(nextHistory); setLog([...log, `Turn ${turn + 1}: delivered ${preview.delivered.toFixed(1)} / ${preview.demand.toFixed(1)} kWh · battery ${preview.batteryUsed.toFixed(1)} used, ${preview.charge.toFixed(1)} charged · grid cost ${money(preview.cost)} · town funding ${money(preview.coverage * 16)}.`]);
    if (turn === 5) { const average = nextHistory.reduce((sum, h) => sum + h.coverage, 0) / 6; const clean = nextHistory.reduce((sum, h) => sum + h.clean, 0) / 6; const score = Math.round(clamp(average * 70 + clean * 20 + (nextCash >= 0 ? 10 : 0))); onFinish({ score, summary: `Your town received ${Math.round(average * 100)}% of its energy needs across six weather turns.`, lesson: 'Solar output follows sunlight; wind output follows the breeze. Batteries store excess energy for a later turn, and efficiency lowers demand. Power is a rate, measured here in kW. Each turn represents one hour, so a 2 kW panel at full output supplies 2 kWh in that turn. A backup grid can help, but it costs resources.', metrics: { 'Demand served': `${Math.round(average * 100)}%`, 'Local clean share': `${Math.round(clean * 100)}%`, 'Build funds left': money(nextCash), 'Stored energy': `${preview.stored.toFixed(1)} kWh` } }); } else setTurn(turn + 1);
  }
  return <GameLayout kind="power" title={['Light up the first neighborhood', 'The windy waterfront', 'The long cloudy evening', 'The changeable forecast', 'Peak-demand challenge'][mission]} description="Build a small energy system and test it against six one-hour weather turns. Each turn earns town funding in proportion to how well you keep up with demand." data={{ solar, wind, lit: coverage >= 0.95, sun: forecast.sun }} sceneLabel={`Energy town with ${solar} solar panels, ${wind} turbines, and ${batteries} batteries. Last turn served ${Math.round(coverage * 100)} percent of demand.`} paused={paused}>
    <Stats><Stat label="Build funds" value={money(cash)} icon="wallet" accent /><Stat label="Forecast turn" value={`${turn + 1}/6`} icon="zap" /><Stat label="Battery" value={`${stored.toFixed(1)}/${batteries * 4} kWh`} /></Stats><div className="forecast">{forecasts[mission].map((weather, i) => <span key={i} className={i === turn ? 'current' : ''}><strong>Turn {i + 1}</strong>{i < turn ? <Icon name="check" size={19} /> : d === 2 && i > turn + 1 ? <Icon name="help" size={19} /> : <Icon name={weather.sun === 0 ? 'home' : weather.sun > 0.8 ? 'sparkles' : 'volume'} size={19} />}<small>{d === 2 && i > turn + 1 ? 'Unknown' : weather.sun === 0 ? 'Night' : weather.sun < 0.6 ? 'Cloudy' : 'Sunny'}</small></span>)}</div><Notice>Current sunlight: {Math.round(forecast.sun * 100)}% · wind: {Math.round(forecast.wind * 100)}% of each unit’s reference output. Demand: {preview.demand.toFixed(1)} kWh this hour.</Notice><div className="power-buys"><button disabled={cash < 18 || solar >= 10} onClick={() => buy('solar')}><strong>Solar panel · $18</strong><small>2 kW at full sun · owned: {solar}</small></button><button disabled={cash < 24 || wind >= 10} onClick={() => buy('wind')}><strong>Wind turbine · $24</strong><small>3 kW at reference breeze · owned: {wind}</small></button><button disabled={cash < 16 || batteries >= 8} onClick={() => buy('battery')}><strong>Battery · $16</strong><small>4 kWh storage · owned: {batteries}</small></button><button disabled={cash < 20 || efficiency} onClick={() => buy('efficiency')}><strong>Efficiency plan · $20</strong><small>{efficiency ? 'Active · 20% lower demand' : 'Lower demand by 20%'}</small></button></div><label className="setting-row"><div><strong>Use stored energy for shortages</strong><span>Otherwise keep the battery for a later turn.</span></div><input type="checkbox" checked={useBattery} onChange={e => setUseBattery(e.target.checked)} /></label><label className="setting-row"><div><strong>Backup grid connection</strong><span>Import missing energy at $2/kWh if funds allow.</span></div><input type="checkbox" checked={gridEnabled} onChange={e => setGrid(e.target.checked)} /></label><Meter label="Projected demand served" value={preview.coverage * 100} color="#ae9bff" /><p className="small muted">Local generation {preview.generated.toFixed(1)} kWh · battery contribution {preview.batteryUsed.toFixed(1)} kWh · grid import {preview.imported.toFixed(1)} kWh.</p><div className="game-actions"><Action onClick={advance}>{turn === 5 ? 'Run the final hour' : 'Run this weather turn'}</Action></div><ul className="game-log">{log.map((line, i) => <li key={i}>{line}</li>)}</ul>
  </GameLayout>;
}
