import { useState } from 'react';
import { clamp, difficultyIndex, type GameProps } from '../data/types';
import { Action, GameLayout, Notice, Stat, Stats } from './shared';
import Icon from '../components/Icon';

const places = [ { name: 'Start', icon: 'home' }, { name: 'Help phone', icon: 'message', item: 'Borrowed phone' }, { name: 'Bus stop', icon: 'calendar' }, { name: 'Park gate', icon: 'compass' }, { name: 'Water station', icon: 'heart', item: 'Water bottle' }, { name: 'Map desk', icon: 'compass', item: 'Route map' }, { name: 'Closed path', icon: 'shield', hazard: true }, { name: 'Open walkway', icon: 'home' }, { name: 'Bicycle desk', icon: 'wrench', item: 'Repair note' }, { name: 'Covered shelter', icon: 'shield' }, { name: 'Crossing', icon: 'compass' }, { name: 'Trusted help', icon: 'heart' } ];
const missionData = [
  { title: 'The missing phone', context: 'Your fictional character cannot find their phone after an outing. Reach the community help desk and make a safe contact plan.', items: ['Borrowed phone', 'Route map'] },
  { title: 'The flat bicycle tire', context: 'Your fictional bicycle has a flat tire. Find a safe walking route and a supervised repair contact.', items: ['Repair note', 'Route map'] },
  { title: 'The missed bus', context: 'Your fictional group missed a bus. Find the posted information and a trusted adult to arrange the next step.', items: ['Route map', 'Borrowed phone'] },
  { title: 'The sudden power outage', context: 'The fictional neighborhood’s lights went out. Follow open paths, stay away from electrical hazards, and locate trusted help.', items: ['Borrowed phone', 'Route map'] },
  { title: 'The changing weather', context: 'An outing’s weather forecast changed. Find a sheltered route and reach a trusted adult without taking a risky shortcut.', items: ['Water bottle', 'Route map'] },
];
const encounters: Record<number, { prompt: string; options: { text: string; points: number; note: string }[] }> = {
  2: { prompt: 'The bus display says your original ride has left. A stranger offers an unplanned ride.', options: [{ text: 'Use the posted schedule and contact a trusted adult through a known number.', points: 100, note: 'You checked a reliable local source and chose trusted help.' }, { text: 'Wait in the public supervised area and ask staff for the next safe option.', points: 100, note: 'A staffed public area and known information give you a safe next step.' }, { text: 'Give the stranger private details and leave without telling anyone.', points: 0, note: 'That creates avoidable risk. Stay in a public supervised place and contact a trusted adult.' }] },
  5: { prompt: 'The desk has a current route map and an old shortcut note with no date.', options: [{ text: 'Use the current marked map and check the open-path signs.', points: 100, note: 'You checked the date and matched the map to what is actually open.' }, { text: 'Ask the staffed desk to explain the safest open route.', points: 100, note: 'A clear question to trusted staff helps when the route is unfamiliar.' }, { text: 'Follow the undated shortcut through the closed path.', points: 10, note: 'An undated shortcut can miss current hazards. The open marked route is safer.' }] },
  8: { prompt: 'A bicycle at the desk has a flat tire. The repair area is supervised, and a walking route is open.', options: [{ text: 'Ask the trusted adult at the desk for supervised help or a safe walking plan.', points: 100, note: 'You used the available help instead of improvising a risky roadside repair.' }, { text: 'Walk the bicycle along the open route and arrange repair later.', points: 100, note: 'Walking can be a practical solution while a safe repair is arranged.' }, { text: 'Ride the damaged bicycle down the steep shortcut.', points: 0, note: 'A damaged bicycle and a steep shortcut are not a safe combination. Choose walking or supervised help.' }] },
  9: { prompt: 'A weather warning asks people to avoid the exposed shortcut. A staffed covered shelter is open.', options: [{ text: 'Stay in the staffed shelter and follow the local warning.', points: 100, note: 'You used a safe place and current information.' }, { text: 'Contact a trusted adult from the shelter and confirm the open route.', points: 100, note: 'You have shelter, trusted contact, and a checked next step.' }, { text: 'Ignore the warning and rush through the exposed shortcut.', points: 0, note: 'A warning is a reason to pause and take shelter, not to rush into exposure.' }] },
  10: { prompt: 'A crossing signal is not working during the outage. Staff can guide people to a nearby marked alternative.', options: [{ text: 'Ask staff for the safer marked crossing and stay with the group.', points: 100, note: 'A safer alternative beats guessing at an unfamiliar crossing.' }, { text: 'Pause in a safe place and ask a trusted adult to help plan the crossing.', points: 100, note: 'You can slow down when the usual signal is unavailable.' }, { text: 'Run across without checking because you are in a hurry.', points: 0, note: 'Hurrying does not remove the hazard. Use trusted help and a safe route.' }] },
  11: { prompt: 'You reach a known community help desk. What is your final contact plan?', options: [{ text: 'Explain the situation to trusted staff and contact my trusted adult through a known number.', points: 100, note: 'You found appropriate help and a practical way to reconnect.' }, { text: 'If there is immediate danger, move to safety and have a trusted adult or staff member contact emergency services.', points: 100, note: 'Immediate danger calls for urgent, appropriate help. Ordinary inconveniences can use a calm practical plan.' }, { text: 'Post my private details publicly and wait for strangers to answer.', points: 0, note: 'Publicly sharing private information is not needed to get safe local help.' }] },
};
export default function RealWorldRescue({ difficulty, mission, paused, onFinish }: GameProps) {
  const d = difficultyIndex(difficulty); const story = missionData[mission]; const capacity = [4, 3, 2][d]; const [position, setPosition] = useState(0); const [visited, setVisited] = useState([0]); const [bag, setBag] = useState<string[]>([]); const [handled, setHandled] = useState<number[]>([]); const [encounter, setEncounter] = useState<number | null>(null); const [points, setPoints] = useState(0); const [decisions, setDecisions] = useState(0); const [risks, setRisks] = useState(0); const [notice, setNotice] = useState('Move one map tile at a time. Useful resources can be collected at a desk or station.'); const [feedback, setFeedback] = useState(''); const [answered, setAnswered] = useState(false);
  const adjacent = (index: number) => Math.abs(index % 4 - position % 4) + Math.abs(Math.floor(index / 4) - Math.floor(position / 4)) === 1;
  function move(index: number) { if (!adjacent(index) || encounter !== null) return; if (places[index].hazard) { setRisks(risks + 1); setNotice('That path is closed for a safety reason. Follow an open route or ask trusted staff.'); return; } setPosition(index); setVisited([...new Set([...visited, index])]); setNotice(`${places[index].name}${places[index].item ? ' has a resource you can add to your kit.' : ' is on your route.'}`); if (encounters[index] && !handled.includes(index)) { setEncounter(index); setAnswered(false); setFeedback(''); } }
  function finish() { const useful = story.items.slice(0, d === 0 ? 1 : 2).filter(item => bag.includes(item)).length; const expected = d === 0 ? 1 : 2; const score = Math.round(clamp((decisions ? points / decisions : 0) * 0.6 + useful / expected * 25 + Math.max(0, 15 - risks * 3))); onFinish({ score, summary: `You reached trusted help, made ${decisions} practical decisions, and carried ${useful} useful resource${useful === 1 ? '' : 's'} for this situation.`, lesson: 'Pause, look for reliable information, choose an open safe route, and ask a trusted adult when you need help. Keep private details private. Immediate danger is a reason to get to safety and contact emergency services; a missed bus or lost item usually needs a calmer local plan.', metrics: { 'Safe-decision average': `${Math.round(decisions ? points / decisions : 0)}%`, 'Useful kit items': `${useful}/${expected}`, 'Map locations explored': visited.length } }); }
  return <GameLayout kind="rescue" title={story.title} description={story.context} paused={paused}>
    <Stats><Stat label="Locations explored" value={visited.length} icon="compass" accent /><Stat label="Kit capacity" value={`${bag.length}/${capacity}`} /><Stat label="Decisions made" value={decisions} /></Stats><div className="map-grid" aria-label="Adventure map">{places.map((place, i) => <button key={place.name} className={`${position === i ? 'current' : visited.includes(i) ? 'visited' : ''} ${place.hazard ? 'hazard' : ''}`} disabled={encounter !== null || (!adjacent(i) && i !== position)} aria-label={`${place.name}${position === i ? ', current location' : place.hazard ? ', closed path' : adjacent(i) ? ', adjacent' : ''}`} onClick={() => move(i)}><Icon name={place.icon} size={23} /><span>{place.name}</span></button>)}</div><h3>Your practical kit</h3><div className="inventory">{bag.length ? bag.map(item => <span key={item}><Icon name="check" size={13} />{item}<button className="icon-button" aria-label={`Leave ${item} at this staffed location`} style={{ width: 24, minWidth: 24, height: 24, border: 0, background: 'transparent' }} onClick={() => setBag(bag.filter(v => v !== item))}><Icon name="close" size={12} /></button></span>) : <p className="small muted">Your kit is empty.</p>}</div>{places[position].item && !bag.includes(places[position].item!) && <Action secondary disabled={bag.length >= capacity || encounter !== null} onClick={() => { setBag([...bag, places[position].item!]); setNotice('Resource added. Keep space for the things this situation actually needs.'); }}>Collect {places[position].item}</Action>}<Notice>{notice}</Notice>{d === 0 && <p className="small muted">Helpful kit item for this mission: {story.items[0]}. Older modes need both {story.items.join(' and ')}.</p>}{encounter !== null && <><div className="event-card"><span className="eyebrow">AT THE {places[encounter].name.toUpperCase()}</span><h3>{encounters[encounter].prompt}</h3></div>{!answered ? <div className="dialogue-choices">{encounters[encounter].options.map(option => <button key={option.text} onClick={() => { setPoints(points + option.points); setDecisions(decisions + 1); setFeedback(option.note); setAnswered(true); }}>{option.text}</button>)}</div> : <><Notice>{feedback}</Notice><Action onClick={() => { if (encounter === 11) finish(); else { setHandled([...handled, encounter]); setEncounter(null); setAnswered(false); } }}>{encounter === 11 ? 'Complete the rescue plan' : 'Continue exploring'}</Action></>}</>}
  </GameLayout>;
}
