import { useState } from 'react';
import { clamp, difficultyIndex, type GameProps } from '../data/types';
import { Action, GameLayout, Notice, Stat, Stats } from './shared';

type Bucket = 'safe' | 'suspicious' | 'verify';
interface Message { sender: string; subject: string; body: string; bucket: Bucket; clues: string[]; explanation: string }
export const messages: Message[] = [
  { sender: 'Prize Desk · prize-drop.example.invalid', subject: 'You won a console!', body: 'You were randomly selected! Pay $25 shipping in gift cards and send your account password in the next ten minutes to claim your prize.', bucket: 'suspicious', clues: ['Gift-card payment', 'Asks for a password', 'Rushes your decision'], explanation: 'Gift cards are hard to recover, passwords should stay private, and the deadline pressures you to skip checking. You did not enter this giveaway.' },
  { sender: 'After-school club · club.example.invalid', subject: 'Tomorrow’s room changed', body: 'The club is meeting in Room 4 tomorrow. This matches the notice your teacher gave you today. No links, payment, or personal information are requested.', bucket: 'safe', clues: [], explanation: 'The message matches an independently confirmed notice and asks for no private information. That context matters more than a familiar name alone.' },
  { sender: 'Delivery Update · parcel-rescue.example.invalid', subject: 'Your parcel is stuck', body: 'Your package will be destroyed tonight. Enter your full bank login at parcel-rescue.example.invalid so we can release it.', bucket: 'suspicious', clues: ['Asks for a password', 'Rushes your decision', 'Unexpected request'], explanation: 'A delivery service does not need your bank login. The threat and unfamiliar link are reasons to stop and use the service’s known website instead.' },
  { sender: 'Coach Riley · new number', subject: 'Can you help quickly?', body: 'Hi, it’s your coach. My phone broke. Please buy a gift card and send its code. Do not tell anyone; it is a surprise.', bucket: 'suspicious', clues: ['Gift-card payment', 'Wants secrecy', 'Unverified identity'], explanation: 'Impersonators borrow familiar names. A secret gift-card request from a new number needs independent verification, not a rushed payment.' },
  { sender: 'School helper · schedule.example.invalid', subject: 'Timetable update', body: 'A message says your class start time changed, but you have not seen a matching announcement. It asks you to open an unfamiliar attachment.', bucket: 'verify', clues: ['Unverified identity', 'Unexpected request'], explanation: 'There is not enough evidence to decide from this message alone. Ask a trusted adult or check the school’s usual channel before opening the attachment.' },
  { sender: 'Local shop · easy-jobs.example.invalid', subject: 'Earn $300 an hour from home', body: 'No experience needed. You must first send us $80 to unlock the work. We will mail a check; send part of it back to our agent.', bucket: 'suspicious', clues: ['Upfront payment', 'Too-good reward', 'Unexpected request'], explanation: 'Paying to unlock a job and sending money back from a check are serious warning signs. A check can appear available before a bank discovers it is invalid.' },
  { sender: 'Device message', subject: 'Security scan result', body: 'This pop-up says your device has 47 viruses. Call an unknown number and let a stranger remotely control your computer immediately.', bucket: 'suspicious', clues: ['Rushes your decision', 'Unverified identity', 'Unexpected request'], explanation: 'A webpage pop-up cannot prove this. Avoid its phone number and remote-access request. A trusted adult can help check the device using known security tools.' },
  { sender: 'Sam · known contact', subject: 'Saturday plan', body: 'Sam asks whether you want to play at the park. You already discussed it in person with Sam and your trusted adult. No private details are requested.', bucket: 'safe', clues: [], explanation: 'This ordinary message fits a plan already confirmed in person. Keep ordinary personal information private even in friendly messages.' },
  { sender: 'Support Team · account-check.example.invalid', subject: 'Keep your account open', body: 'Reply with the one-time security code you just received. Our support agent needs it to stop your account closing.', bucket: 'suspicious', clues: ['Asks for a security code', 'Rushes your decision', 'Unverified identity'], explanation: 'A one-time code can unlock your account. Keep it private and contact support using a known app or website you open yourself.' },
  { sender: 'Friend’s account', subject: 'Is this you in the video?', body: 'A friend sends a link to a new website with no explanation. The site preview says you must sign in again to watch.', bucket: 'verify', clues: ['Unexpected request', 'Unverified identity'], explanation: 'Your friend’s account might be compromised. Ask them another way, and avoid entering credentials into a site reached through an unexpected link.' },
  { sender: 'Game market · rare-items.example.invalid', subject: 'Secret unlimited coins', body: 'Install this unknown browser extension, turn off security warnings, and give it access to every website. Unlimited coins guaranteed.', bucket: 'suspicious', clues: ['Too-good reward', 'Unexpected request'], explanation: 'Disabling protection and granting broad access can expose your accounts. Use official game features and ask a trusted adult before installing unfamiliar software.' },
  { sender: 'Library desk · known contact', subject: 'Book reservation ready', body: 'The reservation number matches your printed library receipt. You can collect the book at the usual desk. No sign-in link is included.', bucket: 'safe', clues: [], explanation: 'The receipt and normal in-person collection provide independent context. You do not need to send payment or credentials in reply.' },
  { sender: 'Community group · new account', subject: 'Volunteer signup', body: 'A new account invites you to a familiar community event. It asks for a form with personal details, but the organizer has not confirmed the form.', bucket: 'verify', clues: ['Unverified identity', 'Unexpected request'], explanation: 'A real event name does not prove that a form is legitimate. Ask a trusted adult and contact the known organizer before sharing personal information.' },
  { sender: 'Payment alert · bank-copy.example.invalid', subject: 'Refund waiting', body: 'You are owed a refund. Give us your debit-card PIN and password so we can deposit it now. Do not contact your bank.', bucket: 'suspicious', clues: ['Asks for a password', 'Wants secrecy', 'Unexpected request'], explanation: 'A refund does not require your PIN or bank password. The request to avoid your bank is another reason to stop and use known official contact details.' },
  { sender: 'Class project · teacher’s usual channel', subject: 'Bring a reusable bottle', body: 'The note matches today’s classroom announcement. It asks you to bring your own water bottle for a supervised outing.', bucket: 'safe', clues: [], explanation: 'The usual channel and classroom announcement agree. There is no surprise request for private data or payment.' },
];
const clueOptions = ['Gift-card payment', 'Asks for a password', 'Asks for a security code', 'Rushes your decision', 'Wants secrecy', 'Unverified identity', 'Unexpected request', 'Upfront payment', 'Too-good reward', 'Has punctuation', 'Uses a greeting'];
export default function ScamShield({ difficulty, mission, paused, onFinish }: GameProps) {
  const d = difficultyIndex(difficulty); const count = [6, 7, 8][d]; const inbox = Array.from({ length: count }, (_, i) => messages[(mission * 3 + i * 2 + d) % messages.length]);
  const [index, setIndex] = useState(0); const [selected, setSelected] = useState<string[]>([]); const [review, setReview] = useState<{ bucket: Bucket; points: number } | null>(null); const [total, setTotal] = useState(0); const [correct, setCorrect] = useState(0); const [evidenceFound, setEvidence] = useState(0);
  const message = inbox[index]; const options = d === 0 ? [...new Set([...message.clues, 'Has punctuation', 'Uses a greeting'])] : clueOptions;
  function sort(bucket: Bucket) { const hits = selected.filter(c => message.clues.includes(c)).length; const extras = selected.filter(c => !message.clues.includes(c)).length; const evidence = message.clues.length ? clamp((hits - extras) / message.clues.length, 0, 1) : selected.length === 0 ? 1 : 0; const points = (bucket === message.bucket ? 60 : 0) + evidence * 40; setReview({ bucket, points }); setTotal(total + points); if (bucket === message.bucket) setCorrect(correct + 1); setEvidence(evidenceFound + hits); }
  function next() { if (index + 1 === count) { const score = Math.round(total / count); onFinish({ score, summary: `You sorted ${correct} of ${count} messages into a supported safety category and found ${evidenceFound} relevant warning signs.`, lesson: 'Pause before acting. Inspect the request, check the sender independently, and keep passwords, PINs, and one-time codes private. “Verify” is a strong choice when you do not yet have enough evidence. All messages and domains in this game are fictional.', metrics: { 'Messages handled': count, 'Supported classifications': correct, 'Warnings found': evidenceFound } }); } else { setIndex(index + 1); setSelected([]); setReview(null); } }
  return <GameLayout kind="scam" title={['The giveaway gauntlet', 'The familiar-name trap', 'The suspicious support desk', 'The busy inbox', 'The careful click'][mission]} description="An inbox is waiting for your investigation. Select the specific warning signs you find, then sort each message. You never need to open a link or enter a password." paused={paused}>
    <Stats><Stat label="Inbox message" value={`${index + 1}/${count}`} icon="message" accent /><Stat label="Well-supported sorts" value={correct} icon="shield" /><Stat label="Evidence found" value={evidenceFound} /></Stats><div className="message-card"><small>FROM: {message.sender}</small><h3>{message.subject}</h3><p>{message.body}</p></div><h3>Pin the evidence</h3><p className="small muted">Select warning signs. A safe message may have none.</p><div className="evidence-chips">{options.map(clue => <button key={clue} disabled={!!review} aria-pressed={selected.includes(clue)} className={selected.includes(clue) ? 'selected' : ''} onClick={() => setSelected(selected.includes(clue) ? selected.filter(c => c !== clue) : [...selected, clue])}>{clue}</button>)}</div>{!review ? <div className="choice-grid"><button className="choice-btn" onClick={() => sort('safe')}><strong>Safe in this context</strong>Independent details support it.</button><button className="choice-btn" onClick={() => sort('suspicious')}><strong>Suspicious</strong>Stop. Do not share or pay.</button><button className="choice-btn" onClick={() => sort('verify')}><strong>Verify independently</strong>Use a known contact or trusted adult.</button></div> : <><Notice tone={review.bucket === message.bucket ? 'success' : 'warning'}><strong>{review.bucket === message.bucket ? 'Supported by the clues. ' : 'Another approach is safer here. '}</strong>{message.explanation}</Notice><p className="small muted">Useful clues: {message.clues.length ? message.clues.join(' · ') : 'No warning signs in the given context'}. +{Math.round(review.points)} investigation points.</p><Action onClick={next}>{index + 1 === count ? 'Close the case' : 'Next inbox message'}</Action></>}
  </GameLayout>;
}
