import { useState } from 'react';
import { clamp, difficultyIndex, money, type GameProps } from '../data/types';
import { Action, Counter, GameLayout, Meter, Notice, Stat, Stats, StepDots } from './shared';

const trades = [ { name: 'Cleaning', material: 8, fair: 32, time: 2, icon: 'sparkles' }, { name: 'Yard care', material: 11, fair: 40, time: 2, icon: 'home' }, { name: 'Pet care', material: 4, fair: 24, time: 1, icon: 'heart' }, { name: 'Digital design', material: 3, fair: 45, time: 3, icon: 'code' }, { name: 'Car washing', material: 7, fair: 28, time: 1.5, icon: 'wrench' }, { name: 'Handmade goods', material: 12, fair: 38, time: 2.5, icon: 'store' } ];
const conditions = [ { name: 'Grand opening', demand: [3, 4, 3, 5, 4] }, { name: 'A neighborhood festival', demand: [4, 5, 2, 5, 3] }, { name: 'A quiet start', demand: [2, 3, 4, 4, 5] }, { name: 'Materials getting pricey', demand: [4, 3, 5, 3, 5] }, { name: 'Repeat customers', demand: [3, 3, 4, 5, 6] } ];
export function calculateBusinessDay(price: number, capacity: number, demand: number, fair: number, material: number, time: number, equipment: number, satisfaction: number, difficulty: number) {
  const affordableDemand = Math.max(0, Math.round(demand * Math.min(1.5, fair / Math.max(1, price)) * (0.65 + satisfaction / 200)));
  const timeLimit = [8, 7, 6][difficulty]; const jobs = Math.min(capacity, affordableDemand, Math.floor(timeLimit / (time * (equipment ? 0.7 : 1))));
  const revenue = jobs * price; const expenses = jobs * material + [8, 12, 16][difficulty]; const taxReserve = Math.max(0, Math.round((revenue - expenses) * [0, 0.1, 0.15][difficulty]));
  const reputationChange = price > fair * 1.5 ? -10 : jobs === 0 ? -5 : price <= fair * 1.15 ? 8 : 2;
  return { jobs, revenue, expenses, taxReserve, profit: revenue - expenses - taxReserve, reputationChange };
}
export default function SideHustle({ difficulty, mission, paused, onFinish }: GameProps) {
  const d = difficultyIndex(difficulty); const starting = [180, 150, 120][d]; const [tradeIndex, setTradeIndex] = useState(0); const trade = trades[tradeIndex]; const [started, setStarted] = useState(false); const [day, setDay] = useState(0); const [cash, setCash] = useState(starting); const [price, setPrice] = useState(32); const [capacity, setCapacity] = useState(3); const [equipment, setEquipment] = useState(0); const [satisfaction, setSatisfaction] = useState(70); const [totalRevenue, setRevenue] = useState(0); const [totalExpenses, setExpenses] = useState(0); const [taxes, setTaxes] = useState(0); const [served, setServed] = useState(0); const [log, setLog] = useState<string[]>([]);
  const material = trade.material + (mission === 3 ? d + 3 : d); const demand = conditions[mission].demand[day]; const estimate = calculateBusinessDay(price, capacity, demand, trade.fair, material, trade.time, equipment, satisfaction, d); const reserve = capacity * material + [8, 12, 16][d];
  function runDay(close = false) {
    const outcome = close ? { jobs: 0, revenue: 0, expenses: 0, taxReserve: 0, profit: 0, reputationChange: 0 } : estimate;
    const nextCash = cash + outcome.profit; const nextSatisfaction = clamp(satisfaction + outcome.reputationChange); const nextServed = served + outcome.jobs;
    const nextRevenue = totalRevenue + outcome.revenue; const nextExpenses = totalExpenses + outcome.expenses; const nextTax = taxes + outcome.taxReserve;
    setCash(nextCash); setSatisfaction(nextSatisfaction); setServed(nextServed); setRevenue(nextRevenue); setExpenses(nextExpenses); setTaxes(nextTax); setLog([...log, `Day ${day + 1}: ${outcome.jobs} customers · revenue ${money(outcome.revenue)} · materials & daily costs ${money(outcome.expenses)} · tax reserve ${money(outcome.taxReserve)} · profit ${money(outcome.profit)}.`]);
    if (day === 4) { const net = nextRevenue - nextExpenses - nextTax - equipment * 60; const score = Math.round(clamp(Math.min(1, Math.max(0, net) / [140, 140, 115][d]) * 45 + nextSatisfaction * 0.3 + Math.min(1, nextServed / 10) * 25)); onFinish({ score, summary: `Your ${trade.name.toLowerCase()} business served ${nextServed} customers and kept ${money(net)} after costs, upgrades, and the pretend tax reserve.`, lesson: 'A sustainable estimate includes materials, overhead, your time, and a reserve for obligations. More customers are useful only when you can serve them well. A fair price and a time-saving upgrade are different strategies worth trying.', metrics: { Revenue: money(nextRevenue), 'Net profit': money(net), 'Customer satisfaction': `${nextSatisfaction}%`, 'Tax reserve': money(nextTax) } }); } else setDay(day + 1);
  }
  return <GameLayout kind="hustle" title={conditions[mission].name} description="You have five business days. Set a price that covers your costs, decide how much work fits in a day, and use customer feedback to improve." data={{ profit: totalRevenue - totalExpenses }} paused={paused}>
    <Stats><Stat label="Business cash" value={money(cash)} icon="wallet" accent /><Stat label="Customers served" value={served} icon="store" /><Stat label="Day" value={`${day + 1}/5`} /></Stats><StepDots total={5} current={day} />
    {!started ? <><h3>Choose your tiny business</h3><div className="choice-grid">{trades.map((item, i) => <button key={item.name} className={`choice-btn ${i === tradeIndex ? 'selected' : ''}`} aria-pressed={i === tradeIndex} onClick={() => { setTradeIndex(i); setPrice(item.fair); }}><strong>{item.name}</strong>{money(item.material + d)} materials · {item.time} hours/job</button>)}</div><Notice>This is a fictional simulation. Real work for young people needs a trusted adult’s help and appropriate safety.</Notice><Action onClick={() => setStarted(true)}>Open for business</Action></> : <><Meter label="Customer satisfaction" value={satisfaction} color="#ffbf70" /><div className="event-card"><span className="eyebrow">DAY {day + 1} · {demand} POTENTIAL CUSTOMERS</span><h3>What will today’s estimate look like?</h3><p>Local reference price: {money(trade.fair)}. Materials per job: {money(material)}. Daily overhead: {money([8, 12, 16][d])}.</p></div><Counter label="Price per job" value={price} min={10} max={90} step={2} onChange={setPrice} /><Counter label="Booking capacity" value={capacity} min={1} max={6} onChange={setCapacity} /><Notice>At this price and pace: about {estimate.jobs} bookings, {money(estimate.revenue)} revenue, and {money(estimate.profit)} profit after costs and the game’s tax reserve.</Notice><div className="game-actions"><Action disabled={cash < reserve} onClick={() => runDay()}>{day === 4 ? 'Finish the workweek' : 'Run this business day'}</Action><Action secondary disabled={equipment > 0 || cash < 60} onClick={() => { setCash(cash - 60); setEquipment(1); }}>{equipment ? 'Equipment upgraded' : 'Upgrade tools · $60'}</Action><Action secondary onClick={() => runDay(true)}>Close today and regroup</Action></div>{cash < reserve && <Notice tone="warning">This capacity needs {money(reserve)} available for supplies. Reduce bookings before taking more work.</Notice>}<ul className="game-log">{log.map((item, i) => <li key={i}>{item}</li>)}</ul></>}
  </GameLayout>;
}
