import { useState } from 'react';
import { clamp, difficultyIndex, type GameProps } from '../data/types';
import { Action, GameLayout, Meter, Notice, Stat, Stats, StepDots } from './shared';

interface Reply { text: string; respect: number; calm: number; trust: number; reaction: string }
interface Situation { title: string; person: string; context: string; need: string; prompts: string[]; options: Reply[][] }
const situations: Situation[] = [
  { title: 'The borrowed controller', person: 'JAMIE · YOUR FRIEND', context: 'A friend borrowed your game controller and has not returned it. You want it back without turning the conversation into a fight.', need: 'Jamie forgot it at a relative’s house and feels embarrassed. They can bring it back tomorrow.', prompts: ['I thought you didn’t mind me keeping it a little longer.', 'I don’t have it here today. Are you mad at me?', 'I can bring it tomorrow. Can we work this out?'], options: [
    [{ text: 'I want it back. Let’s agree on a time that works.', respect: 100, calm: 6, trust: 8, reaction: 'A clear request gives Jamie something specific to respond to.' }, { text: 'I like sharing with you, and I need my controller for tonight. Where is it now?', respect: 100, calm: 5, trust: 10, reaction: 'Jamie hears both the friendship and the need.' }, { text: 'You always ruin everything. I’m posting about you.', respect: 15, calm: -12, trust: -15, reaction: 'Jamie becomes defensive. You can still reset with a more specific request.' }],
    [{ text: 'I’m frustrated, and I can wait until tomorrow if we make a plan.', respect: 100, calm: 8, trust: 8, reaction: 'You name the feeling and the boundary without blaming.' }, { text: 'Tell me what happened. Then let’s figure out the return.', respect: 100, calm: 9, trust: 10, reaction: 'The explanation makes a practical next step easier.' }, { text: 'Forget it. I’ll never say what I need again.', respect: 30, calm: -4, trust: -3, reaction: 'Your need is still important. A direct or warm boundary can both work.' }],
    [{ text: 'Tomorrow works. Please ask before keeping it longer next time.', respect: 100, calm: 8, trust: 8, reaction: 'You found a concrete agreement and a future boundary.' }, { text: 'Thanks. I’ll check in tomorrow, and we can plan another game night later.', respect: 100, calm: 8, trust: 10, reaction: 'The agreement leaves room for the friendship to continue.' }, { text: 'You owe me anything I ask for now.', respect: 20, calm: -10, trust: -12, reaction: 'A demand for unlimited favors does not solve the original issue.' }],
  ] },
  { title: 'The uneven team project', person: 'ROWAN · YOUR TEAMMATE', context: 'You and Rowan are building a club display. You have done most of the work and want a fair plan.', need: 'Rowan is unsure which task to start and would do better with one clear responsibility.', prompts: ['I didn’t know which part you wanted me to do.', 'I’m worried I’ll get it wrong.', 'Can we split the work into smaller parts?'], options: [
    [{ text: 'I need the work to be shared. Can you take the labels while I finish the layout?', respect: 100, calm: 7, trust: 9, reaction: 'A specific division turns a vague conflict into a task plan.' }, { text: 'Let’s list what is left, then each choose a part.', respect: 100, calm: 8, trust: 9, reaction: 'Rowan has a clear way to contribute.' }, { text: 'I’ll do everything and tell everyone you’re useless.', respect: 15, calm: -10, trust: -15, reaction: 'That escalates the conflict and leaves the work unshared.' }],
    [{ text: 'We can check your first label together, then you can finish the rest.', respect: 100, calm: 8, trust: 10, reaction: 'A small check-in makes the task less overwhelming.' }, { text: 'What instructions would help you begin?', respect: 100, calm: 9, trust: 10, reaction: 'Rowan explains what is unclear.' }, { text: 'Just do it. Questions are annoying.', respect: 20, calm: -8, trust: -12, reaction: 'Questions can prevent errors. You can make room for them.' }],
    [{ text: 'Yes. Let’s agree on a finish time and ask for help if something is unclear.', respect: 100, calm: 8, trust: 9, reaction: 'The team now has owners, a deadline, and a way to ask questions.' }, { text: 'I’ll keep my part manageable too. We can check in after ten minutes.', respect: 100, calm: 8, trust: 9, reaction: 'A realistic plan supports both people.' }, { text: 'No. You should have read my mind.', respect: 10, calm: -10, trust: -10, reaction: 'Mind reading is not a workable task plan.' }],
  ] },
  { title: 'Asking a supervisor for help', person: 'MORGAN · THE SUPERVISOR', context: 'A fictional volunteer task is unfamiliar. You want to ask for help and protect everyone’s safety.', need: 'Morgan can demonstrate the process and would rather hear a question than see a risky guess.', prompts: ['How is the setup going?', 'Which part is unclear?', 'Would a demonstration help?'], options: [
    [{ text: 'I need a demonstration before I continue with this unfamiliar task.', respect: 100, calm: 7, trust: 10, reaction: 'You clearly identify a need before taking a risk.' }, { text: 'I’ve finished the safe preparation. Could you walk me through the next part?', respect: 100, calm: 7, trust: 10, reaction: 'Morgan can see what is done and where help is needed.' }, { text: 'It’s all fine. I’ll guess the dangerous part.', respect: 10, calm: -6, trust: -12, reaction: 'Guessing at a safety-sensitive step is avoidable. You can pause and ask.' }],
    [{ text: 'I’m unsure about this step. Could you show it once and let me repeat the instructions?', respect: 100, calm: 9, trust: 10, reaction: 'A specific question helps Morgan give useful guidance.' }, { text: 'Could we check the written instructions together?', respect: 100, calm: 8, trust: 10, reaction: 'Checking the same instructions reduces misunderstanding.' }, { text: 'Everything. And it’s your fault.', respect: 20, calm: -10, trust: -10, reaction: 'A specific question is more useful than blaming.' }],
    [{ text: 'Yes, thanks. I’ll explain it back before continuing.', respect: 100, calm: 8, trust: 9, reaction: 'Checking understanding supports a safe next step.' }, { text: 'Yes. If it still feels unsafe, I’ll stop and ask again.', respect: 100, calm: 8, trust: 9, reaction: 'The plan includes an appropriate safety boundary.' }, { text: 'No, I’ll rush so it looks finished.', respect: 15, calm: -8, trust: -10, reaction: 'Looking finished is not the same as doing the task safely.' }],
  ] },
  { title: 'A frustrated visitor', person: 'CASEY · A VISITOR', context: 'A visitor at a fictional community event is upset about a delayed start. You are helping at the information desk.', need: 'Casey needs a clear update and a place to wait. You can explain the delay without promising something you cannot control.', prompts: ['We’ve been waiting forever. What is happening?', 'Can you guarantee it starts in five minutes?', 'What can we do while we wait?'], options: [
    [{ text: 'I hear that the wait is frustrating. I can check the current update.', respect: 100, calm: 8, trust: 10, reaction: 'You acknowledge the feeling and offer a concrete action.' }, { text: 'The team is checking the room. I can share what is confirmed.', respect: 100, calm: 7, trust: 9, reaction: 'Facts are useful when people feel uncertain.' }, { text: 'Stop complaining or leave.', respect: 20, calm: -12, trust: -15, reaction: 'That escalates the exchange. A firm, respectful explanation can work better.' }],
    [{ text: 'I can’t guarantee a time yet. I’ll ask the lead for the next update.', respect: 100, calm: 7, trust: 10, reaction: 'Honesty avoids adding a promise you cannot keep.' }, { text: 'The confirmed update is still a delay. Would you like the waiting-area directions?', respect: 100, calm: 8, trust: 9, reaction: 'You offer a practical option within your role.' }, { text: 'Sure, I guarantee it, even though I don’t know.', respect: 15, calm: -4, trust: -12, reaction: 'An unsupported promise can make the next delay worse.' }],
    [{ text: 'There’s a seated waiting area and a notice board. I can show you.', respect: 100, calm: 9, trust: 10, reaction: 'You turn the conversation into a useful next step.' }, { text: 'We can check whether another activity is ready. Let me ask the lead.', respect: 100, calm: 8, trust: 10, reaction: 'You offer help without inventing information.' }, { text: 'I’ll ignore you until you stop being upset.', respect: 15, calm: -8, trust: -12, reaction: 'Avoiding the question does not improve the situation.' }],
  ] },
  { title: 'A noisy online disagreement', person: 'TAYLOR · A GAME GROUP MEMBER', context: 'A fictional private game group disagrees about a rule. You can explain your view, set a boundary, or step away.', need: 'Taylor misunderstood the rule and the chat tone. A clear explanation or a respectful pause can both help.', prompts: ['That rule is unfair. You just want to win.', 'Everyone is typing at once. This is getting heated.', 'Can we agree on what happens next?'], options: [
    [{ text: 'I read the rule differently. Let’s look at the same wording.', respect: 100, calm: 8, trust: 8, reaction: 'A shared reference moves the discussion away from assumptions.' }, { text: 'I’m happy to explain, and I want us to keep personal insults out of it.', respect: 100, calm: 8, trust: 8, reaction: 'A boundary can be clear without insulting anyone.' }, { text: 'I’ll share your private messages to embarrass you.', respect: 0, calm: -15, trust: -20, reaction: 'Exposing private information creates a new problem. Keep the discussion about the rule.' }],
    [{ text: 'Let’s pause and each explain one point when everyone is calmer.', respect: 100, calm: 12, trust: 8, reaction: 'A pause is a valid way to lower the heat.' }, { text: 'I’m stepping away for now. We can revisit it respectfully later.', respect: 100, calm: 12, trust: 7, reaction: 'You can choose a calm exit and keep a boundary.' }, { text: 'I’ll type louder and insult everyone.', respect: 10, calm: -15, trust: -15, reaction: 'More pressure is likely to make understanding harder.' }],
    [{ text: 'Use the written rule for this round, then review changes before the next game.', respect: 100, calm: 8, trust: 10, reaction: 'A clear temporary agreement makes play possible.' }, { text: 'I’ll sit out this round and rejoin when we have a respectful agreement.', respect: 100, calm: 9, trust: 8, reaction: 'A respectful boundary is a complete and valid outcome.' }, { text: 'I decide everything. Nobody else gets a voice.', respect: 10, calm: -10, trust: -12, reaction: 'A shared activity needs a shared understanding.' }],
  ] },
];
export default function TalkItOut({ difficulty, mission, paused, onFinish }: GameProps) {
  const d = difficultyIndex(difficulty); const story = situations[mission]; const [goal, setGoal] = useState(''); const [step, setStep] = useState(0); const [calm, setCalm] = useState([65, 55, 45][d]); const [trust, setTrust] = useState([60, 50, 40][d]); const [respect, setRespect] = useState(0); const [listened, setListened] = useState(false); const [reaction, setReaction] = useState(''); const [waiting, setWaiting] = useState(false); const [history, setHistory] = useState<string[]>([]);
  function choose(option: Reply) { setCalm(clamp(calm + option.calm)); setTrust(clamp(trust + option.trust)); setRespect(respect + option.respect); setReaction(`${trust < 40 ? 'The conversation is tense, but there is room to reset. ' : ''}${option.reaction}`); setWaiting(true); setHistory([...history, option.text]); }
  function advance() { if (step === 2) { const score = Math.round(clamp(respect / 3 * 0.7 + calm * 0.15 + trust * 0.1 + (listened ? 5 : 0))); onFinish({ score, summary: `You practiced ${goal.toLowerCase()} with ${story.person.split(' · ')[0].toLowerCase()}. ${score >= 60 ? 'Your approach created room for a useful next step.' : 'The reactions show a few places where another approach could help.'}`, lesson: 'Clear boundaries, honest questions, listening, and respectful pauses can all be effective. You do not have to agree or keep talking to be respectful. If a situation feels unsafe, leave and ask a trusted adult for support.', metrics: { 'Respectful communication': `${Math.round(respect / 3)}%`, 'Calm at the end': `${calm}%`, 'Perspective checked': listened ? 'Yes' : 'Not yet' } }); } else { setStep(step + 1); setReaction(''); setWaiting(false); } }
  return <GameLayout kind="talk" title={story.title} description={story.context} paused={paused}>
    <Stats><Stat label="Conversation step" value={`${step + 1}/3`} icon="message" accent /><Stat label="Your approach" value={goal || 'Choose one'} /></Stats><Meter label="Calm" value={calm} color="#ffa68a" /><Meter label="Trust in the conversation" value={trust} color="#bba2ff" />
    {!goal ? <><h3>What do you want to practice?</h3><div className="choice-grid"><button className="choice-btn" onClick={() => setGoal('A clear boundary')}><strong>A clear boundary</strong>Say what you need directly and respectfully.</button><button className="choice-btn" onClick={() => setGoal('A collaborative plan')}><strong>A collaborative plan</strong>Ask questions and find a next step together.</button></div><Notice>Both approaches can work. You do not need to be outgoing or agreeable to communicate well.</Notice></> : <><StepDots total={3} current={step} /><div className="conversation"><span className="speaker">{story.person}</span><p>{story.prompts[step]}</p>{reaction && <p className="reply">{reaction}</p>}</div>{!listened && !waiting && <Action secondary onClick={() => { setListened(true); setTrust(clamp(trust + 10)); }}>Pause and check their perspective</Action>}{listened && <Notice>{story.need}</Notice>}{waiting ? <div className="game-actions"><Action onClick={advance}>{step === 2 ? 'Reflect on the conversation' : 'Continue the story'}</Action></div> : <div className="dialogue-choices">{story.options[step].map(option => <button key={option.text} onClick={() => choose(option)}>{option.text}</button>)}</div>}<ul className="game-log">{history.map((line, i) => <li key={i}><strong>You:</strong> {line}</li>)}</ul></>}
  </GameLayout>;
}
