import { games } from '../data/games';
import { gameStats, missionKey } from './progress';
import type { GameId, SaveData } from '../data/types';
export interface Guidance { hint: string; steps: string[]; resources: string; mistake: string }
export const guidance: Record<GameId, Guidance> = {
  money: { hint: 'Cover the needed bills before choosing savings and fun.', steps: ['Check take-home pay.', 'Fund essentials and leave a cushion.', 'Compare ways to handle each surprise.'], resources: 'Your unallocated cash and emergency savings already provide a cushion.', mistake: 'A smaller budget line does not reduce the bill itself.' },
  hustle: { hint: 'Keep your price above costs and your bookings within work time.', steps: ['Choose a trade.', 'Check the daily estimate.', 'Run a day and adjust based on results.'], resources: 'Start with the tools you have. Reinvest only when the reserve still covers a day.', mistake: 'Revenue is not profit: expenses and reserves still matter.' },
  scam: { hint: 'Inspect the sender, request, and link before sorting a message.', steps: ['Pin specific warning signs.', 'Choose safe, suspicious, or independent verification.', 'Read the feedback before continuing.'], resources: 'A known official contact is a free verification resource.', mistake: 'Urgency and a familiar display name do not prove identity.' },
  media: { hint: 'Spend research tokens on original sources and missing context.', steps: ['Open a source.', 'Pin relevant evidence.', 'File a verdict that matches the evidence.'], resources: 'Save tokens for a source that can actually change your conclusion.', mistake: 'Popularity is not a measure of whether a claim is supported.' },
  fix: { hint: 'Observe the fault and measure before selecting an approach.', steps: ['Inspect the model.', 'Subtract the starting mark from the ending mark.', 'Choose a matching tool and test the model.'], resources: 'Qualified help is a resource, especially for electrical or other unsafe faults.', mistake: 'More force is not a substitute for a correct diagnosis.' },
  code: { hint: 'Predict the robot’s next tile before running the whole program.', steps: ['Add a few commands.', 'Check walls and the star.', 'Run, inspect a collision, and revise.'], resources: 'The bottom row and right edge provide a clear baseline route.', mistake: 'A reusable function still needs a map where its assumptions hold.' },
  career: { hint: 'Use honest examples and shifts you can actually attend.', steps: ['Choose relevant experience.', 'Plan availability.', 'Answer clearly and ask for help when a task is unfamiliar.'], resources: 'Volunteer experience and ordinary responsibilities can show real skills.', mistake: 'An invented qualification can create a problem later.' },
  food: { hint: 'Compare portions and plan storage before completing the basket.', steps: ['Buy enough food for the menus.', 'Assign one menu to each day.', 'Store each item appropriately.'], resources: 'A useful staple and a flexible menu can save money and reduce waste.', mistake: 'A lower sticker price is not always a lower price per portion.' },
  admin: { hint: 'Schedule tasks before their deadlines and preserve bill funds.', steps: ['Assign days.', 'Use today’s action slots.', 'Advance the calendar and check renewals.'], resources: 'Receipts, reminders, and an early message can prevent avoidable work.', mistake: 'Autopay cannot help if the account has insufficient funds.' },
  talk: { hint: 'Choose a goal, listen, and state the next step respectfully.', steps: ['Pick collaboration or a clear boundary.', 'Check the other perspective.', 'Respond and observe how trust changes.'], resources: 'You can ask a trusted person for help with a difficult conversation.', mistake: 'Being respectful does not require giving up every boundary.' },
  power: { hint: 'Match generation, storage, and demand through the whole forecast.', steps: ['Build a balanced system.', 'Preview the next hour.', 'Adapt before funds or stored energy run short.'], resources: 'Efficiency can reduce the demand you must supply.', mistake: 'Power in kW and energy in kWh describe different quantities.' },
  rescue: { hint: 'Use open routes, current information, and trusted help.', steps: ['Collect useful kit items.', 'Follow the marked route.', 'Make a known-contact plan at the help desk.'], resources: 'Staffed public places and a current map are useful resources.', mistake: 'A risky shortcut does not become safe because you are in a hurry.' },
  music: { hint: 'Build a pulse, leave some rests, and vary the melody.', steps: ['Load or create a pattern.', 'Perform it twice and change one part.', 'Save your composition.'], resources: 'The silent performance view works without speakers or headphones.', mistake: 'A busy pattern is not automatically a better composition.' },
  frequency: { hint: 'Tune the hertz value toward the target and compare the wave.', steps: ['Check target frequency.', 'Move the frequency slider.', 'Test, adjust, and repeat.'], resources: 'Numbers and the wave display can replace listening.', mistake: 'Phone haptic pulses do not set the motor’s frequency or provide therapy.' },
  botany: { hint: 'Inspect the soil before deciding how much water to add.', steps: ['Match plants to light.', 'Observe moisture each day.', 'Use water where needed and review health.'], resources: 'Mulch and suitable drainage help manage the model’s water budget.', mistake: 'Watering more can be harmful when the soil is already very wet.' },
  math: { hint: 'Write the equation, then undo operations on both sides.', steps: ['Identify the unknown.', 'Use the formula and units.', 'Check by substituting your result.'], resources: 'Use the worked examples and live function machine.', mistake: 'A percentage increase acts on the current amount.' },
  geometry: { hint: 'Sketch the shape and label every length before calculating.', steps: ['Identify the shape.', 'Use perpendicular height where required.', 'Keep square and cubic units separate.'], resources: 'The Geometry Forge classes compare surface and volume.', mistake: 'Doubling every length does not merely double area or volume.' },
  calculus: { hint: 'Compare the function value, slope, and signed accumulation.', steps: ['Start from the stated function.', 'Differentiate or integrate the correct expression.', 'Inspect a nearby point or the interval bounds.'], resources: 'Take the derivatives class before tangent predictions.', mistake: 'A derivative and an integral answer different questions.' },
  physics: { hint: 'Write the model assumptions and check the result’s units.', steps: ['Choose the physical law.', 'Substitute values in consistent units.', 'Compare the prediction with the experiment.'], resources: 'The flight and energy classes explain the formulas.', mistake: 'An ideal projectile model omits air resistance.' },
  engine: { hint: 'Assemble every component, then trade speed for torque with gearing.', steps: ['Build the bench.', 'Test torque, rotation, and temperature.', 'Change one setting and retest.'], resources: 'A worked powertrain class explains output power.', mistake: 'Cooling does not create extra mechanical power.' },
  robot: { hint: 'Match the battery and controller to an inspected delivery route.', steps: ['Install hardware.', 'Step the controller and inspect position.', 'Check energy before the full route.'], resources: 'A starting route is available; improve it after observing the model.', mistake: 'A larger motor also consumes more energy.' },
  vm: { hint: 'Install enough memory and inspect the instruction counter.', steps: ['Assemble CPU, RAM, storage, and clock.', 'Step a worked program.', 'Check output and HALT.'], resources: 'The instruction reference and class explain each opcode.', mistake: 'A faster clock cannot fix an invalid address or endless loop.' },
  trail: { hint: 'Keep reserves and include a staffed community stop.', steps: ['Compare all travel costs.', 'Plan enough distance with recovery.', 'Review the weakest supply after every leg.'], resources: 'Transit and community help can make the route more resilient.', mistake: 'The shortest route can consume resources you cannot replace.' },
  water: { hint: 'Treat clarity, verified safety, and storage as separate checks.', steps: ['Switch away from chemical contamination.', 'Reduce leaks and protect storage.', 'Balance inflow with demand.'], resources: 'Official water guidance is linked in the class and game.', mistake: 'Boiling cannot make fuel-contaminated water safe.' },
  kitchen: { hint: 'Plan enough portions and measure the virtual dish before serving.', steps: ['Prepare clean components.', 'Use moderate heat and a measured endpoint.', 'Check suitable cold storage.'], resources: 'FoodSafety.gov is linked for real temperature guidance.', mistake: 'Virtual heating time is not a real cooking instruction.' },
  creator: { hint: 'Build a clear rundown and leave room for narration in the mix.', steps: ['Add at least three scenes.', 'Review captions, privacy, and moderation.', 'Rehearse before exporting locally.'], resources: 'The preview uses generated visuals without a camera or microphone.', mistake: 'A bitrate estimate is not a guarantee of actual file size.' },
  driving: {"hint":"Check the vehicle, slow early, and preserve more space than the model needs to stop.","steps":["Review the current state manual.","Compare speed, reaction time, and stopping space.","Choose the clear, attentive road decision."],"resources":"Official state DMV manuals cover the rules and exam requirements for your jurisdiction.","mistake":"A simplified stopping-distance model cannot establish a real vehicle’s safe gap."},
  cdl: {"hint":"Report the warning, wait for qualified service, and balance secured virtual cargo.","steps":["Complete the virtual inspection.","Receive model service clearance.","Plan the freight route with room and visibility."],"resources":"FMCSA describes federal ELDT requirements; state agencies provide current CDL manuals.","mistake":"A game completion does not provide ELDT training or a CDL credential."},
  trade: {"hint":"Read the blueprint and measure every virtual piece before cutting.","steps":["Count two widths and two heights.","Include kerf in the stock budget.","Join and inspect the frame."],"resources":"Registered apprenticeships combine supervised paid work, mentoring, and instruction.","mistake":"A journeyworker credential comes from actual training requirements, not a game badge."},
  lines: {"hint":"Protect the area and coordinate with utility dispatch before any simulated restoration.","steps":["Select a damaged branch.","Record the seven dispatch milestones in order.","Wait for qualified work and clearance."],"resources":"Real downed lines require distance and contact with the utility or emergency service.","mistake":"Switching a line off does not prove it is safe to work on."},
  electric: {"hint":"Build with model power off, then compare current to the protected circuit brief.","steps":["Install every virtual part.","Choose series or parallel and suitable resistance.","Energize, measure, power off to revise."],"resources":"Ohm’s law relates voltage, current, and resistance in this ideal circuit.","mistake":"A battery-only virtual model does not authorize physical electrical work."},
  fire: {"hint":"Prepare the protection layers and take a clear route to the outside.","steps":["Review alarms and the escape plan.","Avoid every blocked tile.","Meet outside and request help in the exercise."],"resources":"USFA explains working alarms, clear routes, and outside meeting plans.","mistake":"Never go back inside a real fire to finish a task or recover a possession."},
  swim: {"hint":"Layer protection, pause unsafe outings, and alert trained help.","steps":["Choose all four preparation layers.","Revise the plan when conditions are unsuitable.","Assist from a stable land position and keep response access clear."],"resources":"Qualified hands-on swimming, rescue, and CPR classes teach skills this game cannot.","mistake":"An inflatable toy does not replace a fitted approved life jacket."},
  sports: {"hint":"Put energy recovery before default movement in the controller.","steps":["Load a worked controller and inspect its priority.","Step from ball control to the goal.","Compare the trace on another seed."],"resources":"The arena records each action and the first matching rule.","mistake":"An always rule at the top prevents later rules from ever running."},
  outpost: {"hint":"Refill water and recover energy before the default supply route.","steps":["Observe reserves after each tick.","Travel to the marked water station when needed.","Collect the required supplies and return to shelter."],"resources":"Seeded trials let you compare controllers under the same conditions.","mistake":"A supply route can fail even when every destination is reachable."},
  scenario: {"hint":"Observe, protect, and dispatch qualified response at every task site.","steps":["Route to the active objective.","Interact three times in the stated order.","Inspect the trace before the next site."],"resources":"Priority rules make the controller’s decisions inspectable.","mistake":"A faster controller is not better when it skips a required response stage."},
  space: {"hint":"Reduce relative speed before asking the model to dock.","steps":["Approach using bounded thrusters.","Brake a fast close approach.","Interact only inside the docking window."],"resources":"The trace exposes position, energy, rule priority, and docking results.","mistake":"This Cartesian training model omits gravity and orbital dynamics."},
};
export function recommend(save: SaveData, query = '') {
  const rungTerms: Partial<Record<GameId, RegExp>> = { driving:/dmv|driv|road|conduc|carretera/i,cdl:/cdl|truck|freight|camión/i,trade:/journey|apprent|trade|blueprint|oficio|aprendiz/i,lines:/linemen|line crew|utility|liniero/i,electric:/electric|circuit|ohm|eléctr/i,fire:/fire|escape|incendio/i,swim:/swim|water safety|lifeguard|natación/i,sports:/sport|deporte/i,outpost:/survival agent|agent outpost|agente.*superv/i,scenario:/scenario|scenerio|dispatch|escenario/i,space:/space|dock|rendezvous|espacio/i };
  const rung = games.slice(26).find(g => rungTerms[g.id]?.test(query));
  const terms: Partial<Record<GameId, RegExp>> = { money: /budget|money|dinero|presupuesto|saving/i, hustle: /business|negocio|profit/i, scam: /scam|fraud|phish|estafa/i, media: /news|evidence|noticia|prueba/i, fix: /repair|tool|repara|herramienta/i, code: /code|robot|program/i, career: /job|career|trabajo|empleo/i, food: /food|meal|comida|alimento/i, admin: /schedule|deadline|organ|calendario/i, talk: /talk|friend|hablar|amigo|boundar/i, power: /energy|solar|energía/i, music: /music|música|rhythm|ritmo|melod/i, frequency: /wave|frequen|vibr|sound|sonido|onda/i, botany: /plant|garden|botan|jardín|ecolog/i };
  const advancedTerms: Partial<Record<GameId, RegExp>> = { math:/algebra|equation|math|matem/i, geometry:/geom|shape|volume/i, calculus:/calculus|cálculo|derivative|integral|tangent/i, physics:/physics|física|force|motion/i, engine:/engine|motor|torque/i, robot:/robot|bot build|hardware/i, vm:/virtual machine|computer|cpu|ram|computador/i, trail:/surviv|trail|viaje|resilien/i, water:/water|agua/i, kitchen:/cook|kitchen|cocina/i, creator:/stream|production|video|studio show|producci/i };
  const advanced = games.slice(15).find(g => advancedTerms[g.id]?.test(query));
  const named = rung || advanced || games.find(g => terms[g.id]?.test(query));
  const game = named || [...games].sort((a, b) => gameStats(save, a.id).completed - gameStats(save, b.id).completed)[0];
  const mission = Array.from({ length: game.missions }, (_, i) => i).find(i => !save.records[missionKey(game.id, save.difficulty, i)]?.completed) ?? 0;
  return { game, mission, guidance: guidance[game.id] };
}
