import { games } from '../data/games';
import { gameStats, missionKey } from './progress';
import type { GameId, SaveData } from '../data/types';
export interface Guidance { hint: string; steps: string[]; resources: string; mistake: string }
export const guidance: Record<GameId, Guidance> = {
  money: { hint: 'Cover the needed bills before choosing savings and fun.', steps: ['Check take-home pay.', 'Fund essentials and leave a cushion.', 'Compare ways to handle each surprise.'], resources: 'Your unallocated cash and emergency savings already provide a cushion.', mistake: 'A smaller budget line does not reduce the bill itself.' },
  hustle: { hint: 'Keep your price above costs and your bookings within work time.', steps: ['Choose a trade.', 'Check the daily estimate.', 'Run a day and adjust based on results.'], resources: 'Start with the tools you have. Reinvest only when the reserve still covers a day.', mistake: 'Revenue is not profit: expenses and reserves still matter.' },
  scam: { hint: 'Inspect the sender, request, and link before sorting a message.', steps: ['Pin specific warning signs.', 'Choose safe, suspicious, or independent verification.', 'Read the feedback before continuing.'], resources: 'A known official contact is a free verification resource.', mistake: 'Urgency and a familiar display name do not prove identity.' },
  media: { hint: 'Spend research tokens on original sources and missing context.', steps: ['Open a source.', 'Pin relevant evidence.', 'File a verdict that matches the evidence.'], resources: 'Save tokens for a source that can actually change your conclusion.', mistake: 'Popularity is not a measure of whether a claim is supported.' },
  fix: { hint: 'Observe the fault and measure before selecting an approach.', steps: ['Inspect the model.', 'Subtract the starting mark from the ending mark.', 'Choose a matching tool and test the model.'], resources: 'Qualified help is a resource, especially for electrical or other unsafe faults.', mistake: 'More force is not a substitute for a correct diagnosis.' },
  code: { hint: 'Predict the robot’s next tile before running the whole program.', steps: ['Add a few commands.', 'Check walls and the star.', 'Run, inspect a collision, and revise.'], resources: 'The bottom row and right edge provide a clear baseline route.', mistake: 'A reusable function still needs a map where its assumptions hold.' },
  career: { hint: 'Use honest examples and shifts you can actually attend.', steps: ['Choose relevant experience.', 'Plan availability.', 'Answer clearly and ask for help when a task is unfamiliar.'], resources: 'Volunteer experience and ordinary responsibilities can show real skills.', mistake: 'An invented qualification can create a problem later.' },
  food: { hint: 'Compare portions and plan storage before completing the basket.', steps: ['Buy enough food for the menus.', 'Assign one menu to each day.', 'Store each item appropriately.'], resources: 'A useful staple and a flexible menu can save money and reduce waste.', mistake: 'A lower sticker price is not always a lower price per portion.' },
  admin: { hint: 'Schedule tasks before their deadlines and preserve bill funds.', steps: ['Assign days.', 'Use today’s action slots.', 'Advance the calendar and check renewals.'], resources: 'Receipts, reminders, and an early message can prevent avoidable work.', mistake: 'Autopay cannot help if the account has insufficient funds.' },
  talk: { hint: 'Choose a goal, listen, and state the next step respectfully.', steps: ['Pick collaboration or a clear boundary.', 'Check the other perspective.', 'Respond and observe how trust changes.'], resources: 'You can ask a trusted person for help with a difficult conversation.', mistake: 'Being respectful does not require giving up every boundary.' },
  power: { hint: 'Match generation, storage, and demand through the whole forecast.', steps: ['Build a balanced system.', 'Preview the next hour.', 'Adapt before funds or stored energy run short.'], resources: 'Efficiency can reduce the demand you must supply.', mistake: 'Power in kW and energy in kWh describe different quantities.' },
  rescue: { hint: 'Use open routes, current information, and trusted help.', steps: ['Collect useful kit items.', 'Follow the marked route.', 'Make a known-contact plan at the help desk.'], resources: 'Staffed public places and a current map are useful resources.', mistake: 'A risky shortcut does not become safe because you are in a hurry.' },
  music: { hint: 'Build a pulse, leave some rests, and vary the melody.', steps: ['Load or create a pattern.', 'Perform it twice and change one part.', 'Save your composition.'], resources: 'The silent performance view works without speakers or headphones.', mistake: 'A busy pattern is not automatically a better composition.' },
  frequency: { hint: 'Tune the hertz value toward the target and compare the wave.', steps: ['Check target frequency.', 'Move the frequency slider.', 'Test, adjust, and repeat.'], resources: 'Numbers and the wave display can replace listening.', mistake: 'Phone haptic pulses do not set the motor’s frequency or provide therapy.' },
  botany: { hint: 'Inspect the soil before deciding how much water to add.', steps: ['Match plants to light.', 'Observe moisture each day.', 'Use water where needed and review health.'], resources: 'Mulch and suitable drainage help manage the model’s water budget.', mistake: 'Watering more can be harmful when the soil is already very wet.' },
};
export function recommend(save: SaveData, query = '') {
  const terms: Partial<Record<GameId, RegExp>> = { money: /budget|money|dinero|presupuesto|saving/i, hustle: /business|negocio|profit/i, scam: /scam|fraud|phish|estafa/i, media: /news|evidence|noticia|prueba/i, fix: /repair|tool|repara|herramienta/i, code: /code|robot|program/i, career: /job|career|trabajo|empleo/i, food: /food|meal|comida|alimento/i, admin: /schedule|deadline|organ|calendario/i, talk: /talk|friend|hablar|amigo|boundar/i, power: /energy|solar|energía/i, music: /music|música|rhythm|ritmo|melod/i, frequency: /wave|frequen|vibr|sound|sonido|onda/i, botany: /plant|garden|botan|jardín|ecolog/i };
  const named = games.find(g => terms[g.id]?.test(query));
  const game = named || [...games].sort((a, b) => gameStats(save, a.id).completed - gameStats(save, b.id).completed)[0];
  const mission = Array.from({ length: game.missions }, (_, i) => i).find(i => !save.records[missionKey(game.id, save.difficulty, i)]?.completed) ?? 0;
  return { game, mission, guidance: guidance[game.id] };
}
