import { useEffect, useState } from 'react';
import { difficultyIndex, type GameProps } from '../../data/types';
import { useMissionState } from '../../systems/MissionSession';
import { Action, Notice, Stat, Stats } from '../shared';
import { Formula, LabLayout, Select, Slider } from '../advanced/ui';
import { arenaObstacles, arenaObjective, arenaScore, arenaStart, arenaStep, arenaTaskCount, policyActions, policyChoice, policyConditions, rounded, runEpisode, workedPolicy, type ArenaKind, type ArenaState, type PolicyAction, type PolicyRule } from './models';
import { useStudio } from '../../systems/StudioContext';
import { playAgentCue } from '../../systems/sound';
import { parsePolicy } from './validation';
export interface TrainingState { seed:number;rules:PolicyRule[];episode:ArenaState;tests:number; }
const titles:Record<ArenaKind,string>={sports:'Sport Bot Arena',outpost:'Survival Agent Outpost',scenario:'Scenario Agent Dispatch',space:'Space Agent Rendezvous'};
const briefs:Record<ArenaKind,string>={sports:'Control the ball, route around barriers, and score at the goal. Prioritize energy recovery before the next play.',outpost:'Collect supplies and return to shelter. Your agent must balance route length, energy, and trips to the water station at (0, 0).',scenario:'Visit each task site and record observation, a protected zone, and qualified-response dispatch in that order.',space:'Control an ideal Cartesian thruster model. Approach the station, slow relative motion, and dock within 2 × 1 position units below 0.8 speed units.'};
export function AgentArena({kind,difficulty,mission,onFinish,paused}:GameProps&{kind:ArenaKind}) {
  const {save}=useStudio();
  const d=difficultyIndex(difficulty),[s,set]=useMissionState<TrainingState>('model',()=>({seed:mission,rules:[{when:'always',action:'approach'}],episode:arenaStart(kind,mission,d),tests:0}));
  const [running,start]=useState(false),[notice,setNotice]=useState(''),[manual,setManual]=useState<PolicyAction>('approach'),[replay,setReplay]=useState(-1);
  const active=running&&s.episode.status==='ready',target=arenaObjective(s.episode),trace=s.episode.trace,view=replay>=0?trace[Math.min(replay,trace.length-1)]:s.episode;
  useEffect(()=>{if(!active||paused)return;const timer=setInterval(()=>set(previous=>{if(previous.episode.status!=='ready')return previous;const pick=policyChoice(previous.episode,previous.rules);return {...previous,episode:arenaStep(previous.episode,pick.action,pick.reason)};}),160);return()=>clearInterval(timer);},[active,paused,set]);
  useEffect(()=>{if(!running||paused||!trace.length)return;const row=trace[trace.length-1],previous=trace[trace.length-2];playAgentCue(s.episode.status==='complete'?'complete':row.reason.includes('Blocked move')?'blocked':row.progress>(previous?.progress||0)?'interact':kind==='space'?'thruster':'move',kind==='space'?row.x/50:row.x/4-1);},[trace,running,paused,kind,s.episode.status]);
  const reset=(rules=s.rules,seed=s.seed)=>{start(false);setReplay(-1);set({...s,seed,rules,episode:arenaStart(kind,seed,d)});};
  const changeRule=(index:number,rule:PolicyRule)=>reset(s.rules.map((r,i)=>i===index?rule:r));
  const exportPolicy=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({version:1,kind,rules:s.rules},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`brain-sweat-${kind}-policy.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Controller exported. Its rules can be imported into an online agent duel.');};
  const importPolicy=async(file?:File)=>{if(!file)return;try{if(file.size>12000)throw new Error('Choose a policy file smaller than 12 KB.');const rules=parsePolicy(JSON.parse(await file.text()),kind);reset(rules);setNotice('Controller imported. Inspect the rules, then run a fresh episode.');}catch(error){setNotice(error instanceof Error?error.message:'The controller could not be imported.');}};
  return <LabLayout kind={kind} title={`${titles[kind]} · trial ${mission+1}`} description={briefs[kind]} paused={paused} data={{x:view.x,y:view.y,goalX:target[0],goalY:target[1],progress:view.progress,seed:s.seed,vx:s.episode.vx,vy:s.episode.vy}}>
    <div className="agent-status-bar"><span className="eyebrow">PROGRAM · OBSERVE · REVISE</span><strong>{s.episode.status}</strong></div>
    <Slider label="Training seed" value={s.seed} min={0} max={99} onChange={seed=>reset(s.rules,seed)}/>
    {kind!=='space'&&<div className="rung-map agent-map" role="img" aria-label={`Agent at ${view.x}, ${view.y}; current objective ${target[0]}, ${target[1]}; water station 0, 0.`}>{Array.from({length:63},(_,i)=>{const x=i%9,y=Math.floor(i/9),wall=arenaObstacles(s.seed).some(p=>p[0]===x&&p[1]===y);return <span key={i} className={wall?'wall':x===target[0]&&y===target[1]?'goal':''}>{x===view.x&&y===view.y?'●':wall?'■':x===target[0]&&y===target[1]?'★':kind==='outpost'&&x===0&&y===0?'W':'·'}</span>;})}</div>}
    <h3>Priority controller</h3><p>Top to bottom: the first matching condition chooses one action. Editing resets the episode.</p>
    <ol className="policy-rules">{s.rules.map((rule,i)=><li key={i}><Select label={`Rule ${i+1} condition`} value={rule.when} options={policyConditions.map(value=>({value,label:value}))} onChange={when=>changeRule(i,{...rule,when:when as PolicyRule['when']})}/><Select label={`Rule ${i+1} action`} value={rule.action} options={policyActions.map(value=>({value,label:value}))} onChange={action=>changeRule(i,{...rule,action:action as PolicyAction})}/><button className="btn secondary" aria-label={`Move rule ${i+1} up`} disabled={active||i===0} onClick={()=>{const rules=[...s.rules];[rules[i-1],rules[i]]=[rules[i],rules[i-1]];reset(rules);}}>↑</button><button className="btn secondary" aria-label={`Remove rule ${i+1}`} disabled={active||s.rules.length===1} onClick={()=>reset(s.rules.filter((_,j)=>j!==i))}>×</button></li>)}</ol>
    <div className="button-row"><Action secondary disabled={active||s.rules.length===8} onClick={()=>reset([...s.rules,{when:'always',action:'coast'}])}>Add controller rule</Action><Action secondary onClick={()=>reset(workedPolicy(kind))}>Load a worked controller</Action></div>
    <div className="button-row"><Action disabled={active} onClick={()=>{setReplay(-1);set({...s,episode:arenaStart(kind,s.seed,d),tests:s.tests+1});start(true);}}>Run live training</Action><Action secondary disabled={active} onClick={()=>{start(false);setReplay(-1);set({...s,episode:runEpisode(arenaStart(kind,s.seed,d),s.rules),tests:s.tests+1});}}>Run full episode</Action><Action secondary disabled={active||s.episode.status!=='ready'} onClick={()=>{setReplay(-1);const pick=policyChoice(s.episode,s.rules);set({...s,episode:arenaStep(s.episode,pick.action,pick.reason),tests:s.tests+1});}}>Step policy</Action><Action secondary disabled={!active} onClick={()=>start(false)}>Stop training</Action><Action secondary onClick={()=>reset()}>Reset episode</Action></div>
    <details className="manual-control"><summary>Optional manual control</summary><Select label="Manual agent action" value={manual} options={policyActions.map(value=>({value,label:value}))} onChange={v=>setManual(v as PolicyAction)}/><Action secondary disabled={active||s.episode.status!=='ready'} onClick={()=>{setReplay(-1);set({...s,episode:arenaStep(s.episode,manual),tests:s.tests+1});}}>Take manual step</Action></details>
    <Stats><Stat label="Training ticks" value={`${s.episode.tick}/120`}/><Stat label="Agent energy" value={rounded(view.energy)}/><Stat label={kind==='space'?'Relative speed':'Task progress'} value={kind==='space'?rounded(Math.hypot(s.episode.vx,s.episode.vy)):`${s.episode.progress}/${arenaTaskCount(s.episode)+(kind==='outpost'?1:0)}`}/><Stat label="Water reserve" value={rounded(view.water)}/></Stats>
    <Notice tone={s.episode.status==='complete'?'success':s.episode.status==='ready'?'info':'warning'}>{s.episode.status==='complete'?'Task complete. Inspect the trace, change the seed, or compare a different controller.':s.episode.status==='ready'?'Each tick records the chosen rule, action, position, and resources.':'The episode ended before the goal. Revise rule priority, resource recovery, or approach speed and retry.'}</Notice>
    {trace.length>0&&<details className="trace-panel"><summary>Inspect and replay the episode trace</summary><Slider label="Replay tick" value={replay<0?trace.length-1:replay} min={0} max={Math.max(0,trace.length-1)} onChange={setReplay}/><p>Viewed position: ({view.x}, {view.y}) · energy {rounded(view.energy)}</p><div className="trace-scroll" tabIndex={0} role="region" aria-label="Episode trace"><table><thead><tr><th>Tick</th><th>Action</th><th>Position</th><th>Energy</th><th>Reason</th></tr></thead><tbody>{trace.map(row=><tr key={row.tick}><td>{row.tick}</td><td>{row.action}</td><td>{row.x}, {row.y}</td><td>{row.energy}</td><td>{row.reason}</td></tr>)}</tbody></table></div><Action secondary onClick={()=>setReplay(-1)}>Return to live position</Action></details>}
    <div className="button-row"><a className="btn secondary" href={`#/academy?arena=${kind}`}>Train in the academy</a><Action secondary disabled={!save.academy?.controllers[kind]} onClick={()=>{const trained=save.academy?.controllers[kind];if(trained){reset(trained.champion);setNotice('Academy champion loaded. Run this arena seed to compare it.');}}}>Load academy champion</Action><Action secondary onClick={exportPolicy}>Export controller</Action><label className="btn secondary import-button">Import controller<input aria-label="Import agent controller" type="file" accept=".json,application/json" onChange={e=>{void importPolicy(e.target.files?.[0]);e.target.value='';}}/></label><a className="btn secondary" href={`#/online?arena=${kind}`}>Compete with this controller</a></div>{notice&&<Notice>{notice}</Notice>}
    <Formula>{kind==='space'?'Ideal relative-motion model with bounded thrusters, no gravity or orbital dynamics.':'Discrete grid-world model. Approach uses a shortest clear path; rest restores energy. Survival agents must travel to the marked station to refill.'}<p>Controllers use bounded rules, not arbitrary code. Authored demonstration bots remain practice-only. Online competitions evaluate controllers on shared server-selected seeds.</p></Formula>
    <Action disabled={s.episode.status!=='complete'} onClick={()=>onFinish({score:arenaScore(s.episode),summary:'Your agent completed its seeded training objective.',lesson:'Inspect what each rule caused, compare repeated trials, and keep resource and safety conditions ahead of default movement.',metrics:{Ticks:s.episode.tick,Collisions:s.episode.collisions,Seed:s.seed}})}>Submit my trained agent</Action>
  </LabLayout>;
}
export const SportArena=(props:GameProps)=><AgentArena {...props} kind="sports"/>;
export const SurvivalArena=(props:GameProps)=><AgentArena {...props} kind="outpost"/>;
export const ScenarioArena=(props:GameProps)=><AgentArena {...props} kind="scenario"/>;
export const SpaceArena=(props:GameProps)=><AgentArena {...props} kind="space"/>;
