import { difficultyIndex, type GameProps } from '../../data/types';
import { useMissionState } from '../../systems/MissionSession';
import { Action, Notice, Stat, Stats } from '../shared';
import { Formula, LabLayout, Select, Slider } from '../advanced/ui';
import { circuit, cutPiece, damagedLines, electricBrief, electricParts, electricStart, fireExit, fireLayers, fireMove, fireObstacles, fireStart, frameFits, lineAction, lineActions, lineNodes, lineStart, roadChecks, roadDecision, roadEvent, roadReady, roadStart, rounded, stoppingDistance, tradeBrief, tradeStart, truckChecks, truckRating, truckReady, truckStart, waterLayers, waterSafetyEvent, waterSafetyStart, type CircuitConfig, type Move, type RoadEvent } from './models';

function Checks({items,selected,onChange,disabled=false}:{items:string[];selected:string[];onChange:(next:string[])=>void;disabled?:boolean}) {
  return <div className="parts-grid">{items.map(item=><button key={item} className={`part-chip ${selected.includes(item)?'installed':''}`} aria-pressed={selected.includes(item)} disabled={disabled} onClick={()=>onChange(selected.includes(item)?selected.filter(i=>i!==item):[...selected,item])}>{item} {selected.includes(item)?'✓':'+'}</button>)}</div>;
}
function Decision({event,onChoice}:{event:RoadEvent;onChoice:(choice:number)=>void}) {
  return <section className="decision-panel"><h3>{event.title}</h3><p>{event.detail}</p><div className="choice-stack">{event.choices.map((choice,i)=><button className="btn secondary" key={choice} onClick={()=>onChoice(i)}>{choice}</button>)}</div></section>;
}
export function RoadReady({difficulty,mission,onFinish,paused}:GameProps) {
  const [s,set]=useMissionState('model',roadStart), d=difficultyIndex(difficulty), distances=stoppingDistance(s.speed,s.reaction,s.wet);
  const checked=roadChecks.every(c=>s.checks.includes(c)), ready=checked&&roadReady(s);
  return <LabLayout kind="driving" title={`Road Ready · route ${mission+1}`} description="Prepare the vehicle, compare a stopping-distance model, and make four road decisions. US fundamentals; use your state’s current manual for licensing and local rules." paused={paused} data={{progress:s.phase/4,speed:s.started?s.speed:0}}>
    <h3>Before the trip</h3><Checks items={roadChecks} selected={s.checks} disabled={s.started} onChange={checks=>set({...s,checks})}/>
    {!s.started&&<><Slider label="Model speed" value={s.speed} min={10} max={60} unit="mph" onChange={speed=>set({...s,speed})}/><Slider label="Reaction time" value={s.reaction} min={1} max={3} step={0.1} unit="s" onChange={reaction=>set({...s,reaction})}/><Slider label="Available stopping space" value={s.gap} min={10} max={150} unit="m" onChange={gap=>set({...s,gap})}/><label className="setting-row"><span>Wet road model</span><input type="checkbox" checked={s.wet} onChange={e=>set({...s,wet:e.target.checked})}/></label></>}
    <Stats><Stat label="Reaction distance" value={`${rounded(distances.reaction)} m`}/><Stat label="Braking distance" value={`${rounded(distances.braking)} m`}/><Stat label="Total stopping distance" value={`${rounded(distances.total)} m`}/><Stat label="Road decisions" value={`${s.phase}/4`}/></Stats>
    <Formula>Distance = speed × reaction time + speed² / (2 × deceleration)<p>The fictional route limit is 40 mph. Dry/wet deceleration is 5/3 m/s². This teaching model cannot predict a real vehicle’s safe stopping distance.</p></Formula>
    {!s.started&&<><Notice tone={ready?'success':'info'}>{ready?'Checks and stopping space meet this route brief.':'Complete the checks. Keep model speed at or below 40 mph and leave more space than the calculated stop.'}</Notice><Action disabled={!ready} onClick={()=>set({...s,started:true})}>Start the road scenario</Action></>}
    {s.started&&s.phase<4&&<Decision event={roadEvent(mission,s.phase)} onChoice={choice=>set(roadDecision(s,choice,mission))}/>}
    {s.feedback&&<Notice>{s.feedback}</Notice>}
    <a className="text-link" href="https://www.usa.gov/state-motor-vehicle-services" target="_blank" rel="noreferrer">Find your official state DMV manual →</a>
    <Action disabled={s.phase!==4} onClick={()=>onFinish({score:Math.max(60,100-s.risks*(5+d)),summary:'You prepared the vehicle and completed four road decisions.',lesson:'Plan space, scan for hazards, and check your state’s current manual. A game result is not a license or an official DMV exam.',metrics:{'Stopping distance':rounded(distances.total),Revisions:s.risks}})}>Submit my road plan</Action>
  </LabLayout>;
}
export function CDLFoundations({difficulty,mission,onFinish,paused}:GameProps) {
  const [s,set]=useMissionState('model',truckStart), d=difficultyIndex(difficulty), rating=truckRating(mission,d), ready=truckReady(s,mission,d);
  const decide=(choice:number)=>{const e=roadEvent(mission,s.phase);set(choice===e.correct?{...s,phase:s.phase+1,feedback:e.why}:{...s,risks:s.risks+1,feedback:`Pause and revise. ${e.why}`});};
  return <LabLayout kind="cdl" title={`CDL Foundations · freight ${mission+1}`} description="Inspect a fictional truck, report a warning, wait for virtual service clearance, balance cargo, and plan four road decisions." paused={paused} data={{progress:s.phase/4,load:s.front+s.rear}}>
    <h3>Virtual pre-trip inspection</h3><Checks items={truckChecks} selected={s.checks} disabled={s.started} onChange={checks=>set({...s,checks})}/>
    {!s.started&&<><Notice tone="warning">The simulated warning panel has a fault. Hold the trip and report it; a qualified service team handles the repair.</Notice><div className="button-row"><Action secondary disabled={s.faultReported||s.checks.length!==5} onClick={()=>set({...s,faultReported:true})}>Report the warning and hold</Action><Action secondary disabled={!s.faultReported||s.cleared} onClick={()=>set({...s,cleared:true})}>Receive virtual service clearance</Action></div><Slider label="Front cargo" value={s.front} min={0} max={30} unit="model units" onChange={front=>set({...s,front})}/><Slider label="Rear cargo" value={s.rear} min={0} max={30} unit="model units" onChange={rear=>set({...s,rear})}/><label className="setting-row"><span>Cargo secured in the model</span><input type="checkbox" checked={s.secured} onChange={e=>set({...s,secured:e.target.checked})}/></label><Action disabled={!ready} onClick={()=>set({...s,started:true})}>Begin the freight route</Action></>}
    <Stats><Stat label="Total cargo" value={`${s.front+s.rear}/${rating}`}/><Stat label="Cargo imbalance" value={Math.abs(s.front-s.rear)}/><Stat label="Service clearance" value={s.cleared?'Received':'Waiting'}/><Stat label="Road decisions" value={`${s.phase}/4`}/></Stats><Formula>This truck’s fictional capacity is {rating} cargo units, with a front/rear difference no greater than 4. Real axle, weight, inspection, and licensing rules require the applicable official manuals and qualified instruction.</Formula>
    {s.started&&s.phase<4&&<Decision event={roadEvent(mission,s.phase)} onChoice={decide}/>}{s.feedback&&<Notice>{s.feedback}</Notice>}
    <a className="text-link" href="https://www.fmcsa.dot.gov/registration/commercial-drivers-license/entry-level-driver-training-eldt" target="_blank" rel="noreferrer">FMCSA · actual CDL and ELDT requirements →</a>
    <Action disabled={s.phase!==4} onClick={()=>onFinish({score:Math.max(60,100-s.risks*7),summary:'Inspection, reported fault, service clearance, cargo, and road planning came together.',lesson:'Inspect before moving, resolve defects through qualified service, and use official CDL training. This studio does not provide ELDT certification.',metrics:{Cargo:s.front+s.rear,Revisions:s.risks}})}>Submit my freight plan</Action>
  </LabLayout>;
}
export function TradeBench({difficulty,mission,onFinish,paused}:GameProps) {
  const [s,set]=useMissionState('model',tradeStart), brief=tradeBrief(mission,difficultyIndex(difficulty)), fits=frameFits(s,brief);
  return <LabLayout kind="trade" title={`Trade Bench · frame ${mission+1}`} description={`Read a ${brief.width} × ${brief.height} mm blueprint. Measure and cut four virtual pieces in width, height, width, height order; tolerance ±${brief.tolerance} mm.`} paused={paused} data={{parts:s.pieces.length,width:brief.width/40,height:brief.height/40}}>
    <Formula>Bill of materials: 2 × {brief.width} mm + 2 × {brief.height} mm<br/>Stock: {brief.stock} mm · each virtual cut consumes 2 mm kerf.<p>Apprentices learn through supervised work and instruction. Game badges are practice records, not journeyworker credentials or permission to use real tools.</p></Formula>
    <Slider label="Virtual piece length" value={s.length} min={40} max={240} step={0.5} unit="mm" onChange={length=>set({...s,length,measured:false})}/><div className="button-row"><Action secondary disabled={s.pieces.length===4} onClick={()=>set({...s,measured:true,feedback:'Measurement checked against the blueprint.'})}>Measure against blueprint</Action><Action disabled={!s.measured||s.pieces.length===4||s.used+s.length+2>brief.stock} onClick={()=>set(cutPiece(s,brief))}>Cut virtual piece</Action></div>
    <ol className="cut-list" aria-label="Cut list">{s.pieces.map((length,i)=><li key={i}>Piece {i+1}: {length} mm · {i%2?'height':'width'}</li>)}</ol><Stats><Stat label="Stock remaining" value={`${rounded(brief.stock-s.used)} mm`}/><Stat label="Cut pieces" value={`${s.pieces.length}/4`}/><Stat label="Tolerance" value={`±${brief.tolerance} mm`}/></Stats>
    <div className="button-row"><Action secondary disabled={!fits||s.joined} onClick={()=>set({...s,joined:true})}>Join virtual frame</Action><Action secondary disabled={!s.joined||s.inspected} onClick={()=>set({...s,inspected:true,feedback:'Dimensions and the virtual assembly pass the inspection.'})}>Inspect the assembly</Action><Action secondary onClick={()=>set(tradeStart())}>Recycle and restart frame</Action></div>{s.feedback&&<Notice>{s.feedback}</Notice>}
    <Action disabled={!fits||!s.joined||!s.inspected} onClick={()=>onFinish({score:100,summary:'Your measured frame matches its blueprint and passed virtual inspection.',lesson:'Read the drawing, count material and kerf, measure, assemble, and inspect. Real trade skills grow through qualified supervised training.',metrics:{'Material used':s.used,Tolerance:brief.tolerance}})}>Submit my trade project</Action>
  </LabLayout>;
}
export function LineCrew({difficulty,mission,onFinish,paused}:GameProps) {
  const [s,set]=useMissionState('model',lineStart), faults=damagedLines(mission,difficultyIndex(difficulty)), done=faults.every(i=>s.stages[i]===7);
  return <LabLayout kind="lines" title={`Line Crew Dispatch · district ${mission+1}`} description="Coordinate qualified crews in a virtual district. Protect the area, communicate with utility dispatch, and wait for authorized clearances before simulated restoration." paused={paused} data={{progress:faults.filter(i=>s.stages[i]===7).length/faults.length,selected:s.selected}}>
    <Notice>Stay clear of real downed lines and contact the utility or emergency service. This coordination exercise omits the technical procedures only qualified personnel may perform.</Notice>
    <Select label="District branch" value={String(s.selected)} options={lineNodes.map((label,i)=>({value:String(i),label:`${label} · ${faults.includes(i)?s.stages[i]===7?'restored':'needs crew':'clear'}`}))} onChange={selected=>set({...s,selected:Number(selected)})}/>
    <div className="line-status">{lineNodes.map((name,i)=><div key={name}><span>{name}</span><strong>{faults.includes(i)?`${s.stages[i]}/7`:'Clear'}</strong></div>)}</div>
    <h3>Coordination sequence</h3><div className="choice-stack">{lineActions.map((action,i)=><button key={action} className="btn secondary" disabled={!faults.includes(s.selected)||s.stages[s.selected]===7} onClick={()=>set(lineAction(s,i,faults))}>{i+1}. {action}</button>)}</div>
    {s.feedback&&<Notice>{s.feedback}</Notice>}<Formula>“Off” does not establish a safe electrical work condition. Qualified utility workers follow testing, grounding, isolation, and other applicable procedures. The model only records dispatch milestones.</Formula>
    <Action disabled={!done} onClick={()=>onFinish({score:Math.max(60,100-s.risks*5),summary:'Every damaged branch received the full virtual dispatch sequence.',lesson:'Observation, public protection, utility coordination, qualified work, and authorized clearance precede restoration.',metrics:{'Branches restored':faults.length,Revisions:s.risks}})}>Submit the district recovery</Action>
  </LabLayout>;
}
export function CircuitWorkshop({difficulty,mission,onFinish,paused}:GameProps) {
  const [s,set]=useMissionState('model',electricStart), brief=electricBrief(mission,difficultyIndex(difficulty)), result=circuit(s.config), ready=electricParts.every(p=>s.parts.includes(p));
  const configure=(change:Partial<CircuitConfig>)=>set({...s,config:{...s.config,...change},measured:false});
  const success=ready&&s.powered&&s.measured&&!result.tripped&&s.config.mode===brief.mode&&result.current>=brief.min&&result.current<=brief.max;
  return <LabLayout kind="electric" title={`Circuit Workshop · board ${mission+1}`} description={`Assemble a virtual ${brief.mode} circuit with total current from ${brief.min} to ${brief.max} A. Test its protection module and read the virtual meter.`} paused={paused} data={{current:s.powered&&!result.tripped?result.current:0,parts:s.parts.length}}>
    <h3>Battery-only virtual board</h3><Checks items={electricParts} selected={s.parts} disabled={s.powered} onChange={parts=>set({...s,parts,measured:false})}/>
    <fieldset className="circuit-config" disabled={s.powered}><legend>Configure with model power off</legend><Select label="Circuit arrangement" value={s.config.mode} options={[{value:'series',label:'Series'},{value:'parallel',label:'Parallel'}]} onChange={mode=>configure({mode:mode as CircuitConfig['mode']})}/><Slider label="Virtual supply voltage" value={s.config.voltage} min={1} max={24} unit="V" onChange={voltage=>configure({voltage})}/><Slider label="Load A resistance" value={s.config.r1} min={1} max={30} unit="Ω" onChange={r1=>configure({r1})}/><Slider label="Load B resistance" value={s.config.r2} min={1} max={30} unit="Ω" onChange={r2=>configure({r2})}/><Slider label="Protection threshold" value={s.config.fuse} min={0.5} max={3} step={0.5} unit="A" onChange={fuse=>configure({fuse})}/></fieldset>
    <Formula>V = I × R · P = V × I<br/>Series: R = R₁ + R₂ · Parallel: 1/R = 1/R₁ + 1/R₂<p>Ideal components and an instantaneous protection threshold. No mains electricity or physical wiring is involved. Real electrical work needs the appropriate qualified supervision and procedures.</p></Formula>
    <div className="button-row"><Action disabled={!ready||s.powered} onClick={()=>set({...s,powered:true,tests:s.tests+1})}>Energize virtual board</Action><Action secondary disabled={!s.powered} onClick={()=>set({...s,measured:true})}>Read virtual meter</Action><Action secondary disabled={!s.powered} onClick={()=>set({...s,powered:false,measured:false})}>Power off and revise</Action></div>
    {s.measured&&<><Stats><Stat label="Equivalent resistance" value={`${rounded(result.resistance)} Ω`}/><Stat label="Total current" value={`${rounded(result.current)} A`}/><Stat label="Electrical power" value={`${rounded(result.power)} W`}/><Stat label="Protection state" value={result.tripped?'Tripped':'Holding'}/></Stats><Notice tone={success?'success':'warning'}>{result.tripped?'The protection module opened the virtual circuit. Power off and revise the loads.':success?'The meter confirms this board meets the brief.':'Compare the arrangement and current to the brief; power off before editing the model.'}</Notice></>}
    <Action disabled={!success} onClick={()=>onFinish({score:100,summary:'Your protected virtual circuit meets its current and arrangement brief.',lesson:'Series and parallel connections change equivalent resistance. Measure and check protection before accepting a design.',metrics:{Current:rounded(result.current),Power:rounded(result.power),Tests:s.tests}})}>Submit my circuit</Action>
  </LabLayout>;
}
export function FireEscape({mission,onFinish,paused}:GameProps) {
  const [s,set]=useMissionState('model',fireStart), exit=fireExit(mission), prepared=fireLayers.every(l=>s.layers.includes(l));
  return <LabLayout kind="fire" title={`Fire Escape Lab · home ${mission+1}`} description="Prepare a fictional home’s protection layers, find a clear route on the map, meet outside, and request help in the exercise." paused={paused} data={{x:s.x,y:s.y,mission,progress:Number(s.outside)}}>
    <Checks items={fireLayers} selected={s.layers} disabled={s.moves>0} onChange={layers=>set({...s,layers})}/><Notice>Plan two ways out where possible and keep routes clear. In a real fire, get out, stay out, and contact emergency help from outside. Never enter smoke to follow a game route.</Notice>
    <div className="rung-map fire-map" role="img" aria-label={`You are at ${s.x}, ${s.y}; clear exit is ${exit.x}, ${exit.y}. Blocked tiles are marked with squares.`}>{Array.from({length:48},(_,i)=>{const x=i%8,y=Math.floor(i/8),wall=fireObstacles(mission).some(p=>p[0]===x&&p[1]===y);return <span key={i} className={wall?'wall':x===exit.x&&y===exit.y?'goal':''}>{x===s.x&&y===s.y?'●':wall?'■':x===exit.x&&y===exit.y?'OUT':'·'}</span>;})}</div>
    <div className="direction-pad">{(['north','west','east','south'] as Move[]).map(move=><button className="btn secondary" key={move} disabled={!prepared||s.outside} onClick={()=>set(fireMove(s,move,mission))}>Move {move}</button>)}</div>
    <div className="button-row"><Action secondary disabled={!s.outside||s.meeting} onClick={()=>set({...s,meeting:true})}>Meet at the outside point</Action><Action secondary disabled={!s.outside||!s.meeting||s.help} onClick={()=>set({...s,help:true,feedback:'Help requested in the exercise. Everyone stays outside.'})}>Request help in the simulation</Action></div>{s.feedback&&<Notice>{s.feedback}</Notice>}
    <Action disabled={!s.outside||!s.meeting||!s.help} onClick={()=>onFinish({score:Math.max(60,100-s.risks*5),summary:'You prepared, used a clear route, met outside, and requested simulated help.',lesson:'Working alarms and an escape plan support early action. Get outside, stay outside, and arrange real hands-on preparedness with trusted adults.',metrics:{Moves:s.moves,'Route revisions':s.risks}})}>Submit my escape plan</Action>
  </LabLayout>;
}
export function WaterWatch({mission,onFinish,paused}:GameProps) {
  const [s,set]=useMissionState('model',waterSafetyStart), ready=waterLayers.every(l=>s.layers.includes(l));
  return <LabLayout kind="swim" title={`Water Watch · outing ${mission+1}`} description="Layer protection before an outing, respond to a warning, and coordinate a shore-based request for trained help." paused={paused} data={{progress:s.stage/3}}>
    <h3>Layers before the activity</h3><Checks items={waterLayers} selected={s.layers} disabled={s.stage>0} onChange={layers=>set({...s,layers})}/><Formula>Supervision, suitable conditions, water skills, barriers, and fitted approved life jackets serve different purposes. Inflatable toys do not replace a life jacket. This exercise does not teach in-water rescue or CPR.</Formula>
    {ready&&s.stage<3&&<Decision event={waterSafetyEvent(mission,s.stage)} onChoice={choice=>{const event=waterSafetyEvent(mission,s.stage);set(choice===event.correct?{...s,stage:s.stage+1,feedback:event.why}:{...s,risks:s.risks+1,feedback:`Pause and revise. ${event.why}`});}}/>}
    {!ready&&<Notice>Choose all four protection layers to review the scenario.</Notice>}{s.feedback&&<Notice>{s.feedback}</Notice>}
    <Stats><Stat label="Protection layers" value={`${s.layers.length}/4`}/><Stat label="Scenario decisions" value={`${s.stage}/3`}/></Stats><a className="text-link" href="https://www.redcross.org/get-help/how-to-prepare-for-emergencies/types-of-emergencies/water-safety.html" target="_blank" rel="noreferrer">Red Cross · water safety and hands-on training →</a>
    <Action disabled={s.stage!==3} onClick={()=>onFinish({score:Math.max(60,100-s.risks*7),summary:'You planned layered protection and supported a trained response from shore.',lesson:'Pause unsafe outings, alert trained help, and assist from a stable land position. Learn real swimming, first-aid, and rescue skills from qualified instructors.',metrics:{Revisions:s.risks}})}>Submit my water safety plan</Action>
  </LabLayout>;
}
